- bricks/next-builder/src/search-tree/SearchTree.module.css
- bricks/next-builder/src/search-tree/SearchTree.spec.tsx
- bricks/next-builder/src/search-tree/SearchTree.tsx
- bricks/next-builder/src/search-tree/index.tsx
- bricks/next-builder/src/search-tree/utils.spec.tsx
- bricks/next-builder/src/search-tree/utils.tsx
> fix(searchTree): fix search result error

- bricks/frame-bricks/package.json
> feat(): update frame-bricks version

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/cmdb-instance-select/index.tsx
Refs EASY_AGILE-691
请勾选以下两组选项其中之一：
或者：
>
>
> feat(cmdb-instance-select): add extraFields property

- bricks/developers/src/components/BrickDoc/BrickDoc.module.css
- bricks/developers/src/components/BrickPreview/BrickPreview.module.css
Refs: NEXT_BUILDER-1600
请勾选以下两组选项其中之一：
或者：
>
>
> feat(Preview):  preview support dark theme

- bricks/next-builder/src/workbench-quick-entry/WorkbenchQuickEntry.module.css
- bricks/next-builder/src/workbench-quick-entry/WorkbenchQuickEntry.spec.tsx
- bricks/next-builder/src/workbench-quick-entry/WorkbenchQuickEntry.tsx
- bricks/next-builder/src/workbench-quick-entry/index.tsx
> feat(workbench-quick-entry): support thumbnails

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-previewer/package.json
- bricks/next-previewer/src/preview-helper/capture.ts
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- bricks/next-previewer/src/preview-helper/resizeScreenshot.spec.ts
- bricks/next-previewer/src/preview-helper/resizeScreenshot.ts
- bricks/utils/src/broadcast-channel/polyfill.ts
- types/preview/index.d.ts
- yarn.lock
> feat(): support capturing preview screenshot

- bricks/forms/src/general-form/GeneralForm.shadow.less
> style(forms): fomrs默认容器的100%

- bricks/forms/src/general-form/GeneralForm.tsx
- bricks/forms/src/general-form/index.tsx
Reverts easyops-cn/next-basics#1293
> Revert "fix(general-forms): 修改forms默认最大宽度"

- bricks/next-builder/src/workbench-action-list/WorkbenchActionList.tsx
- bricks/next-builder/src/workbench-action/WorkbenchAction.spec.tsx
- bricks/next-builder/src/workbench-action/WorkbenchAction.tsx
Refs: NEXT_BUILDER-1599
请勾选以下两组选项其中之一：
或者：
>
>
>  feat(WorkBenchActionList): support history record

- bricks/flow-builder/src/custom-processors/calcExampleFields.spec.ts
- bricks/flow-builder/src/custom-processors/calcExampleFields.ts
- bricks/flow-builder/src/custom-processors/getRequestExampleOfYaml.spec.ts
- bricks/flow-builder/src/custom-processors/getRequestExampleOfYaml.ts
- bricks/flow-builder/src/index.ts
Refs C_CENTER-32
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): example field processor

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrEnum.tsx
Refs#EVENT-938
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复枚举类型空标签的问题

- bricks/forms/src/general-checkbox/GeneralCheckbox.module.css
- bricks/forms/src/general-checkbox/GeneralCheckbox.spec.tsx
- bricks/forms/src/general-checkbox/GeneralCheckbox.tsx
- bricks/forms/stories/chapters/general-checkbox.ts
> feat(general-checkbox): 支持checkbox设置图标

- bricks/basic-bricks/src/general-modal/GeneralModal.tsx
- bricks/basic-bricks/stories/chapters/general-modal.ts
> feat(general-modal): 支持modal图标src形式

- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
> fix():table允许隐藏表头  refs BRICK_STORE-2755

- bricks/basic-bricks/src/general-modal/GeneralModal.tsx
- bricks/basic-bricks/src/general-modal/index.shadow.less
> fix(general-modal): 修改modal样式

- bricks/forms/src/general-radio/GeneralRadio.spec.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.module.css
- bricks/forms/stories/chapters/general-radio.ts
> feat(general-radio): 支持type=default的单选框带图标;图标设置支持src形式

- bricks/flow-builder/src/custom-processors/getParamsOfDebug.spec.ts
- bricks/flow-builder/src/custom-processors/getParamsOfDebug.ts
- bricks/flow-builder/src/custom-processors/getRequestExampleOfYaml.ts
- bricks/flow-builder/src/custom-processors/interfaces.ts
- bricks/flow-builder/src/index.ts
Refs C_CENTER-39
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): calc debug params processor

- bricks/forms/src/general-checkbox/GeneralCheckbox.module.css
- bricks/forms/stories/chapters/general-checkbox.ts
- bricks/forms/stories/chapters/general-radio.ts
> fix(): 修改文档以及适配暗色模式

- bricks/next-builder/src/workbench-action-list/WorkbenchActionList.spec.tsx
- bricks/next-builder/src/workbench-action-list/WorkbenchActionList.tsx
- bricks/next-builder/src/workbench-action-list/index.tsx
> fix(workBenchActionList): fix jump error

- bricks/next-builder/src/shared/workbench/WorkbenchTree.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/interfaces.ts
Refs: NEXT_BUILDER-1618
请勾选以下两组选项其中之一：
或者：
>
>
> feat(workBenchTree): support render condition

- bricks/next-previewer/src/preview-helper/capture.ts
- types/preview/index.d.ts
Refs: NEXT_BUILDER-1622
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): capture return Blob

- bricks/presentational-bricks/src/brick-alert/BrickAlert.tsx
- bricks/presentational-bricks/src/brick-alert/index.tsx
> feat(brick-alert): 支持配置折叠描述区文案

- bricks/flow-builder/src/custom-processors/calcExampleFields.spec.ts
- bricks/flow-builder/src/custom-processors/calcExampleFields.ts
- bricks/flow-builder/src/custom-processors/expandFields.spec.ts
- bricks/flow-builder/src/custom-processors/expandFields.ts
- bricks/flow-builder/src/custom-processors/getFileTypeFields.spec.ts
- bricks/flow-builder/src/custom-processors/getFileTypeFields.ts
- bricks/flow-builder/src/custom-processors/getRequestExampleOfYaml.ts
- bricks/flow-builder/src/custom-processors/interfaces.ts
- bricks/flow-builder/src/index.ts
Refs C_CENTER-39
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): custom processor

- bricks/presentational-bricks/src/brick-table/index.spec.ts
- bricks/presentational-bricks/src/brick-table/index.tsx
> feat(brick-table): 暴露size/type/pagination属性

- bricks/flow-builder/src/index.ts
- bricks/flow-builder/src/multiple-files-form/MultipleFilesForm.spec.tsx
- bricks/flow-builder/src/multiple-files-form/MultipleFilesForm.tsx
- bricks/flow-builder/src/multiple-files-form/index.spec.ts
- bricks/flow-builder/src/multiple-files-form/index.tsx
Refs C_CENTER-40
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): upload files form

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
> fix(): 修改table斑马纹模式的样式

- bricks/presentational-bricks/src/brick-table/index.spec.ts
- bricks/presentational-bricks/src/brick-table/index.tsx
> fix(): 补充size/type/pagination属性的影响优先级逻辑

- bricks/forms/src/general-radio/index.module.css
> fix(): 删除custom类型下的radio描边 refs BRICK_STORE-2749

- bricks/presentational-bricks/src/brick-table/index.spec.ts
- bricks/presentational-bricks/src/brick-table/index.tsx
> fix(): 兼容在无configProps和无rowSelection的情况下,设置type需要能触发select事件

- bricks/flow-builder/src/custom-processors/calcExampleFields.spec.ts
- bricks/flow-builder/src/custom-processors/calcExampleFields.ts
- bricks/flow-builder/src/custom-processors/expandFields.spec.ts
- bricks/flow-builder/src/custom-processors/expandFields.ts
- bricks/flow-builder/src/custom-processors/getRequestExampleOfYaml.ts
Refs C_CENTER-32
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refactor processor

- bricks/flow-builder/src/custom-processors/getRequestExampleOfYaml.ts
Refs C_CENTER-32
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix regexp

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeDndContext.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-store/WorkbenchStore.tsx
- bricks/next-builder/src/workbench-store/index.tsx
Refs: NEXT_BUILDER-1621
请勾选以下两组选项其中之一：
或者：
>
>
> feat(workbenchBrickTree): support dnd

- bricks/developers/src/brick-document/BrickDocument.tsx
- bricks/flow-builder/package.json
- bricks/flow-builder/src/data-providers/CustomDownloadFile.spec.ts
- bricks/flow-builder/src/data-providers/CustomDownloadFile.ts
- bricks/flow-builder/src/index.ts
- bricks/next-builder/src/events-editor/EventsEditor.module.css
> fix: doc refine

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/package.json
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
- yarn.lock
Refs NEXT_BUILDER-1554
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refactor collect contract

- bricks/forms/src/dynamic-form-item/DynamicFormItem.spec.tsx
- bricks/forms/src/dynamic-form-item/DynamicFormItem.tsx
- bricks/forms/src/dynamic-form-item/index.tsx
> fix(): 动态表单项构件为的columns中的的selec可以设置option选项 refs PIPELINE-1604

- bricks/developers/src/illustration-card/index.module.css
> fix(): fix illustration img style

- bricks/brick-visualization/src/interfaces/brick-visualization.ts
- bricks/brick-visualization/src/visual-property-form/constant.ts
- bricks/brick-visualization/src/visual-property-form/processor.spec.ts
- bricks/brick-visualization/src/visual-property-form/processor.ts
Refs BRICK_STORE-2820
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): group support i18n

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/preview-container/PreviewContainer.spec.tsx
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.spec.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.ts
- bricks/next-builder/src/workbench-store/useListenOnPreviewMessage.spec.tsx
- bricks/next-builder/src/workbench-store/useListenOnPreviewMessage.ts
- bricks/next-previewer/src/preview-helper/inspector.ts
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
Refs: NEXT_BUILDER-1619
请勾选以下两组选项其中之一：
或者：
>
>
> feat(PreviewContainer): support brick drag

- .size-limit.js
- bricks/presentational-bricks/src/i18n/constants.ts
- bricks/presentational-bricks/src/i18n/locales/en.ts
- bricks/presentational-bricks/src/i18n/locales/zh.ts
- bricks/presentational-bricks/src/index.ts
- bricks/presentational-bricks/src/table-transfer/TableTransfer.spec.tsx
- bricks/presentational-bricks/src/table-transfer/TableTransfer.tsx
- bricks/presentational-bricks/src/table-transfer/index.module.css
- bricks/presentational-bricks/src/table-transfer/index.spec.ts
- bricks/presentational-bricks/src/table-transfer/index.tsx
- bricks/presentational-bricks/stories/chapters/table-transfer.ts
> feat(transfer): 新增表格穿梭框构件

- bricks/brick-visualization/src/interfaces/brick-visualization.ts
- bricks/brick-visualization/src/visual-property-form/processor.spec.ts
- bricks/brick-visualization/src/visual-property-form/processor.ts
- bricks/presentational-bricks/src/brick-table/index.tsx
Refs BRICK_STORE-2820
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix typo

- bricks/presentational-bricks/src/table-transfer/TableTransfer.tsx
- bricks/presentational-bricks/src/table-transfer/index.module.css
> fix(transfer): drag style

- bricks/basic-bricks/src/easy-view/index.tsx
> docs(easy-view): add type to @property, add @groupI18N setting

- bricks/presentational-bricks/stories/chapters/index.ts
- bricks/presentational-bricks/stories/chapters/table-transfer.ts
> fix(transfer): update-doc

- bricks/presentational-bricks/src/table-transfer/TableTransfer.tsx
- bricks/presentational-bricks/src/table-transfer/index.tsx
> fix(transfer): fix重置selectedKeys后无法再选bug

- bricks/presentational-bricks/src/brick-table/index.tsx
Refs TRANSFER-112
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-table): add extraRows property

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-builder/src/workbench-store/WorkbenchStore.tsx
- bricks/next-builder/src/workbench-store/index.tsx
Refs: NEXT_BUILDER-1621
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support snippet apply and move event to store

- bricks/brick-visualization/src/visual-property-form/constant.ts
- bricks/brick-visualization/src/visual-property-form/processor.spec.ts
- bricks/brick-visualization/src/visual-property-form/processor.ts
- bricks/presentational-bricks/src/brick-descriptions/index.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
- bricks/presentational-bricks/stories/chapters/brick-descriptions.ts
- bricks/presentational-bricks/stories/chapters/brick-table.ts
Refs BRICK_STORE-2812 BRICK_STORE-2811
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine doc

- bricks/presentational-bricks/src/table-transfer/TableTransfer.tsx
> fix(transfer): fix点击表格行checkbox之外超出最大限制时没有禁用选项的问题

- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
Closes TRANSFER-115
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-table): unify processing logic for rowKey

- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- bricks/general-auth/src/general-login/MFALogin.tsx
- yarn.lock
Refs: ITSERVICE_NEXT-4087
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 多因子认证接口增加org入参

- bricks/basic-bricks/src/general-modal/index.tsx
- bricks/basic-bricks/stories/chapters/general-modal.ts
refs BRICK_STORE-2848
https://tapd.easyops.local/pages/viewpage.action?pageId=38273741
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): refine general-modal doc

- bricks/developers/src/brick-document/BrickDocument.spec.tsx
- bricks/developers/src/brick-document/BrickDocument.tsx
- bricks/developers/src/components/BrickDoc/BrickDoc.module.css
- bricks/presentational-bricks/src/brick-table/index.tsx
Refs BRICK_STORE-2855
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine document view

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.module.css
- bricks/next-builder/src/workbench-store/index.tsx
Refs: NEXT_BUILDER-1619
请勾选以下两组选项其中之一：
或者：
>
>
> feat(PreviewContainer): addNode support redirect parent

- bricks/presentational-bricks/src/table-transfer/TableTransfer.tsx
> fix(transfer): fix transfer重新赋selectedKeys属性后再也无法选中bug

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
> feat(): support previewer auto resize

- bricks/basic-bricks/src/grid-layout/index.ts
- bricks/forms/src/general-buttons/index.tsx
- bricks/forms/src/general-modal/index.tsx
- bricks/forms/stories/chapters/general-modal.ts
close BRICK_STORE-2839 BRICK_STORE-2836 BRICK_STORE-2840
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fixDoc

- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.tsx
- bricks/presentational-bricks/src/modal-confirm/index.tsx
- bricks/presentational-bricks/stories/chapters/modal-confirm.ts
refs BRICK_STORE-2847
https://tapd.easyops.local/pages/viewpage.action?pageId=38273798
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): refine modal-confirm doc

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-previewer/src/preview-helper/inspector.ts
> fix(previewContainer): fix brick drop and still high light state

- bricks/forms/src/general-input/index.tsx
- bricks/forms/stories/chapters/general-input.ts
> fix(forms):更新input组件的示例文档

- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
- bricks/next-builder/src/workbench-store/WorkbenchStore.tsx
> fix(): add birck install info and fix popup down error

- bricks/basic-bricks/src/general-button/index.tsx
- bricks/basic-bricks/src/general-card/GeneralCard.tsx
- bricks/basic-bricks/src/general-card/index.tsx
- bricks/basic-bricks/src/interfaces/general-card.ts
- bricks/basic-bricks/src/interfaces/index.ts
- bricks/basic-bricks/src/micro-app/index.tsx
- bricks/basic-bricks/stories/chapters/general-card.ts
- bricks/brick-visualization/src/visual-property-form/constant.ts
- bricks/forms/src/general-checkbox/index.tsx
- bricks/forms/src/general-form/index.tsx
- bricks/forms/src/general-input/index.tsx
- bricks/forms/src/general-select/index.tsx
- bricks/forms/stories/chapters/general-form.ts
- bricks/forms/stories/chapters/general-select.ts
- bricks/presentational-bricks/src/brick-link/index.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
> refine general-card doc 

- bricks/basic-bricks/src/micro-app/MicroApp.shadow.css
- bricks/basic-bricks/src/micro-app/MicroApp.spec.tsx
- bricks/basic-bricks/src/micro-app/MicroApp.tsx
- bricks/basic-bricks/src/micro-app/index.spec.ts
> feat(): micro-app 兼容ui6.0和ui8.0的样式

- bricks/developers/src/stories/chapters/business-bricks/cmdb-instances/instance-tree-template.ts
- bricks/developers/src/stories/chapters/business-bricks/tool-and-flow/enhanced-tools-input-form.ts
- bricks/developers/src/stories/chapters/business-bricks/tool-and-flow/index.ts
- bricks/developers/src/stories/chapters/business-bricks/tool-and-flow/tool-execution-form-template.ts
- bricks/developers/src/stories/docs/tools/enhanced-tools-input-form.md
> docs(): fix docs

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
- bricks/presentational-bricks/src/brick-table/BrickTable.spec.tsx
- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
close GXCXJF-402
请勾选以下两组选项其中之一：
或者：
>
>
> feat(presentational-bricks): table add invaidRow style

- bricks/developers/src/stories/chapters/business-bricks/cmdb-instances/instance-change-history-template.ts
- bricks/developers/src/stories/chapters/business-bricks/cmdb-instances/instance-timeline-template.ts
- bricks/developers/src/stories/docs/cmdb-instances/instance-timeline.md
> docs(): edit docs

- bricks/basic-bricks/package.json
- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
- bricks/basic-bricks/src/general-custom-buttons/index.module.css
- yarn.lock
Refs LAUNCHPAD-100
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-custom-buttons): fix clickable area of link in dropdown

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.ts
- bricks/next-previewer/src/preview-helper/inspector.ts
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> feat(): support Iframe Drag Of Different Origin

- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/index.tsx
> chore(): style update

- bricks/basic-bricks/src/micro-app/MicroApp.shadow.css
- bricks/basic-bricks/src/micro-app/MicroApp.spec.tsx
- bricks/basic-bricks/src/micro-app/MicroApp.tsx
- bricks/basic-bricks/src/micro-app/index.spec.ts
> chore(): 删除ui8.0特性开关的判断

- bricks/forms/src/general-radio/index.tsx
- bricks/forms/stories/chapters/general-radio.ts
> docs(radio): edit docs

- bricks/next-builder/src/search-tree/SearchTree.tsx
> fix(SearchTree): template link error

- bricks/basic-bricks/src/easy-view/index.tsx
- bricks/basic-bricks/src/general-card/index.tsx
- bricks/basic-bricks/src/general-modal/index.tsx
- bricks/basic-bricks/src/list-container/index.tsx
- bricks/basic-bricks/src/micro-app/index.tsx
- bricks/basic-bricks/src/popover-container/index.tsx
- bricks/forms/src/general-checkbox/index.tsx
- bricks/forms/src/general-input/index.tsx
- bricks/forms/src/general-select/index.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
- bricks/presentational-bricks/src/modal-confirm/index.tsx
> docs(): remove redundant @groupI18N

- bricks/basic-bricks/src/micro-app/MicroApp.shadow.css
- bricks/basic-bricks/src/micro-app/MicroApp.spec.tsx
- bricks/basic-bricks/src/micro-app/MicroApp.tsx
- bricks/basic-bricks/src/micro-app/index.spec.ts
- bricks/basic-bricks/src/page-title/PageTitle.spec.tsx
- bricks/basic-bricks/src/page-title/PageTitle.tsx
- bricks/basic-bricks/src/utils.spec.ts
- bricks/basic-bricks/src/utils.ts
> fix(): micro-app兼容ui8.0样式

- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeDndContext.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
> feat(): tree drop update

- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
> chore(): update style

- bricks/forms/src/general-auto-complete/GeneralAutoComplete.tsx
- bricks/forms/src/general-auto-complete/index.tsx
- bricks/forms/stories/chapters/general-auto-complete.ts
> fix(forms.GeneralAutoComplete): generalAutoComplete添加disabled属性

- bricks/presentational-bricks/stories/chapters/brick-result.ts
> chore(): update brick-result stroy

- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
Refs BRICK_STORE-2809
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 导出的才会在构件库列表中展示

- bricks/basic-bricks/src/micro-app/MicroApp.shadow.css
> chore(): update micro-view style

- bricks/presentational-bricks/src/brick-table/index.tsx
refs SERVICE_OBSERVE-1299
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-table): 切换分页和页码的时候不应该触发sort.update事件

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
> fix(forms): fix select search error when value type is number

- bricks/forms/stories/chapters/general-radio.ts
> docs(): 添加自定义插画类型的radio refs DEVOPS_MANAGEMENT-412

- bricks/presentational-bricks/src/dropdown-select/DropdownSelect.module.css
- bricks/presentational-bricks/src/dropdown-select/DropdownSelect.spec.tsx
- bricks/presentational-bricks/src/dropdown-select/DropdownSelect.tsx
- bricks/presentational-bricks/src/dropdown-select/index.tsx
refs MONITOR-3661
请勾选以下两组选项其中之一：
或者：
>
>
> feat(dropdown-select): add  selectTipText&selectBoxStyle properties

- bricks/forms/src/input-with-unit/InputWithUnit.spec.tsx
- bricks/forms/src/input-with-unit/InputWithUnit.tsx
- bricks/forms/src/input-with-unit/index.tsx
Refs MONITOR-3666
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 去除自动计算和增加最小值

- bricks/presentational-bricks/src/dropdown-select/DropdownSelect.module.css
refs MONITOR-3661
请勾选以下两组选项其中之一：
或者：
>
>
> style(dropdown-select): modify selectTipText style

- bricks/presentational-bricks/src/brick-table/index.tsx
> fix(brick-table):平铺rowSelection属性到外层

- bricks/presentational-bricks/src/brick-tag/BrickTag.spec.tsx
- bricks/presentational-bricks/src/brick-tag/BrickTag.tsx
- bricks/presentational-bricks/src/brick-tag/index.tsx
> feat(): brick-tag添加useBrick和useBrickData属性 refs PERMISSION-252

- bricks/presentational-bricks/src/brick-tag/index.tsx
- bricks/presentational-bricks/src/general-label/index.tsx
- bricks/presentational-bricks/src/markdown-display/index.tsx
> chore(): add back required comment tag

- bricks/developers/src/brick-document/BrickDocument.tsx
Closes BRICK_STORE-2979 BRICK_STORE-2980
请勾选以下两组选项其中之一：
或者：
>
>
> feat(BrickDocument): add support for extendedTypes and indexSignature

- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.spec.tsx
- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.tsx
Refs: NEXT_BUILDER-1665
请勾选以下两组选项其中之一：
或者：
>
>
> feat(markdownEditor): support image set size

- bricks/forms/src/general-auto-complete/index.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
> docs(): docs refine

- bricks/developers/src/brick-document/BrickDocument.tsx
Closes BRICK_STORE-2983
请勾选以下两组选项其中之一：
或者：
>
>
> feat(BrickDocument): add support for description of enum and interface

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
- bricks/presentational-bricks/src/brick-table/BrickTable.spec.tsx
- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
close CD-2730
请勾选以下两组选项其中之一：
或者：
>
>
> feat(presentational-bricks): brickTable support disabledRow style

- bricks/basic-bricks/src/general-notification/index.tsx
- bricks/developers/src/brick-document/BrickDocument.spec.tsx
- bricks/developers/src/brick-document/BrickDocument.tsx
- bricks/developers/src/brick-document/constants.ts
- bricks/developers/src/interfaces/brick-document.ts
- bricks/developers/src/interfaces/index.ts
- bricks/forms/src/dynamic-form-item-v2/index.tsx
- bricks/forms/src/general-auto-complete/index.tsx
- bricks/forms/src/general-date-picker/index.tsx
- bricks/forms/src/general-input-number/index.tsx
- bricks/forms/src/general-switch/index.tsx
> fix(): doc refine

- bricks/forms/src/upload-img/UploadImg.spec.tsx
- bricks/forms/src/upload-img/UploadImg.tsx
- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.tsx
Refs: NEXT_BUILDER-1657
请勾选以下两组选项其中之一：
或者：
>
>
> feat(UploadImg): support upload to compress

- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/datetime-selector/DatetimeSelector.tsx
- bricks/presentational-bricks/src/datetime-selector/index.tsx
- yarn.lock
refs SERVICE_OBSERVE-1575
请勾选以下两组选项其中之一：
或者：
>
>
> feat(datetime-selector): 指定范围时间选择器增加限制选择近n天属性

- bricks/next-builder/src/events-editor/components/handler-item/HandlerItem.tsx
- bricks/next-builder/src/shared/visual-events/getProcessedEvents.ts
- bricks/next-builder/src/workbench-tree/index.tsx
Refs: NEXT_BUILDER-1626
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): event render error when callback.success was null

- bricks/developers/src/brick-document/BrickDocument.tsx
Closes BRICK_STORE-2980
请勾选以下两组选项其中之一：
或者：
>
>
> fix(BrickDocument): fix interface extended links

- bricks/basic-bricks/src/app-bar-breadcrumb/AppbarBreadcrumb.tsx
- bricks/basic-bricks/src/app-bar/AppBarBreadcrumb/AppBarBreadcrumb.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBarBreadcrumb/AppBarBreadcrumb.tsx
> feat(): breadcrumb add useCurrentMenuTitle

- bricks/next-builder/src/workbench-context-menu/WorkbenchContextMenu.tsx
- bricks/next-builder/src/workbench-context-menu/index.tsx
> feat(workbenchContextMenu): support paste child route

- bricks/basic-bricks/src/general-anchor/GeneralAnchor.tsx
> fix(basic-bricks): fix anchor构件在location.hash为空时仍会向上滚一点的问题

- bricks/forms/src/general-form/index.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
- bricks/presentational-bricks/src/brick-tag/BrickTag.tsx
- bricks/presentational-bricks/src/brick-tag/index.tsx
- bricks/presentational-bricks/src/brick-value-mapping/index.tsx
- bricks/presentational-bricks/src/interfaces/brick-tag.ts
- bricks/presentational-bricks/stories/chapters/brick-value-mapping.ts
Refs BRICK_STORE-2861,BRICK_STORE-2861,BRICK_STORE-2850
请勾选以下两组选项其中之一：
或者：
>
>
> docs(): doc refine

- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.spec.ts
- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.ts
- bricks/next-builder/src/index.ts
- bricks/next-builder/src/lazy-bricks.yaml
- bricks/next-builder/src/preview-container/PreviewContainer.module.css
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/workbench-data-tree/WorkbenchDataTree.spec.tsx
- bricks/next-builder/src/workbench-data-tree/WorkbenchDataTree.tsx
- bricks/next-builder/src/workbench-data-tree/index.spec.ts
- bricks/next-builder/src/workbench-data-tree/index.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.spec.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.ts
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
Refs: NEXT_BUILDER-1632
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support dataTree hover highlight brick

- bricks/forms/stories/chapters/general-radio.ts
> docs(): 修改radio中插画示例 refs DEVOPS_MANAGEMENT-412

- bricks/basic-bricks/src/general-anchor/GeneralAnchor.module.css
- bricks/basic-bricks/src/general-anchor/GeneralAnchor.tsx
- bricks/basic-bricks/src/general-anchor/index.tsx
Refs INSTANCE-2529
请勾选以下两组选项其中之一：
或者：
>
>
> fix(anchor): fix页面滚动且在target区域内anchor高亮消失bug

- bricks/developers/src/brick-document/constants.ts
- bricks/forms/src/cmdb-instance-select/index.tsx
- bricks/forms/src/general-auto-complete/index.tsx
- bricks/forms/src/general-form/index.tsx
- bricks/forms/src/general-radio/index.tsx
- bricks/forms/src/general-select/index.tsx
Refs BRICK_STORE-2993
请勾选以下两组选项其中之一：
或者：
>
>
> docs(): refine docs

- bricks/basic-bricks/src/resizable-box/ResizableBox.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
- bricks/next-builder/src/workbench-component-select/index.tsx
> feat(componentSelect): add field isShowSuggest

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> Ella/form b UI lder 20

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- types/preview/index.d.ts
> feat():新增debug事件监听

- bricks/forms/src/general-form/GeneralForm.tsx
> fix(GeneralForm): max-width eval error

- bricks/presentational-bricks/src/brick-illustration/BrickIllustration.tsx
- bricks/presentational-bricks/src/brick-illustration/index.tsx
- bricks/presentational-bricks/src/brick-result/BrickResult.tsx
- bricks/presentational-bricks/src/brick-result/index.tsx
- package.json
- yarn.lock
Refs:BRICK_STORE-2995
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update illustrations config

- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/stories/chapters/general-radio.ts
> feat(): 支持radio自定义icon样式

- bricks/developers/src/brick-book/BrickBook/BrickBook.tsx
- bricks/developers/src/brick-book/BrickBook/style.module.css
- bricks/developers/src/brick-book/BrickDemo/BrickDemo.module.css
- bricks/developers/src/components/BrickDoc/BrickDoc.module.css
Refs BRICK_STORE-3006
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): brick-demo dark mode

- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.module.css
close NEXT_UIKIT-142
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): changeAppBar

- bricks/forms/src/general-input-number-range/GeneralInputNumberRange.spec.tsx
- bricks/forms/src/general-input-number-range/GeneralInputNumberRange.tsx
- bricks/forms/src/general-input-number-range/index.spec.ts
- bricks/forms/src/general-input-number-range/index.tsx
- bricks/forms/src/index.ts
> feat():新增数字区间构件

- bricks/flow-builder/src/custom-processors/getRequestExampleOfYaml.ts
- bricks/flow-builder/src/multiple-files-form/MultipleFilesForm.tsx
> fix(): support required

- bricks/basic-bricks/src/app-bar/AppSetting/AppSetting.tsx
- bricks/general-auth/src/general-logout/index.ts
- declarations/global.d.ts
BRICK_STORE-3008
请勾选以下两组选项其中之一：
或者：
>
>
> feat(logout): 平台登出后重定向回登出前url

- .size-limit.js
- bricks/basic-bricks/src/page-error/PageError.spec.tsx
- bricks/presentational-bricks/src/brick-illustration/BrickIllustration.spec.tsx
- bricks/presentational-bricks/src/brick-illustration/BrickIllustration.tsx
- bricks/presentational-bricks/src/brick-result/BrickResult.spec.tsx
- bricks/presentational-bricks/src/brick-result/BrickResult.tsx
Refs:BRICK_STORE-3000
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): add 添加特性开关 support-new-illustrations

- bricks/presentational-bricks/src/brick-table/index.spec.ts
- bricks/presentational-bricks/src/brick-table/index.tsx
Refs: SUBSCRIBE-62
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 新增event事件: select.row.keys.update

- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.module.css
- bricks/basic-bricks/src/app-bar/DesktopDirContent/DesktopDirContent.module.css
- bricks/basic-bricks/src/app-bar/DesktopSlider/DesktopSlider.module.css
- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.module.css
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.module.css
- bricks/basic-bricks/src/app-bar/site-map/SiteMap.module.css
close NEXT_UIKIT-142
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): changeBgColor

- .size-limit.js
- bricks/presentational-bricks/src/table-transfer/TableTransfer.spec.tsx
- bricks/presentational-bricks/src/table-transfer/TableTransfer.tsx
> fix(presentational-bricks): fix tableTransfer的一些小bug

- bricks/presentational-bricks/src/brick-table/index.tsx
> chore(): update text

- bricks/forms/src/user-or-user-group-select/index.tsx
> fix(): missing objectList property into component

- bricks/forms/src/general-input-number-range/GeneralInputNumberRange.tsx
- bricks/forms/src/general-input-number-range/index.tsx
- bricks/next-builder/src/i18n/constants.ts
- bricks/next-builder/src/i18n/locales/en.ts
- bricks/next-builder/src/i18n/locales/zh.ts
- bricks/next-builder/src/workbench-component-select/constants.ts
> feat():组件选择新增分类表单项，数字区间构件支持placeholder，支持form管控值变更

- bricks/basic-bricks/src/page-error/PageError.spec.tsx
- bricks/presentational-bricks/src/brick-illustration/BrickIllustration.spec.tsx
- bricks/presentational-bricks/src/brick-illustration/BrickIllustration.tsx
- bricks/presentational-bricks/src/brick-result/BrickResult.spec.tsx
- bricks/presentational-bricks/src/brick-result/BrickResult.tsx
> chore(): add misc config

- bricks/forms/src/general-input-number-range/GeneralInputNumberRange.spec.tsx
- bricks/forms/src/general-input-number-range/GeneralInputNumberRange.tsx
- bricks/forms/src/general-input-number-range/index.tsx
> fix():修复form默认值无法代理到数字区间组件

- bricks/presentational-bricks/src/brick-result/BrickResult.tsx
- bricks/presentational-bricks/src/brick-result/components/IllustrationWrapper.tsx
- bricks/presentational-bricks/src/brick-result/index.tsx
- bricks/presentational-bricks/src/interfaces/brick-result.ts
close BRICK_STORE-3012
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brickResult): brickResult support new empty illustrations and size

- bricks/forms/src/custom-templates/tpl-cmdb-object-attr-add.ts
- bricks/forms/src/i18n/locales/en.ts
- bricks/forms/src/i18n/locales/zh.ts
ref: INSTANCE-2591
请勾选以下两组选项其中之一：
或者：
>
>
> feat(custom-templates): 属性说明支持50个字符

- bricks/presentational-bricks/src/brick-illustration/BrickIllustration.spec.tsx
- bricks/presentational-bricks/src/brick-illustration/BrickIllustration.tsx
- bricks/presentational-bricks/src/brick-illustration/index.module.css
- bricks/presentational-bricks/src/brick-illustration/index.tsx
close BRICK_STORE-3021
请勾选以下两组选项其中之一：
或者：
>
>
> feat(BrickIllustration):  BrickIllustration support set size

- bricks/forms/src/general-input-number-range/GeneralInputNumberRange.tsx
- bricks/forms/src/general-input-number-range/index.spec.ts
- bricks/forms/src/general-input-number-range/index.tsx
> fix():修复数字区间最大值最小值的判断，新增校验方法

- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.tsx
close BLUEPRINT-82
请勾选以下两组选项其中之一：
或者：
>
>
> feat(CardItem): icon-as-background card support bottomRightOperate

- bricks/next-builder/src/function-debugger-toolbar-v2/FunctionDebuggerToolbarV2.module.css
- bricks/next-builder/src/function-debugger-toolbar-v2/FunctionDebuggerToolbarV2.spec.tsx
- bricks/next-builder/src/function-debugger-toolbar-v2/FunctionDebuggerToolbarV2.tsx
- bricks/next-builder/src/function-debugger-toolbar-v2/index.spec.ts
- bricks/next-builder/src/function-debugger-toolbar-v2/index.tsx
- bricks/next-builder/src/index.ts
- bricks/next-builder/src/lazy-bricks.yaml
Ref: NEXT_BUILDER-1722
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): feat FunctionDebuggerToolbarV2

- bricks/forms/src/general-input-number-range/GeneralInputNumberRange.tsx
- bricks/forms/src/general-input-number-range/index.tsx
> fix():修复无法输入数字0

- bricks/next-builder/src/workbench-store/WorkbenchStore.tsx
- bricks/next-builder/src/workbench-store/index.tsx
> feat():新增属性activeInstanceId，扩展preview可指定默认选中节点

- bricks/basic-bricks/src/app-bar/AppDocumentLink/AppDocumentLink.tsx
> fix(): 解决appDocumentLink的tooltip位置被覆盖问题

- bricks/flow-builder/src/custom-processors/getFunctionStep.spec.ts
- bricks/flow-builder/src/custom-processors/getFunctionStep.ts
> fix(): 修复flow-builder编排调试中,拓扑调试值的取值不正确问题

- bricks/frame-bricks/src/nav-menu/NavMenu.spec.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
> feat(nav-menu): nav-menu支持使用自定义构件展示  refs INSTANCE-2651

- bricks/forms/src/general-input-number/index.tsx
> chore(): docs refine

- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
Refs NEXT_BUILDER-1873
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): state 变量支持文档配置，以便在挂件文档中展示其属性信息

- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.module.css
- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.spec.tsx
- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.tsx
> feat(): markdown构件样式调整 refs BRICK_STORE-3028

- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> fix(): update root node and update storyboard error

- bricks/forms/src/time-range-picker/TimeRangePicker.spec.tsx
- bricks/forms/src/time-range-picker/TimeRangePicker.tsx
- bricks/forms/src/time-range-picker/index.tsx
Refs:MONITOR-3830
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 构件支持选择近N天

- .size-limit.js
- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/data-providers/MoveStoryboardNodeAndReorder.spec.ts
- bricks/next-builder/src/data-providers/MoveStoryboardNodeAndReorder.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- types/preview/index.d.ts
> fix:() fix drag move route brick error

- bricks/basic-bricks/src/utils.ts
Refs INSTANCE-2619
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): getNewUIStatus适用模板里增加两个

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> feat(): support match api cache tips

- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
This reverts commit 15561b1501ec94f2e9221d37aa6642e6835a9f01.
请勾选以下两组选项其中之一：
或者：
>
>
> Revert "fix(): 导出的才会在构件库列表中展示"

- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
> fix(NavMenu): fix nav-menu render error

- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.module.css
> fix(): markdown构件样式再次调整  refs BRICK_STORE-3028

- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> chore(): delete unuse code

- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.module.css
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- bricks/next-builder/src/workbench-cache-action/index.tsx
- types/preview/index.d.ts
> feat(): support user set build delay time

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
> feat(BrickTree): not allow drag in Slot

- bricks/next-builder/src/workbench-data-tree/index.tsx
- bricks/next-builder/src/workbench-tree/index.tsx
> fix(): fix workbench tree click triggered twice

- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.tsx
- bricks/basic-bricks/src/app-bar/DesktopDir/DesktopDir.tsx
> fix(): support public cdn for app icons in launchpad

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeContext.ts
- bricks/next-builder/src/workbench-tree/index.tsx
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> feat(): support workbench Tree click not update page

- bricks/next-builder/src/i18n/constants.ts
- bricks/next-builder/src/i18n/locales/en.ts
- bricks/next-builder/src/i18n/locales/zh.ts
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.module.css
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.spec.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
- bricks/next-builder/src/workbench-component-select/constants.ts
- bricks/next-builder/src/workbench-component-select/index.tsx
- bricks/next-builder/src/workbench-component-select/processor.spec.ts
- bricks/next-builder/src/workbench-component-select/processor.ts
Refs NEXT_BUILDER-1755
请勾选以下两组选项其中之一：
或者：
>
>
1.在组件库中可直接查看每个构件的文档(hover 直接显示查看文档的 icon)，不需要把构件放到画布中然后再查看。
2.在组件库中可直接查看该构件下存在哪些 snippet，然后在下方展示可用户直接推拽。把现有的 snippet 片段进行过滤，找到单个构件的片段归属于某个构件中。
> fix(): component select optimize

- bricks/developers/src/share/processor.spec.ts
- bricks/developers/src/share/processor.ts
Refs  NEXT_BUILDER-1824
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复不导出的挂件不在开发者中心展示

- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
> fix(): do not prepend public root for widget thumbnails

- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- types/preview/index.d.ts
> fix(): fix move error

- bricks/next-builder/package.json
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.spec.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- bricks/next-builder/src/workbench-cache-action/index.tsx
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
- yarn.lock
> Ella/form b UI lder 84

- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
> fix(WorkbenchTree): skipNotify default value error

- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
> fix():formItem相关，控制无需自动buildAndPush

- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- yarn.lock
Refs BRICK_STORE-3037
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): add csrfToken

- bricks/next-builder/src/utils/getGraphTreeByBuilderData.spec.ts
- bricks/next-builder/src/utils/getGraphTreeByBuilderData.ts
- bricks/next-builder/src/workbench-cache-action/CacheActionList.spec.tsx
- bricks/next-builder/src/workbench-cache-action/CacheActionList.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- types/preview/index.d.ts
> fix(): fix query not found when brick update

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> fix(): update routPath and fix insepect button disabled error

- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.spec.tsx
- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.tsx
- bricks/presentational-bricks/src/modal-confirm/__snapshots__/ModalConfirm.spec.tsx.snap
- bricks/presentational-bricks/src/modal-confirm/index.tsx
> feat(): 提示框增加width属性  refs INSTANCE-2681

- bricks/general-auth/src/general-signup/GeneralSignup.tsx
Closes EASYOPSAIR-29
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-signup): encrypt password only when using AuthApi_register

- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.spec.tsx
- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
- bricks/basic-bricks/src/general-custom-buttons/index.tsx
Closes INSTANCE-2727
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): general-custom-buttons支持打开事件

- bricks/basic-bricks/src/flex-layout/index.tsx
- bricks/basic-bricks/stories/chapters/flex-layout.ts
> feat(): flex-layout支持gap属性

- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.tsx
- bricks/basic-bricks/src/app-bar/DesktopDir/DesktopDir.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
> fix(): fix image url with data uri

- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- bricks/next-builder/src/workbench-cache-action/index.tsx
- types/preview/index.d.ts
> feat(cacheAction): support build not refresh

- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
> fix(): template search nothing

- bricks/forms/src/general-select/GeneralSelect.module.css
- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- package.json
- yarn.lock
close none
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): changeDropDownColor

- bricks/presentational-bricks/src/brick-result/BrickResult.tsx
- bricks/presentational-bricks/src/brick-result/index.tsx
> fix(brick-result): BrickResult support emptyResultSize

- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.ts
- bricks/next-builder/src/shared/visual-events/constants.ts
> fix(): add new context action: context.refresh

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- bricks/next-builder/src/workbench-cache-action/index.tsx
> fix(): route render error

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
- bricks/next-builder/src/shared/storyboard/bundleMenu.spec.ts
- bricks/next-builder/src/shared/storyboard/bundleMenu.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
> feat(): bundle menu with i18n

- bricks/basic-bricks/stories/chapters/general-custom-buttons.ts
- bricks/basic-bricks/stories/chapters/general-drawer.ts
- bricks/basic-bricks/stories/chapters/general-modal.ts
- bricks/forms/src/general-input/GeneralInput.spec.tsx
- bricks/forms/src/general-input/GeneralInput.tsx
- bricks/forms/src/general-input/index.tsx
请勾选以下两组选项其中之一：
或者：
>
>
- [] 手动验证过新特性可以正常工作。
> feat(): 增加按钮描述以及给通用下拉框增加size属性

- bricks/presentational-bricks/src/brick-tag/BrickTag.tsx
- bricks/presentational-bricks/src/brick-tag/index.module.css
ref: MONITOR-3931
请勾选以下两组选项其中之一：
或者：
>
>
> feat(presentational-bricks): Tag.checkableTag在active的情况下字体颜色加深

- bricks/basic-bricks/src/app-bar-breadcrumb/AppbarBreadcrumb.tsx
- bricks/basic-bricks/src/app-bar-breadcrumb/index.tsx
> feat(): add menu props

- bricks/basic-bricks/src/app-bar/LaunchpadButton/LaunchpadButton.tsx
E.g., when a user click a link, and then click the launchpad button before the new page get loaded.
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix launchpad blur not cleared in certain case

- bricks/basic-bricks/stories/chapters/general-custom-buttons.ts
- bricks/basic-bricks/stories/chapters/general-drawer.ts
- bricks/presentational-bricks/stories/chapters/brick-table.ts
> feat(): fix doms

- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/presentational-bricks/stories/chapters/brick-table.ts
> fix(): fix menu css and dom

- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeContext.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-data-tree/index.tsx
- bricks/next-builder/src/workbench-tree/index.tsx
> feat(workbenchTree): support context menu in anywhere

- bricks/next-builder/src/workbench-pane/WorkbenchPane.tsx
> feat(WorkbenchPane): add title slot

- bricks/forms/src/general-date-picker/GeneralDatePicker.spec.tsx
- bricks/forms/src/general-date-picker/GeneralDatePicker.tsx
refs BRICK_STORE-3083
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 切换月/年份，未点击日期时，点击确定后表单项未赋值

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
ref: VIEW-455
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 编辑模型详情中的结构体数组时,列数据可能过多,增加横向滚动

- bricks/basic-bricks/package.json
- bricks/basic-bricks/rollup.stories.js
- bricks/basic-bricks/stories/chapters/easy-view.ts
- bricks/basic-bricks/stories/chapters/general-button.ts
- bricks/basic-bricks/stories/chapters/micro-view.ts
- bricks/basic-bricks/stories/images/basic-bricks.easy-view.svg
- bricks/basic-bricks/stories/images/basic-bricks.general-button.svg
- bricks/basic-bricks/stories/images/basic-bricks.micro-view.svg
- bricks/basic-bricks/stories/images/index.ts
Refs BRICK_STORE-3050
请勾选以下两组选项其中之一：
或者：
>
>
> replace new icon

- bricks/next-builder/src/builder-container/interfaces.ts
- bricks/next-builder/src/data-providers/getStoriesJson.ts
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
Refs BRICK_STORE-307
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 挂件未导出时不再构件库中展示

- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
> fix(): hide icon

- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
> fix(): hide divider

- .size-limit.js
- bricks/developers/src/stories/chapters/atom-bricks/topology-v2/general-graph.ts
- bricks/developers/src/stories/docs/graph/general-graph.md
> docs(): graph 添加curve示例demo

- bricks/basic-bricks/src/advance-list-container/AdvanceListContainer.tsx
> fix():快速查询默认选中状态回显 Closes INSTANCE-2769

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/shared/workbench/WorkbenchTree.module.css
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeDndContext.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-brick-tree/index.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.spec.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
- bricks/next-builder/src/workbench-component-select/index.tsx
- types/preview/index.d.ts
> feat(): support ComponentSelect drag to brickTree

- bricks/basic-bricks/stories/chapters/transform-agent.ts
- bricks/developers/src/stories/docs/basic-providers/http-proxy.md
- bricks/presentational-bricks/src/basic-icon/index.tsx
Ref: BRICK_STORE-3075
请勾选以下两组选项其中之一：
或者：
>
>
> docs(): 整改文档

- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
> fix(): 重新打包

- bricks/basic-bricks/src/general-drawer/GeneralDrawer.tsx
- bricks/basic-bricks/src/general-drawer/index.tsx
> fix():general-drawer宽度可以使用字符串来自适应屏幕 Closes INSTANCE-2768

- bricks/forms/src/general-select/GeneralSelect.module.css
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
> feat(): 重新打包及修改普通下拉框颜色

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> fix(): fix preview url update

- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.ts
- bricks/next-builder/src/shared/visual-events/constants.ts
> fix(): add new builtin event actions

- bricks/next-builder/src/utils/normalizeTreeNodeWithPath.spec.ts
- bricks/next-builder/src/utils/normalizeTreeNodeWithPath.ts
> feat(): add isContainer in tree node

- bricks/presentational-bricks/deploy-default/package.conf.yaml
- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/brick-user/BrickUser.spec.tsx
- bricks/presentational-bricks/src/brick-user/BrickUser.tsx
- yarn.lock
> fix(): refine brick user, don't request all users info

- bricks/next-previewer/src/preview-helper/capture.ts
> fix(): enable foreignObjectRendering

- bricks/basic-bricks/src/app-bar-logo/AppBarLogo.tsx
- bricks/basic-bricks/src/app-bar-logo/index.spec.ts
- bricks/basic-bricks/src/app-bar-logo/index.tsx
- bricks/basic-bricks/src/app-bar/AppBarBreadcrumb/AppBarBreadcrumb.tsx
- bricks/basic-bricks/src/index.ts
- bricks/basic-bricks/src/menu-bar/LogoBar/LogoBar.module.css
- bricks/basic-bricks/src/menu-bar/LogoBar/LogoBar.spec.tsx
- bricks/basic-bricks/src/menu-bar/LogoBar/LogoBar.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
> feat(): support appbar logo

- bricks/developers/src/stories/chapters/atom-bricks/topology-v2/general-topology.ts
- bricks/presentational-bricks/stories/chapters/brick-tag.ts
> docs(): 修改文档

- bricks/basic-bricks/src/menu-bar/LogoBar/LogoBar.tsx
> fix(): fix logoBar render error when app was not found

- bricks/presentational-bricks/src/general-image/GeneralImage.module.css
- bricks/presentational-bricks/src/general-image/GeneralImage.tsx
- bricks/presentational-bricks/src/general-image/index.tsx
> feat(GeneralImage): support imgStyle

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
ref: MONITOR-4024
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms): 可疑接口缺少page参数

- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
- bricks/basic-bricks/src/general-popup/style.shadow.css
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/utils/normalizeTreeNodeWithPath.spec.ts
- bricks/next-builder/src/utils/normalizeTreeNodeWithPath.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- types/preview/index.d.ts
> fix(): fix some problem

- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/brick-user/BrickUser.spec.tsx
- bricks/presentational-bricks/src/brick-user/BrickUser.tsx
- yarn.lock
Closes INSTANCE-2727
请勾选以下两组选项其中之一：
或者：
>
>
> WIP: feat(): refine brick-user

- bricks/forms/package.json
- bricks/forms/src/upload-img/UploadImg.tsx
- yarn.lock
Closes INSTANCE-2847
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): uploadImage 使用mentions时优化接口调用性能

- bricks/basic-bricks/src/app-bar-breadcrumb/index.tsx
> fix(): set noCurrentApp default value to undefined

- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
Ref: BRICK_STORE-3104
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 优化navMenu样式

- bricks/brick-visualization/package.json
- bricks/flow-builder/package.json
- bricks/flow-builder/src/custom-processors/getFlowGraph.spec.ts
- bricks/flow-builder/src/custom-processors/getFlowGraph.ts
- bricks/flow-builder/src/custom-processors/getStepTreeData.spec.ts
- bricks/flow-builder/src/custom-processors/getStepTreeData.ts
- bricks/flow-builder/src/index.ts
- bricks/flow-builder/src/interfaces/flow.ts
- bricks/flow-builder/src/interfaces/index.ts
- bricks/flow-builder/src/step-tree/StepTree.module.css
- bricks/flow-builder/src/step-tree/StepTree.spec.tsx
- bricks/flow-builder/src/step-tree/StepTree.tsx
- bricks/flow-builder/src/step-tree/components/TreeList/TreeList.module.css
- bricks/flow-builder/src/step-tree/components/TreeList/TreeList.spec.tsx
- bricks/flow-builder/src/step-tree/components/TreeList/TreeList.tsx
- bricks/flow-builder/src/step-tree/constants.ts
- bricks/flow-builder/src/step-tree/index.spec.ts
- bricks/flow-builder/src/step-tree/index.tsx
- bricks/flow-builder/src/step-tree/interfaces.ts
- yarn.lock
Refs FLOW_BUILDER-410
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): step tree and processor

- bricks/presentational-bricks/src/brick-tag/index.tsx
> chore(BrickTag): build package again

- bricks/basic-bricks/package.json
- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.module.css
- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.spec.tsx
- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.tsx
- bricks/basic-bricks/src/app-bar/LaunchpadButton/LaunchpadButton.tsx
- bricks/basic-bricks/src/app-bar/LaunchpadService.spec.ts
- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
- bricks/basic-bricks/src/app-bar/LaunchpadSettingsContext.ts
- declarations/global.d.ts
- yarn.lock
> feat(): support launchpad in standalone apps

- bricks/next-builder/package.json
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- types/preview/index.d.ts
- yarn.lock
> Ella/form b UI lder 106

- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.spec.tsx
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
> feat(): 支持sidebarmenu列表超长时显示底部阴影

- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/frame-bricks/src/nav-menu/NavMenu.spec.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
> fix(): 修复NavMenu左侧不对齐的问题&重新实现支持divider特性的逻辑

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.spec.tsx
- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.tsx
- bricks/basic-bricks/src/app-bar/DesktopCell/DesktopCell.tsx
- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
- package.json
- yarn.lock
> fix(): lauchpad image url and skip problem

- bricks/basic-bricks/src/menu-bar/LogoBar/LogoBar.tsx
> fix(): 完善logobar的样式

- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
Ref: BRICK_STORE-3103
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix navmenu hover style

- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.spec.tsx
- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.tsx
- declarations/global.d.ts
> fix(): fix launchpad App image error

- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.tsx
- bricks/basic-bricks/src/app-bar/DesktopDir/DesktopDir.tsx
- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.spec.tsx
- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.tsx
- bricks/basic-bricks/src/app-bar/LaunchpadButton/LaunchpadButton.tsx
- bricks/basic-bricks/src/app-bar/LaunchpadService.spec.ts
- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
- bricks/basic-bricks/src/app-bar/utils/getImageUrl.spec.tsx
- bricks/basic-bricks/src/app-bar/utils/getImageUrl.tsx
> fix(): fix image url error in dir

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.spec.tsx
- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.spec.ts
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
Refs BLUEPRINT-492
请勾选以下两组选项其中之一：
或者：
>
>
> feat(sub-menu-filter): add menu.click event

- bricks/basic-bricks/src/list-container/ListContainer.tsx
- bricks/basic-bricks/src/list-container/index.tsx
Refs BLUEPRINT-476
请勾选以下两组选项其中之一：
或者：
>
>
> feat(list-container): add itemKey property

- bricks/flow-builder/src/custom-processors/getFlowGraph.spec.ts
- bricks/flow-builder/src/custom-processors/getFlowGraph.ts
- bricks/flow-builder/src/custom-processors/getStepTreeData.spec.ts
- bricks/flow-builder/src/custom-processors/getStepTreeData.ts
- bricks/flow-builder/src/interfaces/flow.ts
- bricks/flow-builder/src/step-tree/StepTree.spec.tsx
- bricks/flow-builder/src/step-tree/components/TreeList/TreeList.spec.tsx
> fix(): modify type

- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
Ref: NEXT_BUILDER-2076
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 隐藏组件库snippet tab

- bricks/calendar-bricks/src/agenda-calendar/AgendaCalendar.spec.tsx
- bricks/calendar-bricks/src/agenda-calendar/AgendaCalendar.tsx
- bricks/calendar-bricks/src/agenda-calendar/component/agendaCalendarContext.ts
- bricks/calendar-bricks/src/agenda-calendar/component/customDayPlugin.tsx
- bricks/calendar-bricks/src/agenda-calendar/index.shadow.less
- bricks/calendar-bricks/src/agenda-calendar/index.tsx
> fix():  日程日历构件补充自定义日视图 refs DESKTOP-267

- bricks/next-builder/src/data-providers/GetMatchRoute.spec.ts
- bricks/next-builder/src/data-providers/GetMatchRoute.ts
- bricks/next-builder/src/index.ts
> feat(): get match-route provider

- bricks/flow-builder/src/custom-processors/packVarTemplateData.spec.ts
- bricks/flow-builder/src/custom-processors/packVarTemplateData.ts
> fix(): 修复 json 类型数据时，替换错误问题

- bricks/calendar-bricks/src/agenda-calendar/component/customDayPlugin.tsx
- bricks/calendar-bricks/src/agenda-calendar/index.shadow.less
> fix():  日程日历构件补充自定义日视图的日视图样式修改 refs DESKTOP-267

- .size-limit.js
> chore(size-limit): limit size of chunks and workers

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.shadow.css
- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.spec.tsx
- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.tsx
- bricks/basic-bricks/src/app-bar-wrapper/index.spec.ts
- bricks/basic-bricks/src/app-bar-wrapper/index.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.module.css
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- bricks/basic-bricks/src/app-bar/AppBarTips/AppBarTips.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBarTips/AppBarTips.tsx
- bricks/basic-bricks/src/index.ts
- bricks/frame-bricks/deploy-default/package.conf.yaml
- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.tsx
> feat(): support app-bar show tips

- bricks/flow-builder/src/custom-processors/packVarTemplateData.spec.ts
- bricks/flow-builder/src/custom-processors/packVarTemplateData.ts
> fix(): add field

- bricks/flow-builder/src/custom-processors/getStepTreeData.spec.ts
- bricks/flow-builder/src/custom-processors/getStepTreeData.ts
- bricks/flow-builder/src/interfaces/flow.ts
> fix(): add step type

- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.spec.tsx
- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.tsx
- bricks/basic-bricks/src/app-bar-wrapper/index.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBarTips/AppBarTips.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
> fix(): fix app-bar-tips style

- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.tsx
> fix(): app-bar-wrapper style fix

- bricks/calendar-bricks/src/agenda-calendar/AgendaCalendar.spec.tsx
- bricks/calendar-bricks/src/agenda-calendar/AgendaCalendar.tsx
- bricks/calendar-bricks/src/agenda-calendar/index.shadow.less
- bricks/calendar-bricks/src/agenda-calendar/index.tsx
> fix():  日程日历构件补充展示一天的日程数量、自定义开始日期 refs DESKTOP-267

- bricks/flow-builder/src/multiple-files-form/MultipleFilesForm.tsx
- bricks/forms/src/upload-files-v2/UploadFilesV2.spec.tsx
- bricks/forms/src/upload-files-v2/UploadFilesV2.tsx
- bricks/forms/src/upload-files/UploadFiles.spec.tsx
- bricks/forms/src/upload-files/UploadFiles.tsx
- bricks/forms/src/upload-img/UploadImg.spec.tsx
- bricks/forms/src/upload-img/UploadImg.tsx
- bricks/presentational-bricks/src/avatar-upload/AvatarUpload.spec.tsx
- bricks/presentational-bricks/src/avatar-upload/AvatarUpload.tsx
Refs BRICK_STORE-3089
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): upload file with csrf token

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/app-bar/AppBarTips/AppBarTips.tsx
- package.json
- yarn.lock
> feat(): update appbar tip style

- bricks/flow-builder/src/custom-processors/getStepTreeData.spec.ts
- bricks/flow-builder/src/custom-processors/getStepTreeData.ts
Refs FLOW_BUILDER-434
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix children is branch type not show in some cases

- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.module.css
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
Ref: NEXT_BUILDER-2077
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support workbenchComponentSelect default brick icon

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
> feat(): support license tip

- bricks/basic-bricks/src/event-agent/index.ts
- bricks/basic-bricks/stories/chapters/event-agent.ts
- bricks/basic-bricks/stories/chapters/index.ts
> docs(): add docs about event-agent

- bricks/forms/stories/chapters/general-structs-form-item.ts
- bricks/forms/stories/images/forms.general-structs-form-item.svg
> feat(): update form brick icon

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
- bricks/forms/stories/chapters/cmdb-instance-select.ts
Closes 3116
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms): forms.select支持使用后端搜索

- bricks/forms/src/general-select/GeneralSelect.tsx
Refs 3116
请勾选以下两组选项其中之一：
或者：
>
>
> chore(forms): fix forms.select options update bug

- bricks/basic-bricks/src/app-bar/AppBarTips/AppBarTips.tsx
- bricks/basic-bricks/src/app-bar/DesktopCell/DesktopCell.tsx
- bricks/basic-bricks/src/app-bar/DesktopSlider/DesktopSlider.tsx
- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.spec.tsx
- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.tsx
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.tsx
> feat(): fix launchpad desktops bug and nav style

- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
Ref: NEXT_BUILDER-2082
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): fix appBar margin style

- bricks/flow-builder/src/custom-processors/getFlowGraph.spec.ts
- bricks/flow-builder/src/custom-processors/getFlowGraph.ts
- bricks/flow-builder/src/step-tree/components/TreeList/TreeList.tsx
- bricks/flow-builder/src/step-tree/index.spec.ts
- bricks/flow-builder/src/step-tree/index.tsx
- bricks/flow-builder/src/step-tree/interfaces.ts
> feat(): support context menu

- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- bricks/frame-bricks/src/side-bar/index.tsx
> fix(): liscense style bug fix

- bricks/forms/package.json
- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.tsx
- bricks/forms/src/index.ts
- bricks/forms/src/interfaces/dynamic-form-item-v2.ts
- bricks/forms/src/lazy-bricks.yaml
- yarn.lock
> feat(): dymaic item support editor type

- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.spec.tsx
- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- bricks/basic-bricks/src/app-bar/AppBarTips/AppBarTips.tsx
- bricks/frame-bricks/src/side-bar/SideBar.tsx
> fix(): fix sidebar margin bug & update style

- bricks/forms/src/general-select/GeneralSelect.tsx
Closes EVENT-1108
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复select无法搜索问题

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- bricks/basic-bricks/src/menu-bar/AppSubMenu/AppSubMenu.tsx
- bricks/basic-bricks/src/menu-bar/MenuBar/MenuBar.tsx
> fix(): appbar-tip兼容menu-bar场景的样式

- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
- bricks/basic-bricks/src/general-popup/index.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.module.css
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.spec.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
> feat(): update componentSelect style and fix popup bug

- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
> fix(): fix popup move bug

- bricks/calendar-bricks/package.json
- bricks/calendar-bricks/rollup.stories.js
- bricks/calendar-bricks/src/agenda-calendar/AgendaCalendar.spec.tsx
- bricks/calendar-bricks/src/agenda-calendar/AgendaCalendar.tsx
- bricks/calendar-bricks/src/agenda-calendar/component/customDayPlugin.tsx
- bricks/calendar-bricks/src/agenda-calendar/index.shadow.less
- bricks/calendar-bricks/src/agenda-calendar/index.tsx
- bricks/calendar-bricks/stories/chapters/agenda-calendar.ts
- bricks/calendar-bricks/stories/chapters/index.ts
- bricks/calendar-bricks/stories/images/calendar-bricks.agenda-calendar.svg
- bricks/calendar-bricks/stories/images/index.ts
- bricks/calendar-bricks/stories/index.ts
> fix():  日程日历构件补充文档 refs DESKTOP-267

- bricks/basic-bricks/src/page-title/index.tsx
- bricks/presentational-bricks/src/brick-button/index.tsx
> chore(): readme.md

- bricks/basic-bricks/src/app-bar-wrapper/AppBarWrapper.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBarTips/AppBarTips.tsx
> fix(): update appbar tip style

- bricks/forms/src/general-link/GeneralLink.spec.tsx
- bricks/forms/src/general-link/GeneralLink.tsx
- bricks/forms/src/general-link/__snapshots__/GeneralLink.spec.tsx.snap
- bricks/forms/src/general-link/index.spec.ts
- bricks/forms/src/general-link/index.tsx
- bricks/forms/src/general-link/style.module.css
- bricks/forms/src/index.ts
> feat(): formbuilder添加general-link组件 Refs:FORM_BUILDER-140

- bricks/basic-bricks/src/general-popup/style.shadow.css
refs DASHBOARD-208
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-popup): modify style

- bricks/next-builder/src/shared/workbench/WorkbenchTree.module.css
- bricks/next-builder/src/shared/workbench/WorkbenchTree.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/interfaces.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
> feat(): mark unreachable node

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/custom-processors/getWorkbenchDataTree.spec.ts
- bricks/next-builder/src/custom-processors/getWorkbenchDataTree.ts
- bricks/next-builder/src/index.ts
> feat(): new processor: getWorkbenchDataTree

- bricks/basic-bricks/src/sub-menu/SubMenu.tsx
refs BLUEPRINT-565
请勾选以下两组选项其中之一：
或者：
>
>
> fix(subMenu): fix topOperationConf undefined

- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
> fix(): no public root for component images

- bricks/time/stories/chapters/task-calendar.ts
Ref: BRICK_STORE-3159
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update Time-NB snippets

- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
- bricks/next-builder/src/data-providers/utils/replaceWidgetFunctions.spec.ts
- bricks/next-builder/src/data-providers/utils/replaceWidgetFunctions.ts
> feat(): building widgets with version

- bricks/developers/src/stories/chapters/atom-bricks/other/rich-editor.ts
Ref: BRICK_STORE-3156
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update rich-editor-NB snippet

- bricks/basic-bricks/src/general-popup/GeneralPopup.spec.tsx
- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
- bricks/basic-bricks/src/general-popup/style.shadow.css
> fix(): general-popup drag bug fix

- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.tsx
> fix(launchpad): standalone mode render error

- bricks/developers/src/brick-book/BrickBook/BrickBook.tsx
- bricks/developers/src/brick-book/BrickDemo/BrickDemo.spec.tsx
- bricks/developers/src/brick-book/BrickDemo/BrickDemo.tsx
- bricks/developers/src/components/BrickEditor/BrickEditor.tsx
- bricks/developers/src/components/BrickPreview/BrickPreview.spec.tsx
- bricks/developers/src/components/BrickPreview/BrickPreview.tsx
refs BRICK_STORE-3173
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): developers构件适应新的文档格式

- bricks/basic-bricks/stories/chapters/advanced-list-container.ts
- bricks/basic-bricks/stories/chapters/easy-view.ts
- bricks/basic-bricks/stories/chapters/event-agent.ts
- bricks/basic-bricks/stories/chapters/export-json-file.ts
- bricks/basic-bricks/stories/chapters/flex-layout.ts
- bricks/basic-bricks/stories/chapters/fold-brick-v2.ts
- bricks/basic-bricks/stories/chapters/general-anchor.ts
- bricks/basic-bricks/stories/chapters/general-button.ts
- bricks/basic-bricks/stories/chapters/general-card.ts
- bricks/basic-bricks/stories/chapters/general-custom-buttons.ts
- bricks/basic-bricks/stories/chapters/general-drawer.ts
- bricks/basic-bricks/stories/chapters/general-hotkeys.ts
- bricks/basic-bricks/stories/chapters/general-modal.ts
- bricks/basic-bricks/stories/chapters/general-notification.ts
- bricks/basic-bricks/stories/chapters/general-timer.ts
- bricks/basic-bricks/stories/chapters/general-title.ts
- bricks/basic-bricks/stories/chapters/grid-layout.ts
- bricks/basic-bricks/stories/chapters/index-card.ts
- bricks/basic-bricks/stories/chapters/list-container.ts
- bricks/basic-bricks/stories/chapters/menu-bar.ts
- bricks/basic-bricks/stories/chapters/micro-view.ts
- bricks/basic-bricks/stories/chapters/multiple-columns-card.ts
- bricks/basic-bricks/stories/chapters/page-title.ts
- bricks/basic-bricks/stories/chapters/popover-container.ts
- bricks/basic-bricks/stories/chapters/print-button.ts
- bricks/basic-bricks/stories/chapters/script-brick.ts
- bricks/basic-bricks/stories/chapters/sub-menu-filter.ts
- bricks/basic-bricks/stories/chapters/sub-menu.ts
> feat(): update basic-bricks-NB snippets

- bricks/developers/src/stories/chapters/business-bricks/agile/issue-card.ts
- bricks/developers/src/stories/chapters/business-bricks/agile/kanban-container.ts
Ref: BRICK_STORE-3140
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update agile-NB snippets

- bricks/developers/src/stories/chapters/atom-bricks/other/no-op.ts
- bricks/developers/src/stories/chapters/atom-bricks/other/push-history-record.ts
- bricks/developers/src/stories/chapters/atom-bricks/other/recent-visit.ts
Ref: BRICK_STORE-3144
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update visit-history-NB snippets

- bricks/utils/stories/chapters/broadcast-channel.ts
- bricks/utils/stories/chapters/general-clipboard.ts
> feat(); update utils-NB snippets

- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
> feat():workbenchTree树节点拖拽返回匹配节点（原仅返回根节点）

- bricks/forms/stories/chapters/cmdb-instance-select-panel.ts
- bricks/forms/stories/chapters/cmdb-instance-select.ts
- bricks/forms/stories/chapters/dynamic-form-item-v2.ts
- bricks/forms/stories/chapters/form-crontab-input.ts
- bricks/forms/stories/chapters/general-auto-complete.ts
- bricks/forms/stories/chapters/general-buttons.ts
- bricks/forms/stories/chapters/general-cascader.ts
- bricks/forms/stories/chapters/general-checkbox.ts
- bricks/forms/stories/chapters/general-date-picker.ts
- bricks/forms/stories/chapters/general-form.ts
- bricks/forms/stories/chapters/general-input-number.ts
- bricks/forms/stories/chapters/general-input.ts
- bricks/forms/stories/chapters/general-modal.ts
- bricks/forms/stories/chapters/general-radio.ts
- bricks/forms/stories/chapters/general-select.ts
- bricks/forms/stories/chapters/general-slide.ts
- bricks/forms/stories/chapters/general-structs-form-item.ts
- bricks/forms/stories/chapters/general-switch.ts
- bricks/forms/stories/chapters/general-textarea.ts
- bricks/forms/stories/chapters/general-time-picker.ts
- bricks/forms/stories/chapters/icon-select.ts
- bricks/forms/stories/chapters/inform-methods-form.ts
- bricks/forms/stories/chapters/input-with-unit.ts
- bricks/forms/stories/chapters/time-range-picker.ts
- bricks/forms/stories/chapters/tree-select.ts
- bricks/forms/stories/chapters/upload-files-v2.ts
- bricks/forms/stories/chapters/upload-files.ts
- bricks/forms/stories/chapters/upload-img.ts
- bricks/forms/stories/chapters/user-or-user-group-select.ts
> feat(): update forms-NB snippets

- bricks/next-builder/src/data-providers/LintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> fix(): refine lint storyboard

- bricks/next-builder/src/data-providers/LintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> fix(lint): do not warn multiple times for the same reason

- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> fix(): do not warn the same contexts

- bricks/next-builder/src/workbench-component-select/processor.ts
- bricks/presentational-bricks/stories/chapters/basic-icon.ts
> feat(): update snippets processor

- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/DataView/utils.spec.ts
- bricks/next-builder/src/builder-container/DataView/utils.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> feat(): support setting track and lazy in context

- bricks/next-builder/src/data-providers/CreateThemePage.spec.ts
- bricks/next-builder/src/data-providers/CreateThemePage.ts
> feat(): createThemePage only create snippet

- bricks/next-builder/src/workbench-component-select/processor.spec.ts
- bricks/next-builder/src/workbench-component-select/processor.ts
- bricks/presentational-bricks/stories/chapters/basic-icon.ts
> feat(): update snippet processor

- bricks/next-builder/src/data-providers/LintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> fix(): limit ctx warnings

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
> fix(): ObjectAttrStruct弹窗点击遮罩层不能关闭  Closes INSTANCE-3094

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
- bricks/forms/stories/chapters/cmdb-instance-select.ts
- bricks/forms/stories/chapters/general-select.ts
> feat(select): useBackend支持默认值搜索

- bricks/forms/src/general-select/GeneralSelect.tsx
> fix(select): 设置useBackend onValueChangeArgs为非必填

- bricks/calendar-bricks/src/agenda-calendar/AgendaCalendar.spec.tsx
- bricks/next-builder/src/data-providers/LintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> fix(): warn using TPL variables in templates

- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.module.css
> fix(): fix workbench icon style

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
> fix(): remove unreachable conditions

- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.tsx
> fix(): add new afterSubtitle slot for card-item Refs:ITSERVICE_NEXT-4901

- bricks/basic-bricks/src/popover-container/index.tsx
- bricks/flow-builder/src/schema-editor/components/schema-item/SchemaItem.module.css
> fix(): dark style

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
Closes MONITOR-4159
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 使用useBackend不需要启用前端搜索过滤

- bricks/basic-bricks/stories/chapters/advance-list-container.ts
- bricks/basic-bricks/stories/chapters/fold-brick.ts
- bricks/basic-bricks/stories/chapters/header-bar.ts
- bricks/basic-bricks/stories/chapters/micro-app.ts
- bricks/developers/src/stories/chapters/atom-bricks/form-input/brick-form.ts
- bricks/presentational-bricks/stories/chapters/agent-status.ts
- bricks/presentational-bricks/stories/chapters/brick-alert-level.ts
- bricks/presentational-bricks/stories/chapters/brick-alert-number.ts
- bricks/presentational-bricks/stories/chapters/brick-alert-status.ts
- bricks/presentational-bricks/stories/chapters/brick-alert-value.ts
> feat(): update bricks category

- bricks/basic-bricks/stories/chapters/event-agent.ts
- bricks/basic-bricks/stories/chapters/export-json-file.ts
- bricks/basic-bricks/stories/chapters/general-drawer.ts
- bricks/basic-bricks/stories/chapters/general-modal.ts
- bricks/basic-bricks/stories/chapters/general-notification.ts
- bricks/basic-bricks/stories/chapters/script-brick.ts
- bricks/basic-bricks/stories/images/basic-bricks.general-modal[basic].svg
- bricks/basic-bricks/stories/images/index.ts
- bricks/developers/src/stories/chapters/business-bricks/cmdb-instances/instance-list-modal-v2.ts
- bricks/developers/src/stories/chapters/business-bricks/cmdb-instances/instance-list-modal.ts
- bricks/developers/src/stories/chapters/cmdb-instances.ts
- bricks/developers/src/stories/chapters/general-auth.ts
- bricks/forms/stories/chapters/general-modal.ts
- bricks/utils/stories/chapters/broadcast-channel.ts
- bricks/utils/stories/chapters/general-clipboard.ts
> feat(): update snippet actions text & add general-modal snippet

- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
> fix(launchpad): fix visitor standalone img error

- bricks/basic-bricks/src/resizable-box/ResizableBox.shadow.css
- bricks/basic-bricks/src/resizable-box/ResizableBox.tsx
- bricks/basic-bricks/src/resizable-box/index.tsx
Ref: NEXT_BUILDER-2127
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix resizable-box resize bug

- bricks/calendar-bricks/src/agenda-calendar/index.tsx
- bricks/forms/src/time-range-picker/TimeRangePicker.module.css
- bricks/forms/src/time-range-picker/index.tsx
> fix(): forms.time-range-pick快速筛选的按钮样式背景颜色修改  refs BRICK_STORE-3133

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
> fix(brick-table): 修复table组件选中后，单元格背景透明的问题

- bricks/basic-bricks/src/resizable-box/index.tsx
> fix(): 修复resizable-box Bug,设置resizable属性默认值,兼容默认情况

- .size-limit.js
- bricks/next-builder/src/data-providers/LintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
- bricks/next-builder/src/storyboard-lint-result/StoryboardLintResult.tsx
and unknown event handlers and misuses of CTX
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): new lint errors such as unknown event actions

- bricks/basic-bricks/package.json
- bricks/basic-providers/package.json
- bricks/brick-visualization/package.json
- bricks/calendar-bricks/package.json
- bricks/developers/.gitignore
- bricks/developers/package.json
- bricks/flow-builder/package.json
- bricks/form-builder/package.json
- bricks/forms/package.json
- bricks/frame-bricks/package.json
- bricks/general-auth/package.json
- bricks/next-builder/package.json
- bricks/next-previewer/package.json
- bricks/presentational-bricks/package.json
- bricks/shared-editors/package.json
- bricks/time/package.json
- bricks/utils/package.json
- lerna.json
- nx.json
> chore(): use lerna with nx

- bricks/next-builder/src/data-providers/LintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
- bricks/next-builder/src/storyboard-lint-result/StoryboardLintResult.tsx
> fix(): allow expanding lint result

- bricks/forms/src/general-select/GeneralSelect.tsx
Closes MONITOR-4158
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 使用useBackend时filterOption应为false

- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
> fix(): 修复下拉按钮跟随滚动条滑动问题 refs BRICK_STORE-3125

- bricks/flow-builder/src/custom-processors/packVarTemplateData.ts
- bricks/flow-builder/src/custom-processors/replacePlaceholder.spec.ts
- bricks/flow-builder/src/custom-processors/replacePlaceholder.ts
- bricks/flow-builder/src/index.ts
> fix():refine processor

- bricks/basic-bricks/src/app-bar/LaunchpadService.spec.ts
- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
refs NEXT_BUILDER-2193
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复standalone模式下, launchpad最近访问只有一个的问题

- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
Ref: NEXT_BUILDER-2226
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix VB workbench search bricks bug

- bricks/basic-bricks/jest.config.js
- bricks/basic-providers/jest.config.js
- bricks/brick-visualization/jest.config.js
- bricks/calendar-bricks/jest.config.js
- bricks/developers/jest.config.js
- bricks/flow-builder/jest.config.js
- bricks/form-builder/jest.config.js
- bricks/forms/jest.config.js
- bricks/frame-bricks/jest.config.js
- bricks/general-auth/jest.config.js
- bricks/next-builder/jest.config.js
- bricks/next-previewer/jest.config.js
- bricks/presentational-bricks/jest.config.js
- bricks/shared-editors/jest.config.js
- bricks/time/jest.config.js
- bricks/utils/jest.config.js
- package.json
> chore(): refine test scripts

- bricks/forms/src/general-select/GeneralSelect.tsx
> fix(): select去掉契约限制 refs CD-3119

- bricks/next-builder/src/workbench-data-tree/WorkbenchDataTree.tsx
> fix(): fix workbench-data-tree search bug

- bricks/presentational-bricks/src/general-tooltip/GeneralTooltip.module.css
> fix(): 改变toolTip的icon的间距

- bricks/basic-bricks/src/home-redirect/index.spec.ts
- bricks/basic-bricks/src/home-redirect/index.ts
refs NEXT_BUILDER-2193
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复standalone模式下, home-redirect不生效的问题

- bricks/next-builder/src/data-providers/LintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> feat(): lint storyboard add INSTALLED_APPS

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
Ref: NEXT_BUILDER-2199
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support VB previewer toggle theme

- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
> fix(): launchpad sitemap click and icon error

- bricks/developers/src/illustration-card/IllustrationCard.tsx
> fix(): fix illustrations Style

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.module.css
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
refs BLUEPRINT-600
请勾选以下两组选项其中之一：
或者：
>
>
> feat(SubMenuFilter): add suffixBrickTriggerByHover property

- bricks/basic-bricks/src/grid-layout/index.spec.ts
- bricks/basic-bricks/src/grid-layout/index.ts
> feat(): support setting gap for grid-layout

- bricks/next-builder/src/preview-container/PreviewContainer.module.css
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.module.css
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
Ref: NEXT_BUILDER-2205
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update workbench-select style

- bricks/basic-bricks/src/general-text/GeneralText.tsx
- bricks/basic-bricks/src/general-text/index.tsx
- bricks/basic-bricks/stories/chapters/general-text.ts
- bricks/basic-bricks/stories/chapters/index.ts
- bricks/basic-bricks/stories/images/basic-bricks.general-text.svg
- bricks/basic-bricks/stories/images/basic-bricks.general-text[auxiliaryText].svg
- bricks/basic-bricks/stories/images/basic-bricks.general-text[bannerTitle].svg
- bricks/basic-bricks/stories/images/basic-bricks.general-text[categoryTitle].svg
- bricks/basic-bricks/stories/images/basic-bricks.general-text[containerCardTitle].svg
- bricks/basic-bricks/stories/images/basic-bricks.general-text[main].svg
- bricks/basic-bricks/stories/images/index.ts
> docs(): 补充general-text文档和snippet refs BRICK_STORE-3129

- bricks/next-builder/src/data-providers/getStoriesJson.ts
Ref: NEXT_BUILDER-2231
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support VB show select brick icon

- bricks/basic-bricks/src/grid-layout/gridLayout.module.css
- bricks/basic-bricks/src/grid-layout/index.spec.ts
- bricks/basic-bricks/src/grid-layout/index.ts
> feat():grid布局支持开启网格线以及设置网格线颜色，refs:FORM_BUILDER-154

- bricks/presentational-bricks/src/collapse-info-list/CollapseInfoList.module.css
- bricks/presentational-bricks/src/collapse-info-list/CollapseInfoList.spec.tsx
- bricks/presentational-bricks/src/collapse-info-list/CollapseInfoList.tsx
- bricks/presentational-bricks/src/collapse-info-list/index.spec.ts
- bricks/presentational-bricks/src/collapse-info-list/index.tsx
- bricks/presentational-bricks/src/index.ts
- bricks/presentational-bricks/stories/chapters/collapse-info-list.ts
- bricks/presentational-bricks/stories/images/index.ts
- bricks/presentational-bricks/stories/images/presentational-bricks.collapse-info-list.svg
refs BLUEPRINT-634
请勾选以下两组选项其中之一：
或者：
>
>
> feat(presentational-bricks): add CollapseInfoList

- bricks/presentational-bricks/stories/chapters/collapse-info-list.ts
> chore(CollapseInfoList): update doc

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> feat(): support VB preview route back and forward

- bricks/presentational-bricks/src/card-item/CardItem.spec.tsx
- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.spec.ts
- bricks/presentational-bricks/src/card-item/index.tsx
> feat(presentational-bricks): cartItem构件跳转支持a标签行为 Refs:EASY_AGILE-873

- bricks/basic-bricks/src/general-popup/style.shadow.css
- bricks/next-builder/src/shared/workbench/WorkbenchTree.module.css
- bricks/next-builder/src/workbench-action-list/WorkbenchActionList.module.css
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.module.css
- bricks/next-builder/src/workbench-sidebar/WorkbenchSidebar.shadow.css
- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.module.css
> feat(): update VB style

- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.tsx
> fix(presentational-bricks): 修复cartItem构件无法抛出点击事件问题 Refs:EASY_AGILE-873

- bricks/flow-builder/src/variable-item/VariableItem.spec.tsx
- bricks/flow-builder/src/variable-item/VariableItem.tsx
- bricks/flow-builder/src/variable-item/index.tsx
- bricks/flow-builder/src/variable-item/variable-display/VariableDisplay.spec.tsx
- bricks/flow-builder/src/variable-list/VariableList.module.css
- bricks/flow-builder/src/variable-list/VariableList.tsx
- bricks/flow-builder/src/variable-list/index.tsx
> feat(): support expand

- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.module.css
- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.tsx
> feat(): update workbench tabs style

- bricks/flow-builder/src/variable-item/VariableItem.tsx
- bricks/flow-builder/src/variable-item/constants.ts
- bricks/flow-builder/src/variable-item/index.tsx
- bricks/flow-builder/src/variable-item/variable-display/VariableDisplay.module.css
- bricks/flow-builder/src/variable-item/variable-display/VariableDisplay.tsx
- bricks/flow-builder/src/variable-list/VariableList.tsx
- bricks/flow-builder/src/variable-list/index.tsx
> feat(): support ellipsis

- bricks/presentational-bricks/src/card-item/CardItem.tsx
> fix():add title for card-item descriptionList Refs:ITSERVICE_NEXT-5120

- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
> fix(general-popup): fix blur when open in certain width or height view

- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.spec.tsx
- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.tsx
- bricks/next-builder/src/workbench-tabs/index.tsx
> feat(workbench-tabs): closeDisabled

- bricks/next-builder/src/preview-container/PreviewContainer.module.css
> fix(): fix preview container style

- bricks/basic-bricks/src/app-bar/AppSetting/AppSetting.spec.tsx
- bricks/basic-bricks/src/app-bar/AppSetting/AppSetting.tsx
fixes LAUNCHPAD-124
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): standalone模式下,实际上发行版肯定会带cmdb-account-setting,暂时忽略app安装的判断

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
Closes MONITOR-4264
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): value为空不应该调接口 && 接口返回空不调用transform

- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.module.css
> fix(): fix workbench style

- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
- bricks/next-builder/src/workbench-component-select/index.tsx
> feat(): WorkbenchCompoentnSelect support getSnippetByBrick method

- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.tsx
> feat(workbench-tabs): set closeDisabled by each tab

- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/index.tsx
close DESIGNER_ROUTINE-597
请勾选以下两组选项其中之一：
或者：
>
>
> feat(sideBar): change position sticky to fixed

- bricks/flow-builder/src/custom-processors/packVarTemplateData.ts
> fix(): fix null value

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.module.css
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
> feat(): sub-menu-filter support `to`

- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
> fix(): lazy image loading

- bricks/flow-builder/src/custom-processors/getStepTreeData.spec.ts
- bricks/flow-builder/src/custom-processors/getStepTreeData.ts
> fix(): refactor logic

- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
close OFFICIAL_WEBSITE-49
请勾选以下两组选项其中之一：
或者：
>
>
> fix(GeneralCustomButtons): change more icon

- bricks/forms/stories/chapters/general-form.ts
- bricks/presentational-bricks/stories/chapters/brick-table.ts
> feat(): update snippet

- bricks/forms/src/crontab-input/CrontabInput.spec.tsx
- bricks/forms/src/crontab-input/CrontabInput.tsx
- bricks/forms/src/crontab-input/index.tsx
> fix(): 增加可禁用input框选项 refs ARTIFACT-466

- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.tsx
- bricks/basic-bricks/src/app-bar/LaunchpadButton/LaunchpadButton.tsx
- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
> feat(): pre fetch launchpad info in standalone app

- bricks/frame-bricks/src/nav-menu/NavMenu.spec.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/side-bar/SidebarMenu.tsx
- bricks/frame-bricks/src/side-bar/mockData.ts
refs INSTANCE-3232
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): items为空时不渲染group或者submenu

- bricks/basic-bricks/stories/chapters/multiple-columns-card.ts
> docs(): update brick story

- bricks/basic-bricks/deploy-default/package.conf.yaml
> chore(basic-bricks): update brick-next

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/utils/getGraphTreeByBuilderData.spec.ts
- bricks/next-builder/src/utils/getGraphTreeByBuilderData.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.ts
- types/preview/index.d.ts
> fix(): use displayName instead of alias

- bricks/forms/src/general-structs-form-item/GeneralStructsFormItem.tsx
- bricks/forms/src/general-structs-form-item/index.tsx
> fix(): 可编辑表格组件支持禁用行操作 Refs:EASY_AGILE-889

- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.module.css
- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.tsx
Closes SERVICE_OBSERVE-1939
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复展示label时按钮位置不正确

- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
- bricks/basic-bricks/src/general-custom-buttons/index.module.css
> fix(): basic-bricks.general-custom-buttons样式调整  refs ORCHESTRATION-218

- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
- bricks/basic-bricks/src/general-popup/index.tsx
close DESIGNER_ROUTINE-598
请勾选以下两组选项其中之一：
或者：
>
>
> feat(GeneralPopup): support openDirection

- bricks/basic-bricks/stories/chapters/general-popup.ts
- bricks/basic-bricks/stories/chapters/index.ts
- bricks/basic-bricks/stories/images/basic-bricks.general-popup.svg
- bricks/basic-bricks/stories/images/index.ts
> chore(popup): add doc

- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
close BRICK_STORE-3195
请勾选以下两组选项其中之一：
或者：
>
>
> fix(GeneralSelect): emptyOption repeat

- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
- bricks/basic-bricks/src/general-popup/index.tsx
- bricks/basic-bricks/src/general-popup/style.shadow.css
- bricks/basic-bricks/stories/chapters/general-popup.ts
ref DESIGNER_ROUTINE-598
请勾选以下两组选项其中之一：
或者：
>
>
> fix(popup): add wrapper style

- bricks/next-builder/src/workbench-component-select/processor.ts
- bricks/presentational-bricks/stories/chapters/brick-table.ts
> fix(): update workbench snippets processor

- bricks/brick-visualization/package.json
- bricks/brick-visualization/src/visual-property-form/index.tsx
- yarn.lock
> feat(visualPropertyForm): add childMountPointList

- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
> fix(): use snippet transform useChildren

- bricks/basic-bricks/src/sub-menu/SubMenu.tsx
- bricks/basic-bricks/src/sub-menu/index.module.css
- bricks/basic-bricks/src/sub-menu/index.tsx
> feat(layout): 添加sub-menu作为三级菜单时的样式

- bricks/next-builder/src/workbench-sidebar/WorkbenchSidebar.tsx
> feat(workbenchsideBar): add titleToolbar

- bricks/presentational-bricks/src/rank-table/RankTable.module.css
- bricks/presentational-bricks/src/rank-table/index.spec.ts
- bricks/presentational-bricks/src/rank-table/index.tsx
refs BRICK_STORE-3198
请勾选以下两组选项其中之一：
或者：
>
>
- [] 给问题修复添加了单元测试。
> fix(rank-table): sort 不生效

- bricks/forms/src/general-link/GeneralLink.spec.tsx
- bricks/forms/src/general-link/GeneralLink.tsx
- bricks/forms/src/general-link/index.tsx
- bricks/forms/src/time-range-picker/index.tsx
> fix():修复时间段选择器开始结束时间为空时，校验两者相等，修复link控件文本颜色控制

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
Closes MONITOR-4473
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): select支持value.option.data.change事件

- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.tsx
> chore(BrickTree): support tree.expand event

- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.module.css
> fix(): fix vb workbench tabs style

- bricks/flow-builder/src/custom-processors/getFlowGraph.spec.ts
- bricks/flow-builder/src/custom-processors/getFlowGraph.ts
> fix(): fix no start node

- bricks/basic-bricks/src/app-bar/Launchpad/Launchpad.tsx
> fix(): launchpad first render still loading

- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
> fix(): fix brick tree not query route brick

- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> fix(): add brick after move, sort was error

- bricks/form-builder/src/business-rule/BusinessRule.module.css
- bricks/form-builder/src/business-rule/BusinessRule.spec.tsx
- bricks/form-builder/src/business-rule/BusinessRule.tsx
- bricks/form-builder/src/business-rule/index.spec.ts
- bricks/form-builder/src/business-rule/index.tsx
- bricks/form-builder/src/conditional-format/ConditionalFormat.module.css
- bricks/form-builder/src/conditional-format/ConditionalFormat.spec.tsx
- bricks/form-builder/src/conditional-format/ConditionalFormat.tsx
- bricks/form-builder/src/conditional-format/index.spec.ts
- bricks/form-builder/src/conditional-format/index.tsx
- bricks/form-builder/src/index.ts
> feat(): add conditional component Refs:FORM_BUILDER-179

- bricks/form-builder/src/business-rule/BusinessRule.spec.tsx
- bricks/form-builder/src/business-rule/BusinessRule.tsx
- bricks/form-builder/src/business-rule/index.tsx
> feat(): business rule suport list Refs:FORM_BUILDER-179

- bricks/form-builder/src/business-rule/BusinessRule.spec.tsx
- bricks/form-builder/src/business-rule/BusinessRule.tsx
- bricks/form-builder/src/business-rule/index.tsx
> fix(): 修复每列数据显示隐藏异常问题 Refs:FORM_BUILDER-179

- bricks/form-builder/src/business-rule/BusinessRule.spec.tsx
- bricks/form-builder/src/business-rule/BusinessRule.tsx
> fix(): 修复每列数据变动不更新问题 Refs:FORM_BUILDER-179

- bricks/forms/src/inform-methods-form/index.spec.ts
- bricks/forms/src/inform-methods-form/index.tsx
refs CD-3466
请勾选以下两组选项其中之一：
或者：
>
>
> fix(InformMethodsForm):  fix notRender

- bricks/forms/src/user-or-user-group-select/index.spec.ts
- bricks/forms/src/user-or-user-group-select/index.tsx
refs CD-3465
请勾选以下两组选项其中之一：
或者：
>
>
> fix(UserOrUserGroupSelect): fix notRender

- bricks/form-builder/src/conditional-format/ConditionalFormat.spec.tsx
- bricks/form-builder/src/conditional-format/ConditionalFormat.tsx
> fix(): 修复条件为空初始化显示错误 Refs:FORM_BUILDER-179

- bricks/basic-bricks/stories/chapters/general-drawer.ts
> docs(): update general-drawer snippet style

- bricks/basic-bricks/src/general-button/index.tsx
- bricks/basic-bricks/src/general-custom-buttons/index.tsx
- bricks/basic-bricks/src/popover-container/index.tsx
- bricks/forms/src/general-buttons/index.tsx
- bricks/forms/src/general-checkbox/index.tsx
- bricks/forms/src/general-form/index.tsx
- bricks/forms/src/general-link/index.tsx
- bricks/forms/src/general-modal/index.tsx
- bricks/forms/src/general-radio/index.tsx
- bricks/forms/src/general-select/index.tsx
- bricks/forms/src/general-switch/index.tsx
- bricks/presentational-bricks/src/brick-alert/index.tsx
- bricks/presentational-bricks/src/brick-descriptions/index.tsx
- bricks/presentational-bricks/src/brick-general-search/index.tsx
- bricks/presentational-bricks/src/brick-user/index.tsx
- bricks/presentational-bricks/src/modal-confirm/index.tsx
- bricks/presentational-bricks/src/rank-table/index.tsx
> feat(): add enums in bricks

- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.tsx
> fix(): fix dynamic-form-item-v2 bug

- bricks/form-builder/src/business-rule/BusinessRule.module.css
- bricks/form-builder/src/business-rule/BusinessRule.spec.tsx
- bricks/form-builder/src/business-rule/BusinessRule.tsx
- bricks/form-builder/src/conditional-format/ConditionalFormat.module.css
- bricks/form-builder/src/conditional-format/ConditionalFormat.spec.tsx
- bricks/form-builder/src/conditional-format/ConditionalFormat.tsx
> fix(): 规则列表兼容各种数据呈现 Refs:FORM_BUILDER-179

- bricks/brick-visualization/package.json
- yarn.lock
> feat(): update dependencies

- bricks/basic-bricks/src/general-custom-buttons/index.module.css
> fix(): general-custom-buttons下拉框的hover样式去掉 refs DEVOPS_MANAGEMENT-752

- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
> fix(): forms.general-select补充无边框样式。 refs DEVOPS_MANAGEMENT-774

- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
Ref: NEXT_BUILDER-2314
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support doLintStoryboard to scan old providers-of-xxx

- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
> fix(build-project-of-templates): replace widget keywords in state

- bricks/presentational-bricks/src/brick-result/components/IllustrationWrapper.tsx
- bricks/presentational-bricks/src/brick-result/index.tsx
> feat(): update code

- bricks/basic-bricks/src/menu-bar/AppMenu/AppMenu.module.css
- bricks/basic-bricks/src/menu-bar/MenuBar/MenuBar.module.css
> fix(): support setting linear-gradient via css variables

- bricks/basic-bricks/src/general-button/GeneralButton.tsx
- bricks/basic-bricks/src/general-button/index.tsx
close BRICK_STORE-3204
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 给button添加xs的尺寸

- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.tsx
- bricks/forms/src/dynamic-form-item-v2/autoCompleteItem.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/autoCompleteItem.tsx
- bricks/forms/src/interfaces/dynamic-form-item-v2.ts
> feat(): support dynamic-form-item-v2 autoComplete item

- bricks/basic-bricks/src/flex-layout/index.spec.ts
> chore(): update tag

- bricks/basic-bricks/src/flex-layout/index.spec.ts
> fix(): update basic-bricks version tag

- bricks/forms/src/upload-img/UploadImg.spec.tsx
- bricks/forms/src/upload-img/UploadImg.tsx
- bricks/forms/src/upload-img/index.tsx
> feat(): 图片上传构件forms.upload-img支持多张图片进行上传 refs EASY_HUB-430

- bricks/forms/src/upload-img/UploadImg.tsx
> fix(): 图片上传构件forms.upload-img支持多张图片进行上传 refs EASY_HUB-430

- bricks/basic-bricks/src/app-bar/AppSetting/AppSetting.spec.tsx
- bricks/basic-bricks/src/app-bar/AppSetting/AppSetting.tsx
- bricks/developers/src/components/BrickPreview/BrickPreview.spec.tsx
- bricks/next-previewer/src/preview-helper/previewStart.ts
- package.json
- yarn.lock
> fix(): 修复app-setting名称显示问题 refs USER-4

- bricks/frame-bricks/src/nav-menu/NavMenu.spec.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/nav-menu/index.tsx
> feat(): support nav-menu ShowTooltip

- bricks/developers/deploy-default/package.conf.yaml
- bricks/developers/src/brick-book/BrickBook/BrickBook.spec.tsx
- bricks/developers/src/brick-book/BrickBook/BrickBook.tsx
- bricks/developers/src/brick-book/BrickDemo/BrickDemo.module.css
- bricks/developers/src/brick-book/BrickDemo/BrickDemo.tsx
- bricks/developers/src/components/BrickEditor/BrickEditor.tsx
- bricks/developers/src/components/BrickPreview/BrickPreview.tsx
- bricks/developers/src/components/NextBrickDemo/NextBrickDemo.module.css
- bricks/developers/src/components/NextBrickDemo/NextBrickDemo.tsx
- bricks/developers/src/components/NextBrickPreview/NextBrickPreview.module.css
- bricks/developers/src/components/NextBrickPreview/NextBrickPreview.tsx
- bricks/developers/src/i18n/constants.ts
- bricks/developers/src/i18n/locales/en.ts
- bricks/developers/src/i18n/locales/zh.ts
- bricks/developers/src/interfaces/brick-document.ts
- bricks/developers/src/share/processor.spec.ts
- bricks/developers/src/share/processor.ts
Refs NEXT_BUILDER-2455
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): developer support iframe preview in standalone

- bricks/forms/package.json
- yarn.lock
> chore(forms): update next-libs/forms dependency

- bricks/developers/src/components/NextBrickDemo/NextBrickDemo.module.css
- bricks/developers/src/components/NextBrickDemo/NextBrickDemo.tsx
- bricks/developers/src/components/NextBrickPreview/NextBrickPreview.tsx
> fix(): refactor preview

- bricks/basic-bricks/src/app-bar/AppBarBreadcrumb/AppBarBreadcrumb.module.css
- bricks/presentational-bricks/src/general-list/GeneralList.shadow.less
close BRICK_STORE-3202
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 更改general-list间距及面包屑高度

- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
> fix(): general-select增加maxTagCount属性 refs BRICK_STORE-3223

- bricks/presentational-bricks/src/brick-general-search/index.module.css
- bricks/presentational-bricks/src/brick-input/BrickInput.module.css
close BRICK_STORE-3202
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改searchInput的样式

- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.tsx
- bricks/forms/src/dynamic-form-item-v2/autoCompleteItem.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/autoCompleteItem.tsx
- bricks/forms/src/interfaces/dynamic-form-item-v2.ts
> feat(): support dynamic-form-item autoComplete append mode

- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
Refs INSTANCE-3480
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 下拉框构件添加默认高亮第一个选项的配置

- bricks/brick-visualization/package.json
- bricks/brick-visualization/src/visual-property-form/index.tsx
- yarn.lock
> feat(): brick properties support both change

- bricks/basic-bricks/src/app-bar/AppBarBreadcrumb/AppBarBreadcrumb.module.css
- bricks/basic-bricks/src/micro-app/MicroApp.shadow.css
close BRICK_STORE-3202
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改面包屑及micro-app样式

- bricks/basic-bricks/package.json
- yarn.lock
> fix(): 手动更改custom-antd-styles依赖

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
Closes EVENT-1229
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 值为null不应该拉取接口 && state更新异常

- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.spec.tsx
- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.tsx
- bricks/flow-builder/src/schema-editor/components/ref-required-item/RefRequiredItem.tsx
- bricks/flow-builder/src/schema-editor/components/schema-item/SchemaItem.tsx
- bricks/flow-builder/src/schema-editor/interfaces.ts
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.spec.ts
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.ts
Refs NEXT_BUILDER-2516
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): distinguish required and default field hierarchies

- bricks/forms/src/cmdb-cascader/CmdbCascader.spec.tsx
- bricks/forms/src/cmdb-cascader/CmdbCascader.tsx
- bricks/forms/src/cmdb-cascader/index.spec.ts
- bricks/forms/src/cmdb-cascader/index.tsx
> feat(): cmdb-cascader支持onchangeV2，Refs: FORM_BUILDER-203

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
Closes EVENT-1230
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): optionDataChangeEvent 支持多选

- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
> fix(): fix launchpad fetch everytime

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
Closes EVENT-1239
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): useBackend支持配置不同请求状态的插画

- bricks/forms/src/general-auto-complete/GeneralAutoComplete.spec.tsx
- bricks/forms/src/general-auto-complete/GeneralAutoComplete.tsx
- bricks/forms/src/general-auto-complete/index.tsx
> feat(): support general-auto-complete append mode

- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
close BRICK_STORE-3229
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改sidebar的border-radius

- bricks/basic-bricks/src/utils.spec.ts
- bricks/basic-bricks/src/utils.ts
Refs NEXT_BUILDER-2587
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): compatible with no route data

- bricks/presentational-bricks/src/general-pagination/index.tsx
> feat(): support general-pagination shouldNotify

- bricks/forms/src/cmdb-cascader/CmdbCascader.spec.tsx
- bricks/forms/src/cmdb-cascader/CmdbCascader.tsx
- bricks/forms/src/cmdb-cascader/index.spec.ts
- bricks/forms/src/cmdb-cascader/index.tsx
Refs ITSERVICE_NEXT-5582
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复cmdb cascader无法获取value值

- bricks/developers/deploy-default/package.conf.yaml
- bricks/developers/src/brick-debug/BrickDebug.spec.tsx
- bricks/developers/src/brick-debug/BrickDebug.tsx
- bricks/developers/src/components/NextBrickDemo/NextBrickDemo.module.css
- bricks/developers/src/components/NextBrickDemo/NextBrickDemo.tsx
- bricks/developers/src/components/NextBrickPreview/NextBrickPreview.module.css
- bricks/developers/src/components/NextBrickPreview/NextBrickPreview.tsx
- bricks/developers/src/i18n/constants.ts
- bricks/developers/src/i18n/locales/en.ts
- bricks/developers/src/i18n/locales/zh.ts
- bricks/developers/src/providers-of-brick-story/processor.spec.ts
- bricks/developers/src/share/processor.spec.ts
- bricks/developers/src/share/processor.ts
Refs NEXT_BUILDER-2514
Refs NEXT_BUILDER-2524
Refs NEXT_BUILDER-2531
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refactor brick preview

- bricks/presentational-bricks/package.json
- yarn.lock
请勾选以下两组选项其中之一：
- [] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。
或者：
>
>
> fix(): update @next-libs/hooks

- bricks/flow-builder/package.json
- bricks/flow-builder/src/custom-processors/changeCase.spec.ts
- bricks/flow-builder/src/custom-processors/changeCase.ts
- bricks/flow-builder/src/index.ts
Refs NEXT_BUILDER-2522
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add processor

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
> fix(): 修复下拉多选模式和cmdb实例选择默认为空时出现空tags,refs: ITSERVICE_NEXT-5594

- bricks/presentational-bricks/src/brick-value-mapping/BrickValueMapping.spec.tsx
- bricks/presentational-bricks/src/brick-value-mapping/BrickValueMapping.tsx
- bricks/presentational-bricks/src/brick-value-mapping/index.tsx
- bricks/presentational-bricks/src/brick-value-mapping/style.module.css
> feat(): brick-value-mapping增加文案超出隐藏属性 Closes INSTANCE-3751

- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.tsx
- bricks/forms/src/dynamic-form-item-v2/index.tsx
> feat(): support dynamicFormStyle

- bricks/forms/src/general-select/index.tsx
ref CD-3814
请勾选以下两组选项其中之一：
或者：
>
>
> feat(select): select support validateTrigger

- bricks/flow-builder/src/schema-editor/SchemaEditor.tsx
- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.spec.tsx
- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.tsx
- bricks/flow-builder/src/schema-editor/components/schema-item/SchemaItem.tsx
- bricks/flow-builder/src/schema-editor/index.tsx
Refs FLOW_BUILDER-689
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): hidden root node required

- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/brick-user/BrickUser.spec.tsx
- bricks/presentational-bricks/src/brick-user/BrickUser.tsx
- bricks/presentational-bricks/src/brick-user/index.tsx
- yarn.lock
Closes BRICK_STORE-4159
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): brick-user支持显示 `showKey`

- .gitignore
- .size-limit.js
- bricks/forms/src/cmdb-cascader/CmdbCascader.tsx
- bricks/forms/src/cmdb-cascader/index.spec.ts
- bricks/forms/src/cmdb-cascader/index.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/cmdb-instance-select/index.spec.ts
- bricks/forms/src/cmdb-instance-select/index.tsx
- bricks/forms/src/general-cascader/GeneralCascader.tsx
- bricks/forms/src/general-cascader/index.spec.ts
- bricks/forms/src/general-cascader/index.tsx
- bricks/forms/src/general-checkbox/GeneralCheckbox.tsx
- bricks/forms/src/general-checkbox/index.spec.ts
- bricks/forms/src/general-checkbox/index.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.spec.ts
- bricks/forms/src/general-radio/index.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.spec.ts
- bricks/forms/src/general-select/index.tsx
> Ella/form b UI lder 205

- bricks/forms/src/general-radio/GeneralRadio.spec.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.module.css
- bricks/forms/src/general-radio/index.tsx
- bricks/forms/stories/chapters/general-radio.ts
- bricks/presentational-bricks/stories/chapters/brick-table.ts
refs BRICK_STORE-3266
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): BRICK_STORE-3266 forms.general-radio构件增加带辅助图标的功能。

- bricks/forms/stories/chapters/general-radio.ts
refs BRICK_STORE-3266
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): BRICK_STORE-3266 forms.general-radio构件增加带辅助图标的功能,补充文档。

- bricks/forms/src/cmdb-cascader/CmdbCascader.tsx
> fix(): 修复无默认值情况不触发options获取

- bricks/forms/src/time-range-picker/TimeRangePicker.tsx
refs BRICK_STORE-3288
请勾选以下两组选项其中之一：
或者：
>
>
> fix(time-range-picker): 当类型为dateTime时，点击「确认」的时候触发多次onchange事件

- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
- package.json
- yarn.lock
refs BRICK_STORE-3251
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): BRICK_STORE-3251 【表格组件】表头筛选图标颜色需替换为 #8c8c8c ，位置应紧跟表头文字，间隔是8px

- bricks/forms/src/input-with-unit/InputWithUnit.spec.tsx
- bricks/forms/src/input-with-unit/InputWithUnit.tsx
- bricks/forms/src/input-with-unit/index.tsx
Refs BRICK_STORE-3291
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复value unit不生效以及跟popover组合使用抛错的问题

- bricks/forms/src/general-select/GeneralSelect.module.css
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
> fix(): select选项支持换行

- bricks/flow-builder/src/custom-processors/getFlowGraph.spec.ts
- bricks/flow-builder/src/custom-processors/getFlowGraph.ts
- bricks/flow-builder/src/custom-processors/getStepTreeData.spec.ts
- bricks/flow-builder/src/custom-processors/getStepTreeData.ts
Refs EASYCORE-1012
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix choice node add children error

- bricks/forms/src/general-form/index.tsx
> fix(): 修复form的setInitvalue设置日期时间无法生效,refs: ITSERVICE_NEXT-5576

- bricks/forms/src/general-select/GeneralSelect.module.css
- bricks/forms/src/general-select/GeneralSelect.tsx
> fix(): 增加optionsWrap属性

- bricks/forms/src/general-select/GeneralSelect.module.css
- bricks/forms/src/general-select/GeneralSelect.tsx
> fix(): fix optionsWrap对其他select框的错误影响

- bricks/flow-builder/src/step-tree/CheckManagement.spec.ts
- bricks/flow-builder/src/step-tree/CheckManagement.ts
- bricks/flow-builder/src/step-tree/StepTree.module.css
- bricks/flow-builder/src/step-tree/StepTree.tsx
- bricks/flow-builder/src/step-tree/components/TreeList/TreeList.tsx
- bricks/flow-builder/src/step-tree/index.tsx
- bricks/flow-builder/src/step-tree/interfaces.ts
Refs FLOW_BUILDER-715
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support multiple select

- bricks/general-auth/src/general-signup/GeneralSignup.spec.tsx
- bricks/general-auth/src/general-signup/GeneralSignup.tsx
> fix(): 增加注册页面的同意条款 refs SSO-68

- bricks/flow-builder/src/step-tree/StepTree.module.css
- bricks/flow-builder/src/step-tree/StepTree.tsx
- bricks/flow-builder/src/step-tree/index.spec.ts
- bricks/flow-builder/src/step-tree/index.tsx
Refs FLOW_BUILDER-687
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support usebrick

- bricks/general-auth/src/general-signup/GeneralSignup.tsx
> fix(): 调整enable-nickname-config开关写法 refs SSO-68

- bricks/brick-visualization/src/index.ts
- bricks/brick-visualization/src/visual-form-rules-setting/VisualFormRulesSetting.spec.tsx
- bricks/brick-visualization/src/visual-form-rules-setting/VisualFormRulesSetting.tsx
- bricks/brick-visualization/src/visual-form-rules-setting/components/ListEditor/ListEditor.module.css
- bricks/brick-visualization/src/visual-form-rules-setting/components/ListEditor/ListEditor.tsx
- bricks/brick-visualization/src/visual-form-rules-setting/index.spec.ts
- bricks/brick-visualization/src/visual-form-rules-setting/index.tsx
- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.tsx
Ref: NEXT_BUILDER-2641
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): feat visual-form-rules-setting

- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.spec.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- types/preview/index.d.ts
> feat(): support workbench cache action `update.visualForm`

- bricks/brick-visualization/src/visual-form-rules-setting/VisualFormRulesSetting.tsx
> fix(): fix error caused by undefined formChildren

- bricks/forms/src/dynamic-common-item/DynamicCommonItem.spec.tsx
- bricks/forms/src/dynamic-common-item/DynamicCommonItem.tsx
refs KEY_MANAGEMENT-53
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): dynamicCommonItem删除项时，列设置了encrypt属性为true的数据应该继续保持转码处理

- bricks/basic-bricks/src/general-text/GeneralText.spec.tsx
- bricks/basic-bricks/src/general-text/GeneralText.tsx
- bricks/basic-bricks/src/general-text/index.tsx
refs BRICK_STORE-3304
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-text): textAlign属性不生效

- bricks/presentational-bricks/src/brick-tree/BrickTree.spec.tsx
- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.spec.ts
- bricks/presentational-bricks/src/brick-tree/index.tsx
> feat(): 暴露搜索事件出去 refs TOOL-1339

- bricks/presentational-bricks/src/digital-number/DigitalNumber.module.css
- bricks/presentational-bricks/src/digital-number/DigitalNumber.spec.tsx
- bricks/presentational-bricks/src/digital-number/DigitalNumber.tsx
- bricks/presentational-bricks/src/digital-number/index.spec.ts
- bricks/presentational-bricks/src/digital-number/index.tsx
- bricks/presentational-bricks/src/index.ts
ref: BRICK_STORE-3226
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): finish digit-number

- bricks/brick-visualization/src/visual-form-rules-setting/VisualFormRulesSetting.tsx
- bricks/brick-visualization/src/visual-form-rules-setting/components/ListEditor/ListEditor.tsx
Ref: NEXT_BUILDER-2719
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update rule-setting-list-editor default value

- bricks/brick-visualization/package.json
- bricks/forms/src/general-input/index.tsx
- bricks/forms/src/icon-select/index.tsx
- bricks/presentational-bricks/src/brick-alert/index.tsx
- yarn.lock
> feat(): update visual form dependencies

- bricks/basic-bricks/src/general-timer/index.tsx
ref: SERVICE_OBSERVE-2265
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 添加定时器是否开启的属性

- bricks/brick-visualization/src/visual-form-rules-setting/components/ListEditor/ListEditor.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/CacheActionList.spec.tsx
- bricks/next-builder/src/workbench-cache-action/CacheActionList.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.spec.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
Ref: NEXT_BUILDER-2692
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): feat workbenchAction action update.visualForm

- bricks/forms/src/crontab-input/CrontabInput.tsx
- bricks/forms/src/crontab-input/useCrontab.ts
Refs NEXT_BUILDER-2738
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复 general-form setInitValue 时视图不更新问题

- bricks/forms/src/general-form/index.tsx
- bricks/forms/src/general-input/index.tsx
- bricks/forms/src/general-select/index.tsx
refs NEXT_BUILDER-2693
请勾选以下两组选项其中之一：
或者：
>
>
> doc(): 更新general-form、general-input、general-select的文档

- bricks/developers/package.json
- yarn.lock
> fix(): update basic-components

- bricks/forms/src/general-radio/index.tsx
Ref: NEXT_BUILDER-2694
请勾选以下两组选项其中之一：
或者：
>
>
> docs(): update general-radio docs

- bricks/forms/src/general-input/index.tsx
> docs(): fix input docs editor

- bricks/frame-bricks/src/side-bar/SideBar.module.css
close CD-4077
请勾选以下两组选项其中之一：
或者：
>
>
> feat(sideBar): sideBar support ui8.2

- bricks/forms/src/general-checkbox/index.tsx
> docs(): update checkbox docs

- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
> fix(): slot item not allow drop

- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
- bricks/frame-bricks/src/side-bar/SidebarMenu.tsx
> fix(): 修改二级菜单icon样式

- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/CacheActionList.spec.tsx
- bricks/next-builder/src/workbench-cache-action/CacheActionList.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- types/preview/index.d.ts
Refs NEXT_BUILDER-2682
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support batch operation

- bricks/basic-bricks/src/general-card/index.shadow.less
- bricks/basic-bricks/src/sub-menu/index.module.css
ref CD-4035
请勾选以下两组选项其中之一：
或者：
>
>
> fix(subMenu): subMenu support ui8.2

- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/general-preview-image/GeneralPreviewImage.module.css
- bricks/presentational-bricks/src/general-preview-image/GeneralPreviewImage.spec.tsx
- bricks/presentational-bricks/src/general-preview-image/GeneralPreviewImage.tsx
- bricks/presentational-bricks/src/general-preview-image/components/Image.spec.tsx
- bricks/presentational-bricks/src/general-preview-image/components/Image.tsx
- bricks/presentational-bricks/src/general-preview-image/components/Operations.module.css
- bricks/presentational-bricks/src/general-preview-image/components/Operations.spec.tsx
- bricks/presentational-bricks/src/general-preview-image/components/Operations.tsx
- bricks/presentational-bricks/src/general-preview-image/components/Preview.spec.tsx
- bricks/presentational-bricks/src/general-preview-image/components/Preview.tsx
- bricks/presentational-bricks/src/general-preview-image/components/PreviewGroup.spec.tsx
- bricks/presentational-bricks/src/general-preview-image/components/PreviewGroup.tsx
- bricks/presentational-bricks/src/general-preview-image/components/__snapshots__/Image.spec.tsx.snap
- bricks/presentational-bricks/src/general-preview-image/components/__snapshots__/Preview.spec.tsx.snap
- bricks/presentational-bricks/src/general-preview-image/components/__snapshots__/PreviewGroup.spec.tsx.snap
- bricks/presentational-bricks/src/general-preview-image/components/getFixScaleEleTransPosition.spec.ts
- bricks/presentational-bricks/src/general-preview-image/components/getFixScaleEleTransPosition.ts
- bricks/presentational-bricks/src/general-preview-image/components/hooks/useImageTransform.spec.tsx
- bricks/presentational-bricks/src/general-preview-image/components/hooks/useImageTransform.ts
- bricks/presentational-bricks/src/general-preview-image/components/previewConfig.ts
- bricks/presentational-bricks/src/general-preview-image/index.spec.ts
- bricks/presentational-bricks/src/general-preview-image/index.tsx
- bricks/presentational-bricks/src/i18n/constants.ts
- bricks/presentational-bricks/src/i18n/locales/en.ts
- bricks/presentational-bricks/src/i18n/locales/zh.ts
- bricks/presentational-bricks/src/index.ts
- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.tsx
- yarn.lock
> markdownDisplay组件支持图片相册模式预览

- bricks/forms/src/general-auto-complete/index.tsx
- bricks/forms/src/general-textarea/index.tsx
- bricks/presentational-bricks/src/brick-alert/index.tsx
Ref: NEXT_BUILDER-2766
请勾选以下两组选项其中之一：
或者：
>
>
> docs(): update form bricks docs

- bricks/forms/src/general-date-picker/index.tsx
- bricks/forms/src/general-input-number/index.tsx
- bricks/forms/src/input-with-unit/index.tsx
- bricks/presentational-bricks/src/markdown-editor/index.tsx
> docs(): update bricks docs

- bricks/presentational-bricks/stories/chapters/card-item.ts
> fix(): 信息展示卡片 优化升级一

- bricks/brick-visualization/src/visual-form-rules-setting/VisualFormRulesSetting.tsx
> fix(): fix visual-form-rules-setting bug

- bricks/presentational-bricks/src/brick-table/BrickTable.spec.tsx
- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
> fix(): 自定义空数据的构件 refs APPCONFIG-987

- bricks/forms/src/general-checkbox/GeneralCheckbox.module.css
> fix(): checkbox圆角调整

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
Refs INSTANCE-4386
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): label中显示多个且第一个不存在时用"-"代替

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.module.css
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/cmdb-instance-select/index.tsx
close CD-4179
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 应用列表下拉选项的值过长时，悬浮展示框错位

- bricks/presentational-bricks/src/general-preview-image/GeneralPreviewImage.tsx
- bricks/presentational-bricks/src/general-preview-image/components/Image.tsx
- bricks/presentational-bricks/src/general-preview-image/index.tsx
- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.spec.tsx
- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.tsx
- bricks/presentational-bricks/src/markdown-display/index.tsx
Refs PRODUCT-7
请勾选以下两组选项其中之一：
或者：
>
>
> fix(presentational-bricks):markdownDisplay组件添加参数控制图片预览

- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/info-display-card-list/InfoDisplayCardList.spec.tsx
- bricks/presentational-bricks/src/info-display-card-list/InfoDisplayCardList.tsx
- bricks/presentational-bricks/src/info-display-card-list/__mocks__/infoList.ts
- bricks/presentational-bricks/src/info-display-card-list/index.module.css
- bricks/presentational-bricks/src/info-display-card-list/index.tsx
- bricks/presentational-bricks/stories/chapters/card-item.ts
- bricks/presentational-bricks/stories/chapters/info-display-card-list.ts
> feat(): 信息展示卡片 优化升级三

- bricks/developers/src/stories/chapters/atom-bricks/other/entry-card-list.ts
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.shadow.less
- bricks/presentational-bricks/src/card-item/index.tsx
- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.module.css
- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.tsx
- bricks/presentational-bricks/src/info-display-card-list/InfoDisplayCardList.tsx
- bricks/presentational-bricks/stories/chapters/card-item.ts
- bricks/presentational-bricks/stories/chapters/info-display-card-list.ts
> feat(): 入口卡片 优化升级

- bricks/forms/src/general-textarea/GeneralTextArea.spec.tsx
- bricks/forms/src/general-textarea/GeneralTextArea.tsx
> feat(): textArea支持输入tab键 close ARTIFACT-555

- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
> fix(): 调整二级菜单图标样式

- bricks/brick-visualization/src/visual-form-rules-setting/VisualFormRulesSetting.tsx
- bricks/brick-visualization/src/visual-form-rules-setting/components/ConditionalFormat/ConditionalFormat.module.css
- bricks/brick-visualization/src/visual-form-rules-setting/components/ConditionalFormat/ConditionalFormat.spec.tsx
- bricks/brick-visualization/src/visual-form-rules-setting/components/ConditionalFormat/ConditionalFormat.tsx
Ref: NEXT_BUILDER-2815
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): feat visualFormRulesSetting more form item type

- bricks/brick-visualization/src/visual-form-rules-setting/VisualFormRulesSetting.tsx
- bricks/brick-visualization/src/visual-form-rules-setting/components/ConditionalFormat/ConditionalFormat.spec.tsx
- bricks/brick-visualization/src/visual-form-rules-setting/components/ConditionalFormat/ConditionalFormat.tsx
> feat(): edit operation value

- bricks/forms/src/general-textarea/GeneralTextArea.tsx
> fix(): 重新提交forms-nb

- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.shadow.less
- bricks/presentational-bricks/src/card-item/index.spec.ts
- bricks/presentational-bricks/src/card-item/index.tsx
- bricks/presentational-bricks/stories/chapters/card-item.ts
- bricks/presentational-bricks/stories/chapters/info-display-card-list.ts
> fix(): 卡片组件升级验收问题汇总

- bricks/presentational-bricks/src/card-item/index.shadow.less
- bricks/presentational-bricks/stories/chapters/card-item.ts
> fix(): close BRICK_STORE-3345

- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- yarn.lock
refs ITSERVICE_NEXT-5817
请勾选以下两组选项其中之一：
或者：
>
>
> feat():ITSERVICE_NEXT-5817 作为交付，我希望银联国际项目定制的登录方式能接入内部双因子验证，以便满足客户需求

- bricks/presentational-bricks/src/brick-value-mapping/BrickValueMapping.spec.tsx
- bricks/presentational-bricks/src/brick-value-mapping/BrickValueMapping.tsx
> fix(): BrickValueMapping文字省略时用tooltip展示全部内容 Closes INSTANCE-4538

- bricks/next-builder/src/shared/quick-generate/factory.ts
> chore(): only for publish new version

- bricks/presentational-bricks/src/card-item/index.shadow.less
- bricks/presentational-bricks/stories/chapters/card-item.ts
> fix(): fix BRICK_STORE-3345

- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- yarn.lock
refs ITSERVICE_NEXT-5817
请勾选以下两组选项其中之一：
或者：
>
>
> fix():ITSERVICE_NEXT-5817 作为交付，我希望银联国际项目定制的登录方式能接入内部双因子验证，以便满足客户需求

- bricks/presentational-bricks/src/brick-humanize-time/BrickHumanizeTime.spec.tsx
- bricks/presentational-bricks/src/brick-humanize-time/BrickHumanizeTime.tsx
Closes BRICK_STORE-3347
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-humanize-time): return hyphen when value is null or undefined and isCostTime is true

- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.module.css
> fix(): entryCard改为hover整张卡片时改变样式

- bricks/flow-builder/src/schema-editor/components/schema-item/SchemaItem.spec.tsx
- bricks/flow-builder/src/schema-editor/components/schema-item/SchemaItem.tsx
Ref: C_CENTER-56
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): feat contracts show enum

- bricks/next-builder/src/shared/quick-generate/FormTypeGenerator.spec.ts
- bricks/next-builder/src/shared/quick-generate/FormTypeGenerator.ts
- bricks/next-builder/src/shared/quick-generate/TableTypeGenerator.ts
- bricks/next-builder/src/shared/quick-generate/factory.spec.ts
- bricks/next-builder/src/shared/quick-generate/interface.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- bricks/next-builder/src/workbench-cache-action/index.spec.ts
- bricks/next-builder/src/workbench-cache-action/index.tsx
- types/preview/index.d.ts
Refs NEXT_BUILDER-2917
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refactor quick generator

- bricks/presentational-bricks/src/brick-descriptions/BrickDescriptions.module.css
ref CD-4214
请勾选以下两组选项其中之一：
或者：
>
>
> fix(descriptions): css fix

- bricks/basic-bricks/src/app-bar/DesktopCell/DesktopCell.module.css
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.module.css
Ref: INSTANCE-4120
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update app-bar style

- bricks/next-builder/src/shared/quick-generate/CommTypeGenerator.spec.ts
- bricks/next-builder/src/shared/quick-generate/CommTypeGenerator.ts
- bricks/next-builder/src/shared/quick-generate/FormTypeGenerator.spec.ts
- bricks/next-builder/src/shared/quick-generate/FormTypeGenerator.ts
- bricks/next-builder/src/shared/quick-generate/TableTypeGenerator.spec.ts
- bricks/next-builder/src/shared/quick-generate/TableTypeGenerator.ts
REfs NEXT_BUILDER-2916
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support provider modification

- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- yarn.lock
Reverts easyops-cn/next-basics#2117
> Revert "fix():ITSERVICE_NEXT-5817 作为交付，我希望银联国际项目定制的登录方式能接入内部双因子验证，以便满足客户需求"

- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- yarn.lock
refs ITSERVICE_NEXT-5817
请勾选以下两组选项其中之一：
或者：
>
>
> fix():回退银联国际定制化登陆页面代码

- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.spec.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
- bricks/next-builder/src/workbench-component-select/constants.ts
- bricks/next-builder/src/workbench-component-select/index.tsx
> feat(): feat workbench-component-select suggest list

- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- bricks/general-auth/src/general-signup/GeneralSignup.spec.tsx
- bricks/general-auth/src/general-signup/GeneralSignup.tsx
refs INFRA-1568
请勾选以下两组选项其中之一：
或者：
>
>
> fix():INFRA-1568 登录页允许屏蔽掉优维相关页面元素

- bricks/presentational-bricks/package.json
- yarn.lock
> fix(): close MONITOR-5331 refs MONITOR-5331

- bricks/forms/src/general-date-picker/index.tsx
- bricks/forms/src/general-input-number/index.tsx
- bricks/forms/src/general-textarea/index.tsx
- bricks/forms/src/general-time-picker/index.tsx
- bricks/presentational-bricks/src/markdown-editor/index.tsx
> docs(): update docs

- bricks/forms/src/time-range-picker/TimeRangePicker.tsx
refs CD-4399
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 时间选择器无法清除数据

- bricks/next-builder/src/data-providers/LintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> feat(): update storyboard lint

- bricks/next-builder/src/custom-processors/getWorkflowGraph.spec.ts
- bricks/next-builder/src/custom-processors/getWorkflowGraph.ts
- bricks/next-builder/src/index.ts
- bricks/next-builder/src/workflow-node/WorkflowNode.module.css
- bricks/next-builder/src/workflow-node/WorkflowNode.spec.tsx
- bricks/next-builder/src/workflow-node/WorkflowNode.tsx
- bricks/next-builder/src/workflow-node/index.spec.ts
- bricks/next-builder/src/workflow-node/index.tsx
Refs NEXT_BUILDER-2911
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): suppport work flow node

- bricks/basic-bricks/src/sub-menu/index.module.css
> fix(): 三级菜单优化

- bricks/next-builder/src/shared/components/contract-auto-complete/ContractAutoComplete.spec.tsx
- bricks/next-builder/src/shared/components/contract-auto-complete/ContractAutoComplete.tsx
Refs NEXT_BUILDER-3037
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复契约 copy 问题

- bricks/next-builder/src/shared/quick-generate/processor.spec.ts
> chore(): only for republish

- bricks/forms/src/user-or-user-group-select/UserOrUserGroupSelect.tsx
> fix(): 修复因为hideInvalidUser属性,用户组获取数据参数不对问题 refs ITSERVICE_NEXT-6101

- bricks/general-auth/src/general-signup/GeneralSignup.module.css
- bricks/general-auth/src/general-signup/GeneralSignup.tsx
> fix(general-auth): 注册页面ui和登录页面一致

- .size-limit.js
- bricks/presentational-bricks/package.json
- yarn.lock
> fix(): update basic-components version

- bricks/presentational-bricks/src/brick-value-mapping/BrickValueMapping.tsx
> fix(brickValueMapping): adjust generalIcon position

- bricks/basic-bricks/src/general-card/index.shadow.less
Closes CD-4482
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-card): update compact mode style

- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> fix(): fix lint error

- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
> fix(): NEXT_BUILDER-2934 二级菜单分类颜色需替换

- bricks/developers/src/components/BrickPreview/BrickPreview.spec.tsx
- bricks/developers/src/components/BrickPreview/BrickPreview.tsx
> fix(): use createRoot

- .size-limit.js
- bricks/next-builder/package.json
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- yarn.lock
> feat(): add brick or provider and auto insert dep

- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.module.css
- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.spec.tsx
- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.tsx
> fix(): 自定义cmdb首页，资源名称显示不全 Closes CMDB_EXTEND-324

- bricks/presentational-bricks/src/general-carousel/index.module.css
> fix(): 修改轮播构件的样式

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
> fix(): 修改斑马纹表格调整的bug

- bricks/next-builder/src/data-providers/UpdateBricks.spec.ts
- bricks/next-builder/src/data-providers/UpdateBricks.ts
- bricks/next-builder/src/utils/walk.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> feat(): support update route or template

- bricks/forms/src/general-structs-form-item/index.tsx
> fix(): 修改generalgeneral-structs-form-item关闭时触发父modal关闭问题

- bricks/next-builder/src/custom-processors/getWorkflowGraph.spec.ts
- bricks/next-builder/src/custom-processors/getWorkflowGraph.ts
Refs NEXT_BUILDER-3064
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): modifeid field

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStr.tsx
- bricks/forms/src/general-structs-form-item/index.tsx
Refs INSTANCE-4847
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): fix受保护的字符型字段没有禁用完全

- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.tsx
> feat(): brick tree support stopEvent

- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
> fix(): update brick tree code

- .size-limit.js
- bricks/next-builder/src/data-providers/AddDependencies.spec.ts
- bricks/next-builder/src/data-providers/AddDependencies.ts
- bricks/next-builder/src/index.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
> feat(): add dependencies provider

- bricks/next-builder/src/data-providers/AddDependencies.ts
- bricks/next-builder/src/data-providers/utils/dependCache.spec.ts
- bricks/next-builder/src/data-providers/utils/dependCache.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
> feat(): support dependCahce

- bricks/general-auth/src/general-login/GeneralLogin.tsx
Refs NEXT_BUILDER-3051
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix url container chinese characters

- bricks/presentational-bricks/src/brick-descriptions/BrickDescriptions.module.css
- bricks/presentational-bricks/src/brick-descriptions/BrickDescriptions.spec.tsx
- bricks/presentational-bricks/src/brick-descriptions/index.tsx
- bricks/presentational-bricks/stories/chapters/brick-descriptions.ts
close BRICK_STORE-3365
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-descriptions): 提供descriptionList属性

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
close BRICK_STORE-3354
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 表格组件第一列左侧padding调整

- bricks/presentational-bricks/src/brick-descriptions/BrickDescriptions.module.css
> fix(): brick-description样式调整

- bricks/next-builder/src/shared/storyboard/bundleMenu.spec.ts
- bricks/next-builder/src/shared/storyboard/bundleMenu.ts
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
> feat(): support build menu with imgSrc

- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.tsx
- bricks/forms/src/interfaces/dynamic-form-item-v2.ts
> feat(): support dynamicFormV2 support checkbox

- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
> fix(): fix await fetch depend

- bricks/next-builder/src/workflow-node/WorkflowNode.module.css
- bricks/next-builder/src/workflow-node/WorkflowNode.spec.tsx
- bricks/next-builder/src/workflow-node/WorkflowNode.tsx
- bricks/next-builder/src/workflow-node/index.tsx
Refs FLOW_BUILDER-824
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support suffixBrick

- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
> fix(sidebar): 修改二级菜单为img时的样式

- bricks/presentational-bricks/src/brick-tree/BrickTree.spec.tsx
- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.tsx
> feat(): brick-tree构件支持自定义图标 Refs ITSERVICE_NEXT-6226

- bricks/next-builder/package.json
- bricks/next-builder/src/shared/workbench/WorkbenchAvatarIcon.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/interfaces.ts
Closes NEXT_BUILDER-3166
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): workbenchTree support avatar-icon

- bricks/developers/src/components/NextBrickDemo/NextBrickDemo.tsx
- bricks/developers/src/components/NextBrickPreview/NextBrickPreview.module.css
- bricks/developers/src/components/NextBrickPreview/NextBrickPreview.tsx
- bricks/developers/src/components/NextBrickPreview/processor.spec.ts
- bricks/developers/src/components/NextBrickPreview/processor.ts
Refs NEXT_BUILDER-3115
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): optimize automatic height adjustment in developer brick preview

- bricks/forms/src/user-or-user-group-select/UserOrUserGroupSelect.spec.tsx
- bricks/forms/src/user-or-user-group-select/UserOrUserGroupSelect.tsx
- bricks/forms/src/user-or-user-group-select/index.tsx
> fix(): forms.user-or-user-group-select支持单选  refs EASY_AGILE-1069

- bricks/frame-bricks/src/side-bar/SideBar.tsx
close
NEXT_BUILDER-3100
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改二级菜单拖拽侧边栏bug

- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/presentational-bricks/src/brick-alert/BrickAlert.tsx
- bricks/presentational-bricks/src/brick-alert/style.module.css
> fix(sidebar): 二级菜单拖拽修复以及brick-tag样式修改

- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
> fix(sidebar): 修改二级菜单拖拽样式

- bricks/presentational-bricks/src/general-carousel/GeneralCarousel.spec.tsx
- bricks/presentational-bricks/src/general-carousel/GeneralCarousel.tsx
- bricks/presentational-bricks/src/general-carousel/index.tsx
Closes SERVICE_OBSERVE-2595
请勾选以下两组选项其中之一：
或者：
>
>
> feat(carousel): 支持配置上下自动滚动

- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-data-tree/WorkbenchDataTree.tsx
Closes NEXT_BUILDER-3167
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): brick-tree && data-tree can't drag

- bricks/presentational-bricks/src/card-item/index.shadow.less
> fix(): 修改card-item样式

- bricks/basic-bricks/src/popover-container/PopoverContainer.tsx
- bricks/basic-bricks/src/popover-container/index.tsx
Refs PIPELINE-1444
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support more properties of popover

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.spec.ts
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
Refs NEXT_BUILDER-3134
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support preview context/state value

- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
refs: BRICK_STORE-3379
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add featureFlag hidden-login-footer and brand.auth_login_bg_url

- bricks/presentational-bricks/src/brick-table/index.tsx
Closes CD-4715
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-table): add column.filters.update event

- bricks/basic-bricks/src/general-popup/GeneralPopup.spec.tsx
- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
- bricks/basic-bricks/src/general-popup/index.tsx
Refs NEXT_BUILDER-3134
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support resize property

- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
Closes NEXT_BUILDER-3167
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): allowDrag is false still trigger dragOver

- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/datetime-selector/DatetimeSelector.tsx
- bricks/presentational-bricks/src/datetime-selector/index.tsx
- yarn.lock
> feat(datetime): 增加rangeDays属性

- bricks/forms/src/general-form-item-v2/index.spec.ts
- bricks/forms/src/general-form-item-v2/index.tsx
- bricks/forms/src/general-form-item/AbstractFormControl.spec.tsx
- bricks/forms/src/general-form-item/AbstractFormControl.tsx
- bricks/forms/src/general-form-item/GeneralFormItem.spec.tsx
- bricks/forms/src/general-form-item/GeneralFormItem.tsx
- bricks/forms/src/index.ts
- bricks/forms/src/interfaces/general-form-item.ts
- bricks/forms/src/interfaces/index.ts
- bricks/forms/stories/chapters/general-form-item-v2.ts
- bricks/forms/stories/chapters/index.ts
Closes BRICK_STORE-3380
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add general-form-item-v2 brick

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/cmdb-instance-select/index.tsx
Refs EASY_AGILE-1162
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复cmdb实例选择构件选完值后依然聚焦导致再次点击时不触发onFocus重新请求数据

- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> feat(): do lint storyboard support new syntax

- bricks/presentational-bricks/src/index.ts
- bricks/presentational-bricks/src/tree-transfer/TreeTransfer.spec.tsx
- bricks/presentational-bricks/src/tree-transfer/TreeTransfer.tsx
- bricks/presentational-bricks/src/tree-transfer/index.spec.ts
- bricks/presentational-bricks/src/tree-transfer/index.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/TreeShuttleBox.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/TreeShuttleBoxLeft.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/TreeShuttleBoxRight.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/TreeShuttleButton.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/index.ts
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/interfaceType.ts
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/share.module.css
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/tool.spec.ts
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/tool.ts
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/useTreeContext.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/useTreeShuttle.ts
refs MONITOR-6059
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 新增树型结构穿梭框通用构件

- bricks/developers/src/provider-doc/ProviderSample/ProviderSample.tsx
Refs NEXT_BUILDER-3267
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): the situation where the value is null 

- bricks/presentational-bricks/src/brick-tag/index.module.css
> fix(brick-tag): 修改tag样式

- bricks/presentational-bricks/src/tree-transfer/TreeTransfer.spec.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/TreeShuttleBoxLeft.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/TreeShuttleBoxRight.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/TreeShuttleButton.tsx
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/tool.ts
- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/useTreeContext.tsx
refs MONITOR-6059
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复树型穿梭框数量准确性与切换dataSource时展开数据

- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.module.css
- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.spec.tsx
- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.tsx
- bricks/frame-bricks/src/nav-menu/utils.tsx
Closes DESIGNER_ROUTINE-649
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 新三级菜单样式

- bricks/presentational-bricks/src/general-pagination/GeneralPagination.tsx
> fix(general-pagination): fix page and pageSize which maybe undefined

- bricks/next-builder/src/shared/components/contract-auto-complete/ContractAutoComplete.spec.tsx
- bricks/next-builder/src/shared/components/contract-auto-complete/ContractAutoComplete.tsx
- bricks/next-builder/src/shared/components/contract-auto-complete/index.tsx
Refs NEXT_BUILDER-1563
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support suffix

- bricks/forms/src/general-form/GeneralForm.shadow.less
Closes CRONTAB-500
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): 菜单按钮样式

- bricks/presentational-bricks/src/datetime-selector/DatetimeSelector.tsx
- bricks/presentational-bricks/src/datetime-selector/index.tsx
> fix(datetime): 增加format属性

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
Closes DESIGNER_ROUTINE-651
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): storyboard菜单数据多层

- bricks/basic-bricks/src/fold-brick-v2/FoldBrickV2.tsx
- bricks/basic-bricks/src/fold-brick-v2/index.tsx
close APPCONFIG-1110
请勾选以下两组选项其中之一：
或者：
>
>
> feat(fold-brick-v2): support foldIcon

- bricks/forms/src/general-auto-complete/GeneralAutoComplete.module.css
- bricks/forms/src/general-auto-complete/GeneralAutoComplete.spec.tsx
- bricks/forms/src/general-auto-complete/GeneralAutoComplete.tsx
- bricks/forms/src/general-auto-complete/index.tsx
- bricks/forms/src/general-select/GeneralSelect.module.css
- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
- bricks/forms/src/interfaces/common.ts
Closes NEXT_BUILDER-3217
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): auto-complete、general-select构件 options 支持 caption

- bricks/basic-bricks/src/fold-brick-v2/FoldBrickV2.tsx
close APPCONFIG-1110
请勾选以下两组选项其中之一：
或者：
>
>
> fix(FoldBrickV2): css fix

- bricks/presentational-bricks/src/table-transfer/TableTransfer.tsx
- bricks/presentational-bricks/src/table-transfer/index.tsx
> fix(transfer): 表格穿梭框加一个搜索框placeholder配置项

- bricks/forms/src/general-auto-complete/GeneralAutoComplete.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.module.css
Closes DESIGNER_ROUTINE-648
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 三级菜单样式修改

- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.spec.tsx
- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.tsx
Closes DESIGNER_ROUTINE-648
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 三级菜单交互改为mouseEnter

- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
> chore(): normalizeMenu

- bricks/presentational-bricks/src/brick-descriptions/BrickDescriptions.module.css
- bricks/presentational-bricks/stories/chapters/brick-descriptions.ts
close DESIGNER_ROUTINE-641
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-descriptions): 增加表格描述列表

- bricks/basic-bricks/src/fold-brick-v2/index.tsx
Closes CD-4576
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 希望双态应用提供接入指引，引导用户做好部署准备工作并完成部署

- bricks/presentational-bricks/src/table-transfer/TableTransfer.tsx
- bricks/presentational-bricks/src/table-transfer/index.tsx
Closes MONITOR-6150
请勾选以下两组选项其中之一：
或者：
>
>
> fix(table-transfer): add`search.change`event

- bricks/next-builder/src/builder-container/interfaces.ts
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
Closes NEXT_BUILDER-3219
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): snippet增加原构件id

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
- bricks/presentational-bricks/src/brick-timeline/index.module.css
> fix(): 修改table及timeline样式

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
> fix(table): 修改table行高

- bricks/presentational-bricks/src/banner-display-card-list/BannerDisplayCardList.module.css
- bricks/presentational-bricks/src/banner-display-card-list/BannerDisplayCardList.spec.tsx
- bricks/presentational-bricks/src/banner-display-card-list/BannerDisplayCardList.tsx
- bricks/presentational-bricks/src/banner-display-card-list/index.spec.ts
- bricks/presentational-bricks/src/banner-display-card-list/index.tsx
- bricks/presentational-bricks/src/index.ts
Closes APPCONFIG-1110
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 希望配置中心提供友好的接入指引，便于用户快速入门

- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.spec.tsx
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- bricks/next-builder/src/workbench-cache-action/processDynamicSnippet.spec.ts
- bricks/next-builder/src/workbench-cache-action/processDynamicSnippet.ts
- types/preview/index.d.ts
Refs NEXT_BUILDER-3198
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support dynamic snippet

- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.module.css
- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.tsx
refs SERVICE_OBSERVE-2648
请勾选以下两组选项其中之一：
或者：
>
>
> style(): 调整样式已支持上下布局

- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.module.css
- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.tsx
refs SERVICE_OBSERVE-2648
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): 兼容在usebrick中使用columns 为undefined,导致报错的问题

- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.spec.tsx
- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.tsx
Closes NEXT_BUILDER-3365
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 三级菜单默认显示第一个分组

- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.spec.tsx
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
- bricks/frame-bricks/src/side-bar/SidebarMenu.tsx
Closes BRICK_STORE-3398
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 二级菜单交互动效优化

- bricks/next-builder/src/data-providers/AddDependencies.ts
Closes NEXT_BUILDER-3323
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 没有扫描到子构件 properties/events/lifeCycle/context/state 上的依赖

- bricks/next-builder/package.json
- bricks/next-builder/src/builder-container/interfaces.ts
- bricks/next-builder/src/custom-processors/getWorkbenchDataTree.spec.ts
- bricks/next-builder/src/custom-processors/getWorkbenchDataTree.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- yarn.lock
Refs NEXT_BUILDER-3360
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support dynamic snippet preview

- bricks/next-builder/src/data-providers/BackupBricks.spec.ts
- bricks/next-builder/src/data-providers/BackupBricks.ts
- bricks/next-builder/src/data-providers/UpdateBricksArrange.spec.ts
- bricks/next-builder/src/data-providers/UpdateBricksArrange.ts
- bricks/next-builder/src/data-providers/UpdateBricksToV3.spec.ts
- bricks/next-builder/src/data-providers/UpdateBricksToV3.ts
- bricks/next-builder/src/data-providers/UpgradeBricks.spec.ts
- bricks/next-builder/src/data-providers/UpgradeBricks.ts
- bricks/next-builder/src/data-providers/brickMap.ts
- bricks/next-builder/src/index.ts
- bricks/next-builder/src/utils/walk.spec.ts
- bricks/next-builder/src/utils/walk.ts
> feat(): support brick upgrade to v3

- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
> chore(): update navMenu style

- bricks/presentational-bricks/src/general-tooltip/GeneralTooltip.spec.tsx
- bricks/presentational-bricks/src/general-tooltip/GeneralTooltip.tsx
Closes BRICK_STORE-3397
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复tooltips有时候不触发

- bricks/next-builder/src/shared/workbench/WorkbenchBackend.spec.ts
- bricks/next-builder/src/shared/workbench/WorkbenchBackend.ts
> fix(): Temporarily removes the flag for ignoring workflow

- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/workbench-cache-action/processDynamicSnippet.ts
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
- bricks/next-previewer/src/preview-helper/previewStart.ts
Refs NEXT_BUILDER-3198
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): dynamic snippet optimization

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
Refs NEXT_BUILDER-3378
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): build and push support workflows

- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
Refs  NEXT_BUILDER-3378
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix spelling mistake

- bricks/basic-bricks/src/quick-visit-menu/QuickVisitMenu.spec.tsx
- bricks/basic-bricks/src/quick-visit-menu/QuickVisitMenu.tsx
- bricks/basic-bricks/src/quick-visit-menu/index.module.css
> fix(menu): 快捷访问菜单样式调整

- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
refs SSO-90
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 4a登录重定向方式调整

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
Refs  NEXT_BUILDER-3378
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): specified fields

- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.module.css
> chore(): 三级菜单样式调整

- bricks/basic-bricks/src/index.ts
- bricks/basic-bricks/src/virtual-list-container/VirtualListContainer.spec.tsx
- bricks/basic-bricks/src/virtual-list-container/VirtualListContainer.tsx
- bricks/basic-bricks/src/virtual-list-container/index.spec.ts
- bricks/basic-bricks/src/virtual-list-container/index.tsx
- bricks/basic-bricks/src/virtual-list-container/style.module.css
Refs ITSERVICE_NEXT-6555
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 公告栏虚拟滚动列表

- bricks/presentational-bricks/src/tree-transfer/treeShuttleBox/TreeShuttleBoxRight.tsx
refs MONITOR-6284
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 穿梭框右侧无法点击展开和收拢

- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
Closes NEXT_BUILDER-3374
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): NT构件依赖添加错误

- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/nav-menu/ThreeLevelMenuPopoverContent.module.css
> fix(): 三级菜单样式调整

- bricks/presentational-bricks/src/markdown-editor/MarkdownEditor.tsx
- bricks/presentational-bricks/src/markdown-editor/index.tsx
Refs AGILE-330
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): markdown编辑输入框支持配置显示行数

- bricks/basic-bricks/src/quick-visit-menu/MenuTag.tsx
- bricks/basic-bricks/src/quick-visit-menu/QuickVisitMenu.spec.tsx
- bricks/basic-bricks/src/quick-visit-menu/QuickVisitMenu.tsx
- bricks/basic-bricks/src/quick-visit-menu/index.module.css
Refs CMDB_INSTANCE-49
请勾选以下两组选项其中之一：
或者：
>
>
> fix(cmdb): 快捷访问菜单样式优化

- bricks/general-auth/src/general-login/GeneralLogin.module.css
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- bricks/general-auth/src/i18n/locales/en.ts
- bricks/general-auth/src/i18n/locales/zh.ts
refs SSO-90
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 将4a登录方式切换放在右上角

- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.spec.tsx
- bricks/next-builder/src/workbench-component-select/WorkbenchComponentSelect.tsx
- bricks/next-builder/src/workbench-component-select/constants.ts
Refs NEXT_BUILDER-3329
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support workflow category

- bricks/form-builder/src/cmdb-cascader-path-setter/CmdbCascaderPathSetter.tsx
Refs ITSERVICE_NEXT-6602
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fb cmdb级联配置模型不支持模型名称搜索

- bricks/basic-bricks/src/virtual-list-container/VirtualListContainer.tsx
- bricks/basic-bricks/src/virtual-list-container/index.spec.ts
- bricks/basic-bricks/src/virtual-list-container/index.tsx
Refs ITSERVICE_NEXT-6602
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 滚动列表数据不进行添加操作

- bricks/basic-bricks/src/quick-visit-menu/QuickVisitMenu.tsx
- bricks/basic-bricks/src/quick-visit-menu/index.module.css
> fix(basic-bricks): 快捷访问输入框有字且鼠标悬浮时才出现删除按钮

- bricks/basic-bricks/src/quick-visit-menu/index.module.css
> fix(basic-bricks): 快捷访问搜索框样式优化

- bricks/basic-bricks/src/quick-visit-menu/MenuTag.tsx
- bricks/basic-bricks/src/quick-visit-menu/QuickVisitMenu.spec.tsx
- bricks/basic-bricks/src/quick-visit-menu/QuickVisitMenu.tsx
- bricks/basic-bricks/src/quick-visit-menu/index.tsx
> fix(basic-bricks): 优化快捷访问菜单闪烁的问题

- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
Refs ITSERVICE_NEXT-6542
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 指定拖拽元素类型可配置

- bricks/calendar-bricks/src/agenda-calendar/AgendaCalendar.tsx
- bricks/calendar-bricks/src/agenda-calendar/component/customDayPlugin.tsx
> fix(): Date.toLocaleString兼容性问题，使用moment.js代替 ref NEXT_BUILDER-3447

- bricks/calendar-bricks/src/agenda-calendar/AgendaCalendar.spec.tsx
> fix(): 修改示例文案，重新触发流水线 ref NEXT_BUILDER-3447

- bricks/presentational-bricks/src/brick-result/index.shadow.less
Refs NEXT_BUILDER-3366
请勾选以下两组选项其中之一：
或者：
>
>
> fix(presentational-bricks): 次要标题字号与颜色调整

- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.tsx
refs MONITOR-6354
请勾选以下两组选项其中之一：
或者：
>
>
> style(): 优化右侧删除按钮间距

- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/chunks/doLintStoryboard.ts
> fix(): fix doLint match batch update problem

- bricks/basic-bricks/src/virtual-list-container/VirtualListContainer.tsx
Refs ITSERVICE_NEXT-6554
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): virtual list add empty status

- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
> chore(): 分类菜单弹出层左对齐

- bricks/presentational-bricks/src/general-carousel/GeneralCarousel.spec.tsx
- bricks/presentational-bricks/src/general-carousel/GeneralCarousel.tsx
- bricks/presentational-bricks/src/general-carousel/index.tsx
refs DASHBOARD-45
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 走马灯支持按需加载幻灯片

- bricks/basic-bricks/src/sub-menu/SubMenu.spec.tsx
- bricks/basic-bricks/src/sub-menu/SubMenu.tsx
- bricks/basic-bricks/src/sub-menu/index.module.css
- bricks/frame-bricks/src/side-bar/SideBar.module.css
Closes BRICK_STORE-3385
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 三级菜单背景颜色调整

- bricks/presentational-bricks/src/copyable-text/CopyableText.spec.tsx
- bricks/presentational-bricks/src/tree-transfer/TreeTransfer.spec.tsx
> chore(presentational-bricks): add jest

- bricks/general-auth/src/general-login/GeneralLogin.tsx
- bricks/general-auth/src/i18n/locales/en.ts
- bricks/general-auth/src/i18n/locales/zh.ts
refs SSO-90
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 兼容nw登录标题

- bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> fix(): cacheAction render error in v3

- bricks/calendar-bricks/src/agenda-calendar/index.shadow.less
> fix(): CUSTOMIZE-338 日历构件优化 ref CUSTOMIZE-338

- bricks/next-builder/src/shared/components/workflow-data-field/WorkflowDataField.spec.tsx
- bricks/next-builder/src/shared/components/workflow-data-field/WorkflowDataField.tsx
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
- bricks/next-builder/src/workflow-condition-item/WorkflowConditionItem.tsx
- bricks/next-builder/src/workflow-create-data-item/WorkflowCreateDataItem.tsx
Refs NEXT_BUILDER-1554
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): throw an error if the contract cannot be found

- bricks/flow-builder/src/variable-item/VariableItem.tsx
- bricks/flow-builder/src/variable-item/index.tsx
- bricks/flow-builder/src/variable-item/variable-display/VariableDisplay.tsx
- bricks/flow-builder/src/variable-list/VariableList.tsx
Refs NEXT_BUILDER-3403
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support labelBrick

- bricks/general-auth/src/custom-processors/getCookieByName.ts
- bricks/general-auth/src/index.ts
refs CMDB_INSTANCE-155
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 通过cookie名称获取cookie值

- bricks/presentational-bricks/src/general-badge/GeneralBadge.module.css
Closes DESIGNER_ROUTINE-655
请勾选以下两组选项其中之一：
或者：
>
>
> fix(presentational-bricks.general-badge): 去掉徽标描边
