- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
- bricks/brick-visualization/src/visual-property-form/index.spec.ts
- bricks/brick-visualization/src/visual-property-form/index.tsx
Refs NEXT_BUILDER-653
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add values.change events

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStr.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStr.tsx
fixes INSTANCE-1373
请勾选以下两组选项其中之一：
或者：
>
>
> fix(object-attr): 流水线号和自增ID起始值增加默认值

- bricks/basic-bricks/src/general-modal/GeneralModal.tsx
- bricks/basic-bricks/src/general-modal/index.shadow.less
- bricks/basic-bricks/src/general-modal/index.tsx
- bricks/basic-bricks/stories/chapters/general-modal.ts
Closes INSTANCE-1390
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-modal): 增加模态框标题后插槽

- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.spec.tsx
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
- bricks/brick-visualization/src/visual-property-form/index.tsx
- bricks/brick-visualization/src/visual-property-form/processor.spec.ts
- bricks/brick-visualization/src/visual-property-form/processor.ts
Refs NEXT_BUILDER-653
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix form set initValue problem

- bricks/developers/src/stories/chapters/atom-bricks/form-input/index.ts
- bricks/forms/stories/chapters/advance-setting.ts
- bricks/forms/stories/chapters/cmdb-instance-select-panel.ts
- bricks/forms/stories/chapters/cmdb-object-attr-value.ts
- bricks/forms/stories/chapters/form-crontab-input.ts
- bricks/forms/stories/chapters/form-modal.ts
- bricks/forms/stories/chapters/general-auto-complete.ts
- bricks/forms/stories/chapters/general-buttons.ts
- bricks/forms/stories/chapters/general-cascader.ts
- bricks/forms/stories/chapters/general-date-picker.ts
- bricks/forms/stories/chapters/general-form-item.ts
- bricks/forms/stories/chapters/general-input-number.ts
- bricks/forms/stories/chapters/general-input.ts
- bricks/forms/stories/chapters/general-select.ts
- bricks/forms/stories/chapters/general-slide.ts
- bricks/forms/stories/chapters/general-structs-form-item.ts
- bricks/forms/stories/chapters/general-switch.ts
- bricks/forms/stories/chapters/general-textarea.ts
- bricks/forms/stories/chapters/general-time-picker.ts
- bricks/forms/stories/chapters/icon-select.ts
- bricks/forms/stories/chapters/index.ts
- bricks/forms/stories/chapters/inform-methods-form.ts
- bricks/forms/stories/chapters/input-with-unit.ts
- bricks/forms/stories/chapters/time-range-picker.ts
- bricks/forms/stories/chapters/upload-img.ts
- bricks/forms/stories/chapters/user-or-user-group-select.ts
- bricks/forms/stories/constants.ts
> chore(): 文档迁移

- bricks/forms/src/custom-templates/tpl-cmdb-object-attr-add.ts
refs INSTANCE-1371
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): forms.tpl-cmdb-object-attr-add,表单label文字不对

- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
Refs NEXT_BUILDER-653
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): add validate message

- bricks/forms/src/cmdb-object-attr-value/CmdbObjectAttrValue.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
- bricks/forms/src/cmdb-object-attr-value/index.tsx
- bricks/forms/src/custom-templates/tpl-cmdb-object-attr-add.ts
refs INSTANCE-1371
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): forms.tpl-cmdb-object-attr-add,修改template编辑状态

- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.spec.tsx
- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
- bricks/basic-bricks/src/general-custom-buttons/index.tsx
refs BRICK_STORE-2030
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): custom-button支持定义moreButton的类型

- bricks/next-builder/src/builder-container/BuilderContainer.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/index.tsx
> feat(builder-container): support fullscreen toggle event

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/EventsView/getBricksWithEvents.spec.ts
- bricks/next-builder/src/builder-container/EventsView/getBricksWithEvents.ts
> feat(): scan bricks with events

- bricks/developers/src/brick-document/BrickDocument.tsx
> chore(): refine doc

- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.module.css
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.spec.tsx
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
- bricks/brick-visualization/src/visual-property-form/processor.spec.ts
- bricks/brick-visualization/src/visual-property-form/processor.ts
- bricks/forms/src/general-form/index.tsx
Refs NEXT_BUILDER-653
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): property visualization support category

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/EventsView/BrickWithEventsItem.module.css
- bricks/next-builder/src/builder-container/EventsView/BrickWithEventsItem.spec.tsx
- bricks/next-builder/src/builder-container/EventsView/BrickWithEventsItem.tsx
- bricks/next-builder/src/builder-container/EventsView/EventsView.module.css
- bricks/next-builder/src/builder-container/EventsView/EventsView.spec.tsx
- bricks/next-builder/src/builder-container/EventsView/EventsView.tsx
> feat(): support events view

- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.spec.tsx
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
Refs NEXT_BUILDER-667
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复表单项 label 不显示 tooltips 问题

- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvas.tsx
- bricks/next-builder/src/builder-container/EventsView/getBricksWithEvents.ts
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.spec.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.tsx
> feat(): support to visualize custom templates

- bricks/next-builder/src/builder-container/BuilderContainer.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/constants.ts
- bricks/next-builder/src/builder-container/index.tsx
- bricks/next-builder/src/builder-container/interfaces.ts
> feat(): remember current toolbox tab

- .size-limit.js
- __mocks__/@next-libs/editor-components.js
- bricks/next-builder/package.json
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemFormModal.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemFormModal.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.module.css
- bricks/next-builder/src/builder-container/DataView/DataView.spec.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/DataView/utils.spec.ts
- bricks/next-builder/src/builder-container/DataView/utils.ts
- bricks/next-builder/src/builder-container/index.tsx
- bricks/next-builder/src/builder-container/interfaces.ts
refs NEXT_BUILDER-669
请勾选以下两组选项其中之一：
或者：
>
>
> feat(builder-container): Data View

- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.module.css
- bricks/next-builder/src/builder-container/DataView/DataView.spec.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/DataView/utils.spec.ts
- bricks/next-builder/src/builder-container/DataView/utils.ts
- bricks/next-builder/src/builder-container/index.tsx
refs NEXT_BUILDER-670
请勾选以下两组选项其中之一：
或者：
>
>
> feat(data-view): update context and delete context item

- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvas.spec.tsx
- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvas.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamCanvas.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/buildBrickEventDownstreamTree.ts
- bricks/next-builder/src/builder-container/EventStreamCanvas/interfaces.ts
- bricks/next-builder/src/builder-container/EventStreamCanvas/styleConfig.ts
- bricks/next-builder/src/builder-container/EventsView/BrickWithEventsItem.module.css
- bricks/next-builder/src/builder-container/EventsView/BrickWithEventsItem.spec.tsx
- bricks/next-builder/src/builder-container/EventsView/BrickWithEventsItem.tsx
- bricks/next-builder/src/builder-container/index.tsx
> feat(): show brick event stream

- bricks/forms/src/general-form/index.tsx
Refs NEXT_BUILDER-677
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复表单赋值失效的问题

- bricks/next-builder/package.json
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventDownstreamGraph.module.css
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventDownstreamGraph.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventNodeComponent.module.css
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventNodeComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamCanvas.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraphComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/buildBrickEventDownstreamTree.ts
- bricks/next-builder/src/builder-container/EventStreamCanvas/interfaces.ts
- bricks/next-builder/src/builder-container/EventStreamCanvas/styleConfig.ts
> feat(): show event downstream

- bricks/developers/src/brick-document/BrickDocument.tsx
Refs NEXT_BUILDER-677
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix doc

- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.module.css
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.spec.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.tsx
- bricks/next-builder/src/builder-container/index.tsx
- bricks/next-builder/src/builder-container/interfaces.ts
- bricks/next-builder/src/custom-processors/routeTree.ts
- bricks/next-builder/src/interface.ts
- bricks/next-builder/src/utils/generateRouteTree.spec.ts
- bricks/next-builder/src/utils/generateRouteTree.ts
> feat(builder-container): routes view

- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.module.css
- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.spec.tsx
- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.module.css
- bricks/next-builder/src/builder-container/DataView/DataView.spec.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.module.css
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.spec.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.tsx
- bricks/next-builder/src/builder-container/SearchComponent/SearchComponent.module.css
- bricks/next-builder/src/builder-container/SearchComponent/SearchComponent.spec.tsx
- bricks/next-builder/src/builder-container/SearchComponent/SearchComponent.tsx
refs NEXT_BUILDER-680
请勾选以下两组选项其中之一：
或者：
>
>
> feat(builder-container): search component

- bricks/next-builder/src/builder-container/RoutesView/RoutesView.spec.tsx
refs NEXT_BUILDER-680
请勾选以下两组选项其中之一：
或者：
>
>
> fix(route-view): add act in test

- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvas.spec.tsx
- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvas.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraph.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraphComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamHandler.module.css
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamHandler.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamNodeComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/buildBrickEventUpstreamTree.ts
- bricks/next-builder/src/builder-container/EventsView/getBricksWithEvents.spec.ts
- bricks/next-builder/src/builder-container/EventsView/getBricksWithEvents.ts
- bricks/next-builder/src/builder-container/interfaces.ts
> feat(): scan events defined by targetRef for custom templates

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
> fix(sub-menu-filter): 修复没有设置defaultOpenKeys时搜索出错

- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/EventsView/EventsView.module.css
- bricks/next-builder/src/builder-container/EventsView/EventsView.spec.tsx
- bricks/next-builder/src/builder-container/EventsView/EventsView.tsx
- bricks/next-builder/src/builder-container/EventsView/filterBricksWithEvents.spec.ts
- bricks/next-builder/src/builder-container/EventsView/filterBricksWithEvents.ts
- bricks/next-builder/src/builder-container/EventsView/getBricksWithEvents.ts
> feat(): search bricks with events

- bricks/brick-visualization/package.json
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.spec.tsx
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
- bricks/brick-visualization/src/visual-property-form/components/ColorEditor/ColorEditor.module.css
- bricks/brick-visualization/src/visual-property-form/components/ColorEditor/ColorEditorItem.spec.tsx
- bricks/brick-visualization/src/visual-property-form/components/ColorEditor/ColorEditorItem.tsx
- bricks/brick-visualization/src/visual-property-form/components/IconSelect/IconSelectFormItem.tsx
- bricks/brick-visualization/src/visual-property-form/constant.ts
- bricks/brick-visualization/src/visual-property-form/index.spec.ts
- bricks/brick-visualization/src/visual-property-form/index.tsx
- bricks/brick-visualization/src/visual-property-form/processor.spec.ts
- bricks/brick-visualization/src/visual-property-form/processor.ts
- bricks/presentational-bricks/src/brick-tag/index.tsx
- bricks/presentational-bricks/src/general-badge/index.tsx
- yarn.lock
Refs NEXT_BUILDER-692
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add color property editor

- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.spec.tsx
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
Refs NEXT_BUILDER-693
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix property form validate missing some value

- bricks/next-builder/src/data-providers/StoryboardAssembly.spec.ts
- bricks/next-builder/src/data-providers/StoryboardAssembly.ts
> fix(storyboard-assembly): return projectId

- bricks/next-builder/src/data-providers/ScanI18nInStoryboard.spec.ts
- bricks/next-builder/src/data-providers/ScanI18nInStoryboard.ts
- bricks/next-builder/src/data-providers/StoryboardAssembly.spec.ts
- bricks/next-builder/src/index.ts
> feat(): add a custom provider of scan-i18n-in-storyboard

- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/EventsView/EventsView.tsx
- bricks/next-builder/src/builder-container/RootNodeSelect/RootNodeSelect.module.css
- bricks/next-builder/src/builder-container/RootNodeSelect/RootNodeSelect.spec.tsx
- bricks/next-builder/src/builder-container/RootNodeSelect/RootNodeSelect.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.module.css
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.spec.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.tsx
- bricks/next-builder/src/builder-container/ToolboxPane/ToolboxPane.module.css
- bricks/next-builder/src/builder-container/ToolboxPane/ToolboxPane.tsx
- bricks/next-builder/src/builder-container/ToolboxPane/__mocks__/ToolboxPane.tsx
- bricks/next-builder/src/builder-container/constants.ts
> fix(builder-container): refine toolbox

- .size-limit.js
- bricks/next-builder/package.json
- bricks/next-builder/src/builder-container/DataView/ContextItem.module.css
- bricks/next-builder/src/builder-container/DataView/ContextItem.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItem.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.module.css
- bricks/next-builder/src/builder-container/DataView/DataView.spec.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
refs NEXT_BUILDER-686
请勾选以下两组选项其中之一：
或者：
>
>
> feat(data-view): draggable item

- package.json
- yarn.lock
Manually yarn renew by Github Actions.
> Yarn renew

- bricks/forms/stories/chapters/general-form.ts
> docs(general-form): 修改demo

- bricks/forms/src/general-form-item/index.tsx
> feat(general-form-item): passthrough pattern property

- bricks/next-builder/src/builder-container/BuilderContainer.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/RootNodeSelect/RootNodeSelect.module.css
- bricks/next-builder/src/builder-container/RootNodeSelect/RootNodeSelect.spec.tsx
- bricks/next-builder/src/builder-container/RootNodeSelect/RootNodeSelect.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.spec.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.tsx
- bricks/next-builder/src/builder-container/interfaces.ts
refs NEXT_BUILDER-686
请勾选以下两组选项其中之一：
或者：
>
>
> feat(builder-container): root node select

- bricks/presentational-bricks/src/brick-table/index.tsx
refs IPTABLES-96
refs BRICK_STORE-2031
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-table): sortOrder & pageSize & page

- bricks/forms/src/editor-bricks/general-buttons/general-buttons.editor.tsx
- bricks/forms/src/editor-bricks/general-checkbox/general-checkbox.editor.tsx
- bricks/forms/src/editor-bricks/general-date-picker/general-date-picker.editor.tsx
- bricks/forms/src/editor-bricks/general-input-number/general-input-number.editor.tsx
- bricks/forms/src/editor-bricks/general-input/general-input.editor.tsx
- bricks/forms/src/editor-bricks/general-radio/general-radio.editor.tsx
- bricks/forms/src/editor-bricks/general-select/general-select.editor.tsx
- bricks/forms/src/editor-bricks/general-slide/general-slide.editor.tsx
- bricks/forms/src/editor-bricks/general-switch/general-switch.editor.tsx
- bricks/forms/src/editor-bricks/general-textarea/general-textarea.editor.tsx
- bricks/forms/src/editor-bricks/general-time-picker/general-time-picker.editor.tsx
- bricks/forms/src/editor-bricks/shared/utils/getSmartDisplay.ts
- bricks/forms/src/editor-bricks/shared/utils/index.ts
- bricks/presentational-bricks/src/editor-bricks/statistic-card/statistic-card.editor.tsx
Refs NEXT_BUILDER-697
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): editor-bricks add smart display

- bricks/presentational-bricks/src/brick-link/BrickLink.spec.tsx
- bricks/presentational-bricks/src/brick-link/BrickLink.tsx
- bricks/presentational-bricks/src/brick-link/__snapshots__/BrickLink.spec.tsx.snap
Closes INSTANCE-1419
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-link): 没有label时取消icon的margin

- bricks/next-builder/src/builder-container/RootNodeSelect/RootNodeSelect.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.spec.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.tsx
refs NEXT_BUILDER-702
请勾选以下两组选项其中之一：
或者：
>
>
> fix(route-node-select): theme and search

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/cmdb-instance-select/index.tsx
> feat(): 实例选择器添加disabled属性

- bricks/next-builder/src/builder-container/BuilderContainer.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.module.css
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.spec.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.tsx
- bricks/next-builder/src/builder-container/interfaces.ts
> fix(): show route of routes and redirect

- bricks/presentational-bricks/src/info-display-card-list/InfoDisplayCardList.spec.tsx
- bricks/presentational-bricks/src/info-display-card-list/InfoDisplayCardList.tsx
- bricks/presentational-bricks/src/info-display-card-list/index.module.css
- bricks/presentational-bricks/src/info-display-card-list/index.tsx
Closes TOOL-669
请勾选以下两组选项其中之一：
或者：
>
>
> feat(InfoDisplayCard): infoDisplayCard支持titleBrick

- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.module.css
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.spec.tsx
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
- bricks/brick-visualization/src/visual-property-form/index.tsx
Refs NEXT_BUILDER-693
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine property form

- .size-limit.js
- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/BuilderContainer.module.css
- bricks/next-builder/src/builder-container/BuilderContainer.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbar/BuilderToolbar.module.css
- bricks/next-builder/src/builder-container/BuilderToolbar/BuilderToolbar.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbar/BuilderToolbar.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/RootNodeSelect/RootNodeSelect.module.css
- bricks/next-builder/src/builder-container/RootNodeSelect/RootNodeSelect.tsx
- bricks/next-builder/src/builder-container/ToolboxPane/ToolboxPane.module.css
- bricks/next-builder/src/builder-container/ToolboxPane/ToolboxPane.tsx
- bricks/next-builder/src/builder-container/index.tsx
refs NEXT_BUILDER-702
请勾选以下两组选项其中之一：
或者：
>
>
> feat(builder-container): toolbar

- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.shadow.less
- bricks/presentational-bricks/src/card-item/index.tsx
- bricks/presentational-bricks/stories/chapters/card-item.ts
refs BRICK_STORE-2039
请勾选以下两组选项其中之一：
或者：
>
>
> feat(card-item): tagConfig and imgSrc

- bricks/developers/src/stories/chapters/atom-bricks/card/general-card-list.ts
- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.shadow.less
- bricks/presentational-bricks/src/card-item/index.tsx
- bricks/presentational-bricks/stories/chapters/card-item.ts
refs BRICK_STORE-2040
请勾选以下两组选项其中之一：
或者：
>
>
> fix(card-item): style & demo

- bricks/presentational-bricks/src/general-tooltip/GeneralTooltip.spec.tsx
- bricks/presentational-bricks/src/general-tooltip/GeneralTooltip.tsx
- bricks/presentational-bricks/src/general-tooltip/index.tsx
- bricks/presentational-bricks/stories/chapters/general-tooltip.ts
Closes BRICK_STORE-2037 BRICK_STORE-2036
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-tooltip): 支持displayBrick和triggerByIcon

- bricks/brick-visualization/src/interfaces/brick-visualization.ts
- bricks/brick-visualization/src/interfaces/index.ts
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
- bricks/brick-visualization/src/visual-property-form/constant.ts
- bricks/brick-visualization/src/visual-property-form/index.tsx
- bricks/brick-visualization/src/visual-property-form/processor.spec.ts
- bricks/brick-visualization/src/visual-property-form/processor.ts
Refs NEXT_BUILDER-706
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): extract common properties

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/editor-bricks/any-brick/any-brick.editor.module.css
- bricks/basic-bricks/src/editor-bricks/any-brick/any-brick.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/any-brick/any-brick.editor.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeMountPoint/StoryboardTreeMountPoint.module.css
> feat(): show children in any-brick--editor

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
Closes TOOL-663
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): subMenuFilter 支持treeMode

- bricks/forms/src/time-range-picker/TimeRangePicker.tsx
- bricks/presentational-bricks/src/info-display-card-list/index.module.css
Closes TOOL-671
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): TimeRangePicker render with no initValue

- bricks/next-builder/src/builder-container/RoutesView/RoutesView.spec.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.tsx
refs NEXT_BUILDER-687
请勾选以下两组选项其中之一：
或者：
>
>
> feat(route-view): filter route data by query

- bricks/next-builder/src/builder-container/BuilderToolbar/BuilderToolbar.tsx
refs NEXT_BUILDER-705
请勾选以下两组选项其中之一：
或者：
>
>
> feat(builder-toolbar): tooltip

- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.module.css
- bricks/presentational-bricks/src/brick-tree/index.tsx
- bricks/presentational-bricks/stories/chapters/brick-tree.ts
Closes TOOL-664
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-tree): brick-tree support suffix

- bricks/presentational-bricks/src/info-display-card-list/InfoDisplayCardList.tsx
- bricks/presentational-bricks/src/info-display-card-list/index.module.css
Closes TOOL-671
请勾选以下两组选项其中之一：
或者：
- [  ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
>
>
> fix(InfoDisplayCardList): enable detail tooltip

- bricks/basic-bricks/src/general-card/index.shadow.less
> chore(general-card): increase footer z-index

- bricks/presentational-bricks/src/brick-tree/index.module.css
Closes TOOL-671
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-tree): tree with suffix style fix

- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
- yarn.lock
> fix(brick-table): use react-dnd dll

- bricks/presentational-bricks/src/info-display-card-list/index.module.css
> chore(): update InfoDisplayCardList style

- bricks/developers/src/stories/chapters/business-bricks/cmdb-instances/cmdb-instances-export.ts
- bricks/developers/src/stories/chapters/business-bricks/cmdb-instances/cmdb-instances-import.ts
- bricks/developers/src/stories/chapters/business-bricks/cmdb-instances/index.ts
- bricks/developers/src/stories/chapters/cmdb-instances.ts
- bricks/developers/src/stories/docs/cmdb-instances/cmdb-instances-export.md
- bricks/developers/src/stories/docs/cmdb-instances/cmdb-instances-import.md
> docs(cmdb-instances): add demo&doc

- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.tsx
- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.spec.tsx
- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.module.css
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbar/BuilderToolbar.module.css
- bricks/next-builder/src/builder-container/BuilderToolbar/BuilderToolbar.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/DataView/DataView.spec.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdown.module.css
- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdown.spec.tsx
- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdown.tsx
- bricks/next-builder/src/builder-container/ToolboxPane/ToolboxPane.tsx
- bricks/next-builder/src/i18n/constants.ts
- bricks/next-builder/src/i18n/locales/en.ts
- bricks/next-builder/src/i18n/locales/zh.ts
refs NEXT_BUILDER-700
请勾选以下两组选项其中之一：
或者：
>
>
> feat(builder-container): pin toolbar to the top

- bricks/basic-bricks/src/editor-bricks/micro-view/micro-view.editor.module.css
- bricks/basic-bricks/src/editor-bricks/micro-view/micro-view.editor.tsx
> fix(editor-bricks): fix micro-view--editor toolbar style

- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.module.css
- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.tsx
- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.module.css
- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdown.module.css
- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdown.spec.tsx
- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdown.tsx
- bricks/next-builder/src/builder-container/constants.ts
refs NEXT_BUILDER-700
请勾选以下两组选项其中之一：
或者：
>
>
> feat(builder-container): add frequently used bricks

- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.tsx
- bricks/next-builder/src/builder-container/BuilderContextMenu/useCanPaste.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContextMenu/useCanPaste.ts
> fix(builder): restrict node pasting

- bricks/forms/src/time-range-picker/TimeRangePicker.spec.tsx
- bricks/forms/src/time-range-picker/TimeRangePicker.tsx
Closes BRICK_STORE-2043
请勾选以下两组选项其中之一：
或者：
>
>
> fix(TimeRangePicker): time-range-picker不给value时无法定位默认日期位置

- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.spec.tsx
- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.tsx
- bricks/next-builder/src/builder-container/BrickLibrary/groupBricks.spec.ts
- bricks/next-builder/src/builder-container/BrickLibrary/groupBricks.ts
- bricks/next-builder/src/builder-container/BrickLibrary/searchBricks.spec.ts
- bricks/next-builder/src/builder-container/BrickLibrary/searchBricks.ts
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.tsx
- bricks/next-builder/src/builder-container/index.tsx
> fix(builder): fix custom template scope in brick library

- bricks/presentational-bricks/src/card-item/CardItem.spec.tsx
- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.shadow.less
- bricks/presentational-bricks/src/card-item/index.tsx
- bricks/presentational-bricks/src/info-display-card-list/index.module.css
Closes TOOL-663
请勾选以下两组选项其中之一：
或者：
>
>
> fix(Card): CardItem support imgSize

- bricks/basic-bricks/src/general-button/index.tsx
- bricks/forms/src/editor-bricks/general-select/general-select.editor.module.css
- bricks/forms/src/editor-bricks/general-select/general-select.editor.tsx
- bricks/forms/src/editor-bricks/shared/style/base-form-item.module.css
- bricks/presentational-bricks/src/brick-result/index.tsx
> fix(): some optimization

- bricks/brick-visualization/package.json
- bricks/forms/package.json
- bricks/presentational-bricks/package.json
- yarn.lock
> chore(): update @next-libs/forms

- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.tsx
- bricks/next-builder/src/builder-container/index.tsx
- bricks/next-builder/src/builder-container/interfaces.ts
> feat(builder): support to append bricks

- bricks/basic-bricks/src/editor-bricks/general-drawer/general-drawer.editor.module.css
- bricks/basic-bricks/src/editor-bricks/general-drawer/general-drawer.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/general-drawer/general-drawer.editor.tsx
- bricks/basic-bricks/src/editor-bricks/index.ts
> feat(): add general-drawer ui editor

- bricks/brick-visualization/src/visual-property-form/index.spec.ts
- bricks/brick-visualization/src/visual-property-form/index.tsx
Refs  NEXT_BUILDER-653
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add validate.error event

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/StoryboardTreeNode/StoryboardTreeNode.module.css
- bricks/next-builder/src/builder-container/StoryboardTreeNode/StoryboardTreeNode.tsx
refs NEXT_BUILDER-715
请勾选以下两组选项其中之一：
或者：
>
>
> feat(builder-container): set hoverNodeUid

- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemFormModal.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/DataView/utils.spec.ts
- bricks/next-builder/src/builder-container/DataView/utils.ts
refs NEXT_BUILDER-720
请勾选以下两组选项其中之一：
或者：
>
>
> feat(data-view): add onChange to context

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/editor-bricks/general-drawer/general-drawer.editor.module.css
- bricks/basic-bricks/src/editor-bricks/general-drawer/general-drawer.editor.tsx
- bricks/basic-bricks/src/editor-bricks/general-modal/general-modal.editor.module.css
- bricks/basic-bricks/src/editor-bricks/general-modal/general-modal.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/general-modal/general-modal.editor.tsx
- bricks/basic-bricks/src/editor-bricks/index.ts
> feat(): add general-modal editor

- bricks/next-builder/src/builder-container/utils/findQueryInNode.spec.tsx
- bricks/next-builder/src/builder-container/utils/findQueryInNode.ts
refs NEXT_BUILDER-721
请勾选以下两组选项其中之一：
或者：
>
>
> fix(find-query-in-node): letter case should be ignored

- bricks/forms/stories/chapters/time-range-picker.ts
- bricks/presentational-bricks/stories/chapters/info-display-card-list.ts
> chore(docs): update time-range-picker doc

- bricks/forms/src/dynamic-user-select-item/DynamicUserSelectItem.tsx
refs EVENT-314
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): forms.dynamic-user-select-item第一选项，应排除用户和用户组的选项

- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdown.module.css
- bricks/next-builder/src/builder-container/components/SearchableTree/SearchableTree.module.css
refs NEXT_BUILDER-724
请勾选以下两组选项其中之一：
或者：
>
>
> fix(searchable-tree): width & height

- bricks/forms/src/editor-bricks/general-date-picker/general-date-picker.editor.module.css
- bricks/forms/src/editor-bricks/general-date-picker/general-date-picker.editor.tsx
- bricks/forms/src/editor-bricks/general-input-number/general-input-number.editor.tsx
- bricks/forms/src/editor-bricks/general-input/general-input.editor.tsx
- bricks/forms/src/editor-bricks/general-select/general-select.editor.module.css
- bricks/forms/src/editor-bricks/general-select/general-select.editor.tsx
- bricks/forms/src/editor-bricks/general-textarea/general-textarea.editor.tsx
- bricks/forms/src/editor-bricks/general-time-picker/general-time-picker.editor.module.css
- bricks/forms/src/editor-bricks/general-time-picker/general-time-picker.editor.tsx
- bricks/forms/src/editor-bricks/shared/style/base-form-item.module.css
> fix(): fix style

- bricks/basic-bricks/src/editor-bricks/general-modal/general-modal.editor.module.css
> fix(): modify style

- bricks/presentational-bricks/src/brick-tag/BrickTag.spec.tsx
- bricks/presentational-bricks/src/brick-tag/BrickTag.tsx
- bricks/presentational-bricks/src/brick-tag/index.module.css
- bricks/presentational-bricks/src/brick-tag/index.tsx
- bricks/presentational-bricks/stories/chapters/brick-tag.ts
Closes BRICK_STORE-2046
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-tag): 增加tag close event

- bricks/presentational-bricks/src/brick-tree/BrickTree.spec.tsx
- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
Closes VIEW-329
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-tree): 默认选中项改变时，全选状态对应改变

- bricks/forms/src/custom-templates/tpl-cmdb-object-attr-add.ts
> chore(forms): add test id

- bricks/next-builder/package.json
- bricks/next-builder/src/builder-container/BuilderContainer.module.css
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.module.css
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeNode/StoryboardTreeNode.module.css
- bricks/next-builder/src/builder-container/StoryboardTreeNode/StoryboardTreeNode.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.module.css
- yarn.lock
> feat(builder): support resizing toolbox column

- bricks/basic-bricks/src/app-bar/DesktopSlider/DesktopSlider.tsx
Refs LAUNCHPAD-59
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 恢复记忆上次 launchpad 打开tab

- bricks/presentational-bricks/src/brick-table/index.tsx
> docs(): refine doc

- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/utils/findQueryInNode.ts
- bricks/next-builder/src/builder-container/utils/utils.spec.ts
- bricks/next-builder/src/builder-container/utils/utils.ts
- bricks/next-builder/src/i18n/locales/en.ts
- bricks/next-builder/src/i18n/locales/zh.ts
refs NEXT_BUILDER-742
请勾选以下两组选项其中之一：
或者：
>
>
> feat(data-view): find data by configuration

- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.module.css
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/i18n/locales/zh.ts
> fix(builder): keep cursor status when dragging resizer

- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.module.css
Refs LAUNCHPAD-61
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): modify favorite count

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/DataView/ContextItem.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItem.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemFormModal.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.spec.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/utils/findQueryInNode.ts
- bricks/next-builder/src/builder-container/utils/utils.spec.ts
- bricks/next-builder/src/builder-container/utils/utils.ts
refs NEXT_BUILDER-742
请勾选以下两组选项其中之一：
或者：
>
>
> feat(data-view): higtlight matching nodes when context is hovering

- bricks/forms/src/general-textarea/GeneralTextArea.tsx
- bricks/forms/src/general-textarea/index.tsx
Closes BRICK_STORE-2048
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-textarea): add property inputBoxStyle

- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.tsx
- bricks/forms/stories/chapters/general-radio.ts
refs BRICK_STORE-2053
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-radio): size

- bricks/presentational-bricks/src/brick-tag/BrickTag.spec.tsx
- bricks/presentational-bricks/src/brick-tag/BrickTag.tsx
- bricks/presentational-bricks/src/brick-tag/index.tsx
refs BRICK_STORE-2052
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-tag): cancelable

- bricks/developers/src/stories/docs/cmdb-instances/instance-change-history-template.md
- bricks/developers/src/stories/docs/cmdb-instances/instance-change-history.md
> docs(cmdb-instances): update doc

- bricks/brick-visualization/package.json
- bricks/forms/package.json
- bricks/forms/src/icon-select/IconSelect.tsx
- bricks/forms/src/icon-select/index.tsx
- bricks/presentational-bricks/package.json
- yarn.lock
refs BRICK_STORE-1990
请勾选以下两组选项其中之一：
或者：
>
>
> feat(icon-select): defaultColor

- bricks/presentational-bricks/package.json
- yarn.lock
> chore(deps): Update @next-core/custom-antd-styles

- bricks/presentational-bricks/src/editor-bricks/brick-table/brick-table.editor.spec.tsx
- bricks/presentational-bricks/src/editor-bricks/brick-table/brick-table.editor.tsx
> fix(editors): smart display for column titles of brick-table

- bricks/developers/src/stories/docs/graph/general-graph.md
refs BRICK_STORE-2050
请勾选以下两组选项其中之一：
或者：
>
>
> docs(graph): disableWheel & graphMaxHeight

- .size-limit.js
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.module.css
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.spec.tsx
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.tsx
- bricks/basic-bricks/src/app-bar/site-map/SiteMap.module.css
- bricks/basic-bricks/src/app-bar/site-map/SiteMap.spec.tsx
- bricks/basic-bricks/src/app-bar/site-map/SiteMap.tsx
- bricks/basic-bricks/src/app-bar/site-map/mockData.ts
Refs LAUNCHPAD-58
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine sitemap

- bricks/forms/src/dynamic-user-select-item/DynamicUserSelectItem.tsx
refs EVENT-314
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 选择关联资源负责人，出现多个相同的选项

- bricks/next-builder/src/builder-container/BuilderContainer.module.css
- bricks/next-builder/src/builder-container/BuilderContainer.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
> fix(builder): click overlay to exit fullscreen

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
refs MONITOR-1710
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): cmdb-instance-select初始化赋值，拉取数据不对

- bricks/presentational-bricks/src/card-item/index.shadow.less
- bricks/presentational-bricks/src/info-display-card-list/InfoDisplayCardList.tsx
- bricks/presentational-bricks/src/info-display-card-list/index.module.css
Closes FLOW-281
请勾选以下两组选项其中之一：
或者：
>
>
> fix(InfoDisplayCardList): InfoDisplayCardList css bug fix

- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraph.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraphComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamNodeComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamTitle.module.css
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamTitle.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/buildBrickEventDownstreamTree.ts
- bricks/next-builder/src/builder-container/EventStreamCanvas/buildBrickEventUpstreamTree.ts
- bricks/next-builder/src/builder-container/EventStreamCanvas/interfaces.ts
- bricks/next-builder/src/builder-container/index.spec.tsx
- bricks/next-builder/src/builder-container/index.tsx
refs NEXT_BUILDER-729
请勾选以下两组选项其中之一：
或者：
>
>
> feat(event-stream-canvas): onEventNodeClick

- bricks/presentational-bricks/src/info-display-card-list/InfoDisplayCardList.tsx
- bricks/presentational-bricks/src/info-display-card-list/index.module.css
>  chore(InfoDisplayCardList): InfoDisplayCardList optimization

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
> fix(brick-table): 修复黑暗模式表格斑马纹

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
Closes DESKTOP-225
请勾选以下两组选项其中之一：
或者：
>
>
> fix(AppBar): update accountEntry appId

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
refs INSTANCE-1577
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 结构项enums类型没有枚举值项

- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.spec.tsx
- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
- bricks/basic-bricks/src/general-custom-buttons/index.tsx
- bricks/basic-bricks/stories/chapters/general-card.ts
- bricks/basic-bricks/stories/chapters/general-custom-buttons.ts
Closes BRICK_STORE-2056
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-custom-buttons): 支持设置更多按钮为link类型

- bricks/presentational-bricks/src/collapsible-card-item/CollapsibleCardItem.spec.tsx
- bricks/presentational-bricks/src/collapsible-card-item/CollapsibleCardItem.tsx
- bricks/presentational-bricks/src/collapsible-card-item/__snapshots__/CollapsibleCardItem.spec.tsx.snap
- bricks/presentational-bricks/src/collapsible-card-item/index.shadow.css
- bricks/presentational-bricks/src/collapsible-card-item/index.spec.ts
- bricks/presentational-bricks/src/collapsible-card-item/index.tsx
Closes FLOW-295
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): collapsible-card-item新增`hoverable`,`cardStyle`property

- bricks/basic-bricks/src/sub-menu-filter/index.module.css
Closes FLOW-284
请勾选以下两组选项其中之一：
或者：
>
>
> fix(SubMenuFilter): SubMenuFilter adaptive height

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
Reverts easyops-cn/next-basics#122
> Revert "feat(basic-bricks): subMenuFilter 支持treeMode"

- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/brick-tag/index.module.css
- bricks/presentational-bricks/src/brick-value-mapping/style.module.css
- yarn.lock
> fix(tag): style fix

- bricks/forms/src/upload-files-v2/UploadFilesV2.module.css
- bricks/forms/src/upload-files-v2/UploadFilesV2.spec.tsx
- bricks/forms/src/upload-files-v2/UploadFilesV2.tsx
- bricks/forms/src/upload-files-v2/index.tsx
> feat(upload-files-v2): add property `hideDragBtnWhenAchieveMax`

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
Refs NIL-0
请勾选以下两组选项其中之一：
或者：
>
>
> feat(sso): handle sso logout

- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/DataView/utils.spec.ts
- bricks/next-builder/src/builder-container/DataView/utils.ts
refs NEXT_BUILDER-761
请勾选以下两组选项其中之一：
或者：
>
>
> feat(context): Compatible legacy data with provider selector

- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamTitle.tsx
refs NEXT_BUILDER-762
请勾选以下两组选项其中之一：
或者：
>
>
> feat(event-stream-title): handle click when type is root

- bricks/brick-visualization/package.json
- bricks/forms/package.json
- bricks/presentational-bricks/package.json
- yarn.lock
refs BRICK_STORE-1990
请勾选以下两组选项其中之一：
或者：
>
>
> fix(icon-select): reset color when defaultColor changes

- bricks/developers/src/stories/docs/code-bricks/code-display.md
refs BRICK_STORE-2058
请勾选以下两组选项其中之一：
或者：
>
>
> docs(): code-display

- bricks/basic-bricks/src/sub-menu-filter/index.module.css
- bricks/basic-bricks/src/sub-menu/index.module.css
BRICK_STORE-2059
请勾选以下两组选项其中之一：
或者：
>
>
> fix(sub-menu): fix style of sub-menu

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
Closes BRICK_STORE-2062
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): ObjectAttrStruct  regex bug fix

- bricks/forms/src/cmdb-object-attr-value/CmdbObjectAttrValue.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/CmdbObjectAttrValue.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrEnum.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
refs INSTANCE-1629
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): cmdb-object-attr-value枚举值输入方式改变&resetFields不生效

- bricks/basic-bricks/src/app-bar/DesktopSlider/DesktopSlider.tsx
- bricks/basic-bricks/src/app-bar/FavoriteDesktopCell/FavoriteDesktopCell.module.css
- bricks/basic-bricks/src/app-bar/LaunchpadService.spec.ts
- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.module.css
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.spec.tsx
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.tsx
- bricks/basic-bricks/src/app-bar/site-map/SiteMap.spec.tsx
- bricks/basic-bricks/src/app-bar/site-map/SiteMap.tsx
Refs DESKTOP-231
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): filter empty category and push visitor by sitemap

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/app-bar/FavoriteDesktopCell/FavoriteDesktopCell.module.css
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.module.css
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.spec.tsx
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.tsx
Refs LAUNCHPAD-56
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): style refine

- .size-limit.js
- bricks/next-builder/package.json
- bricks/next-builder/src/data-providers/ScanBricksAndTemplates.spec.ts
- bricks/next-builder/src/data-providers/ScanBricksAndTemplates.ts
> feat(): get depending contracts by provider bricks

- bricks/presentational-bricks/src/brick-general-search/BrickGeneralSearch.spec.tsx
- bricks/presentational-bricks/src/brick-general-search/BrickGeneralSearch.tsx
- bricks/presentational-bricks/src/brick-general-search/index.tsx
- bricks/presentational-bricks/stories/chapters/brick-table.ts
refs BRICK_STORE-1657
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-general-search): debounceTime & query.change.v2

- bricks/basic-bricks/src/app-bar/LaunchpadButton/LaunchpadButton.tsx
Refs LAUNCHPAD-56
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): launchpad support hot-key

- bricks/brick-visualization/package.json
- bricks/forms/package.json
- bricks/presentational-bricks/package.json
- yarn.lock
refs BRICK_STORE-1990
请勾选以下两组选项其中之一：
或者：
>
>
> fix(icon-select): set color when props.value changes

- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.module.css
- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.spec.tsx
- bricks/basic-bricks/src/app-bar/DesktopApp/DesktopApp.tsx
- bricks/basic-bricks/src/app-bar/DesktopCell/DesktopCell.module.css
- bricks/basic-bricks/src/app-bar/DesktopCell/DesktopCell.tsx
- bricks/basic-bricks/src/app-bar/DesktopCustom/DesktopCustom.module.css
- bricks/basic-bricks/src/app-bar/MyDesktop/MyDesktop.module.css
Refs LAUNCHPAD-51
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): myDesktop style optimization

- bricks/presentational-bricks/src/brick-tree/BrickTree.spec.tsx
- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.module.css
Closes BRICK_STORE-2067
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-tree): 搜索大小写不敏感

- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.module.css
- bricks/presentational-bricks/src/images/card-bg-bottom-left.svg
- bricks/presentational-bricks/src/images/card-bg-bottom-right.svg
- bricks/presentational-bricks/src/images/card-bg-top-left.svg
- bricks/presentational-bricks/src/images/card-bg-top-right.svg
- bricks/presentational-bricks/src/info-display-card-list/index.module.css
Closes BRICK_STORE-2067
请勾选以下两组选项其中之一：
或者：
>
>
> style(card-item): 适配黑暗模式

- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
Refs LAUNCHPAD-56
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): get apps includes internal

- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- yarn.lock
> feat(): 兼容esb定制化登录

- bricks/developers/src/provider-provider-doc/processors.ts
- bricks/developers/src/provider-provider-doc/ucpro.mock.ts
> fix(provider-doc): fix provider doc after migrated sdk usage

- bricks/basic-bricks/package.json
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- bricks/basic-bricks/src/app-bar/License-notification/LicenseInfo.module.css
- bricks/basic-bricks/src/app-bar/License-notification/LicenseNotification.spec.tsx
- bricks/basic-bricks/src/app-bar/License-notification/LicenseNotification.tsx
- yarn.lock
Refs USER_ADMIN-125
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support license info

- bricks/basic-bricks/src/app-bar/LaunchpadService.spec.ts
- bricks/basic-bricks/src/app-bar/LaunchpadService.ts
- bricks/forms/src/cmdb-instance-select-panel/CmdbInstanceSelectPanelWrapper.spec.tsx
- bricks/forms/src/dynamic-user-select-item/DynamicUserSelectItem.spec.tsx
- bricks/forms/src/inform-methods-form/InformMethodsForm.spec.tsx
- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/presentational-bricks/src/markdown-editor/MarkdownEditor.spec.tsx
> test(): fix sdk usage in tests

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrBool.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrBool.tsx
refs BRICK_STORE-2074
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): cmdb属性构件,应该传出布尔值而不是字符串的true/false

- bricks/basic-bricks/package.json
- bricks/basic-bricks/src/app-bar/License-notification/LicenseNotification.spec.tsx
- bricks/basic-bricks/src/app-bar/License-notification/LicenseNotification.tsx
- yarn.lock
Refs USER_ADMIN-125
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): handle delay api

- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.module.css
- bricks/next-builder/src/builder-container/BrickLibrary/BrickLibrary.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/EventsView/EventsView.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.tsx
- bricks/next-builder/src/builder-container/shared.module.css
> fix(): refine scrollbar style

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/DataView/utils.ts
> feat(): support conditional context

- bricks/basic-bricks/package.json
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.module.css
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- bricks/basic-bricks/src/i18n/constants.ts
- bricks/basic-bricks/src/i18n/locales/en.ts
- bricks/basic-bricks/src/i18n/locales/zh.ts
- yarn.lock
Closes INSTANCE-1668
请勾选以下两组选项其中之一：
或者：
>
>
> feat(app-bar): add switch lang btn

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
> chore(app-bar): change icon

- bricks/forms/src/tree-select/TreeSelect.tsx
- bricks/forms/src/tree-select/index.tsx
Closes TOOL-794
请勾选以下两组选项其中之一：
或者：
>
>
> feat(treeSelect): treeSelect support defaultExpandedKeys

- bricks/basic-bricks/package.json
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- yarn.lock
Refs USER_ADMIN-125
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine liscense info

- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
- bricks/basic-bricks/src/general-custom-buttons/index.tsx
- bricks/basic-bricks/stories/chapters/general-custom-buttons.ts
> feat(general-custom-buttons): add test id support

- bricks/developers/src/stories/chapters/atom-bricks/other/index.ts
- bricks/developers/src/stories/chapters/atom-bricks/other/no-op.ts
- bricks/developers/src/stories/docs/basic-providers/no-op.md
> feat(): add docs about provider-no-op

- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.spec.tsx
- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.tsx
- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdown.tsx
> fix(): refine visual builder and add tests

- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamCanvas.spec.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamCanvas.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraph.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraphComponent.spec.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraphComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamHandler.spec.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamHandler.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamNodeComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamTitle.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/__mocks__/EventStreamGraph.tsx
> test(): add tests for events view

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- bricks/basic-bricks/src/i18n/constants.ts
- bricks/basic-bricks/src/i18n/locales/en.ts
- bricks/basic-bricks/src/i18n/locales/zh.ts
> fix(app-bar): 切换语言文字修改

- bricks/presentational-bricks/src/card-item/index.shadow.less
> fix(card-item): fix disabled style

- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraph.spec.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraph.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamGraphComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamNodeComponent.spec.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamNodeComponent.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamTitle.spec.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/EventStreamTitle.tsx
- bricks/next-builder/src/builder-container/EventStreamCanvas/buildBrickEventDownstreamTree.spec.ts
> test(): add tests for event graph

- bricks/basic-bricks/src/sub-menu/index.module.css
> fix(sub-menu): 修复item项宽度大了1px

- bricks/basic-bricks/src/general-modal/GeneralModal.tsx
- bricks/basic-bricks/src/i18n/constants.ts
- bricks/basic-bricks/src/i18n/locales/en.ts
- bricks/basic-bricks/src/i18n/locales/zh.ts
Closes INSTANCE-1698
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-modal): add i18n

- bricks/basic-bricks/src/editor-bricks/micro-view/micro-view.editor.module.css
- bricks/basic-bricks/src/editor-bricks/micro-view/micro-view.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/micro-view/micro-view.editor.tsx
> fix(editor): support minor slots

- bricks/presentational-bricks/stories/chapters/brick-table.ts
> chore(brick-table): add demo message

- bricks/forms/src/custom-templates/tpl-cmdb-object-attr-add.ts
refs BRICK_STORE-2092
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): attribute ID rule

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- bricks/basic-bricks/src/i18n/constants.ts
- bricks/basic-bricks/src/i18n/locales/en.ts
- bricks/basic-bricks/src/i18n/locales/zh.ts
refs INSTANCE-1719
请勾选以下两组选项其中之一：
或者：
>
>
> fix(basic-bricks): add switch-language btn tooltip

- bricks/forms/src/form-modal/FormModal.spec.tsx
- bricks/forms/src/form-modal/FormModal.tsx
- bricks/forms/src/general-modal/GeneralModal.tsx
- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.tsx
> fix(forms,presentational-bricks): 修改表单模态框中取消按钮样式

- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
- bricks/basic-bricks/src/general-custom-buttons/index.module.css
修复设置buttonUrl&disabled时没有tooltip && 修复disabeld时hover有底色 && 修复没设置buttonUrl时tooltip位置不对
Closes BRICK_STORE-2095
请勾选以下两组选项其中之一：
或者：
>
>
antd默认样式menu-item > a 会有margin&padding导致没有设置buttonUrl时tooltip位置不一致。同时在disabeld时拥有pointer-events: none导致tooltip不显示。
用div隔开，赋予div相同的margin&padding让tooltip位置一致，禁用效果改由里面的Link决定。
> fix(general-custom-buttons):  修复按钮组tooltip相关问题

- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
- bricks/basic-bricks/src/general-custom-buttons/index.module.css
refs BRICK_STORE-2104
请勾选以下两组选项其中之一：
或者：
>
>
> fix(basic-bricks): general-custom-buttons disabled style

- bricks/forms/stories/chapters/general-form.ts
- bricks/presentational-bricks/stories/chapters/general-tooltip.ts
> chore(forms,presentational-bricks): demo更改

- bricks/presentational-bricks/src/brick-table/index.tsx
- bricks/presentational-bricks/src/custom-processors/flattenTreeDataListAndCalcRowSpan.spec.ts
- bricks/presentational-bricks/src/custom-processors/flattenTreeDataListAndCalcRowSpan.ts
- bricks/presentational-bricks/src/index.spec.ts
- bricks/presentational-bricks/src/index.ts
- bricks/presentational-bricks/stories/chapters/brick-table.ts
Closes BRICK_STORE-2105
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add flattenTreeDataListAndCalcRowSpan custom processor

- bricks/forms/package.json
- yarn.lock
> chore(deps): Update @next-libs/forms

- bricks/basic-bricks/src/popover-container/PopoverContainer.module.css
> fix(popover-container): fix vertically centered style

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/popover-container/PopoverContainer.tsx
> fix(): fix target ref for use brick in portal

- bricks/forms/src/dynamic-form-item/DynamicFormItem.spec.tsx
- bricks/forms/src/dynamic-form-item/DynamicFormItem.tsx
- bricks/forms/src/dynamic-form-item/index.tsx
…RICK_STORE-2076
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): dynamic-form-item brick support remote search for users Closes BRICK_STORE-1729

- bricks/basic-bricks/src/general-button/GeneralButton.tsx
- bricks/basic-bricks/stories/chapters/general-button.ts
- bricks/forms/src/general-buttons/GeneralButtons.tsx
- bricks/forms/src/general-switch/GeneralSwitch.tsx
- bricks/forms/stories/chapters/form-modal.ts
- bricks/forms/stories/chapters/general-buttons.ts
- bricks/forms/stories/chapters/general-switch.ts
- bricks/forms/stories/chapters/general-textarea.ts
- bricks/presentational-bricks/stories/chapters/brick-input.ts
> chore(): add test id

- bricks/general-auth/deploy-default/package.conf.yaml
- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- yarn.lock
Refs INFRA-1052 INFRA-1051
请勾选以下两组选项其中之一：
或者：
>
>
> feat(loginv2): support login by easyops, ldap or custom provider

- bricks/forms/src/user-or-user-group-select/UserOrUserGroupSelect.spec.tsx
- bricks/forms/src/user-or-user-group-select/UserOrUserGroupSelect.tsx
- bricks/forms/src/user-or-user-group-select/index.tsx
refs INSTANCE-1716
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms): add userGroupQuery and userQuery properties

- bricks/forms/package.json
- yarn.lock
> chore(): update next-core/custom-antd-styles:1.8.8

- bricks/presentational-bricks/src/brick-tree/BrickTree.spec.tsx
- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.module.css
- bricks/presentational-bricks/src/brick-tree/index.tsx
> feat(): 添加属性控制brick-tree的全部及默认的显示样式 Closed TOOL-832

- bricks/forms/src/form-modal/FormModal.spec.tsx
- bricks/forms/src/form-modal/FormModal.tsx
- bricks/forms/src/form-modal/index.tsx
Refs BRICK_STORE-2109
请勾选以下两组选项其中之一：
或者：
>
>
> feat(form-modal): add test id to modal content element

- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
> fix(): brick-tree问题调整 Closed TOOL-832

- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- yarn.lock
> feat(): 新增验证用户是否设置了双因子规则接口

- bricks/basic-bricks/src/popover-container/PopoverContainer.tsx
Closes BRICK_STORE-2124
请勾选以下两组选项其中之一：
或者：
>
>
> fix(popover-container): fix popover brick ref

- bricks/presentational-bricks/stories/chapters/general-image.ts
> chore(): refine icon

- bricks/basic-bricks/src/editor-bricks/index.ts
- bricks/basic-bricks/src/editor-bricks/multiple-columns-card/multiple-columns-card.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/multiple-columns-card/multiple-columns-card.editor.tsx
Refs NEXT_BUILDER-819
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): multiple-columns-card editor

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.module.css
Closes BRICK_STORE-2049
请勾选以下两组选项其中之一：
或者：
>
>
> fix(sub-menu-filter): 过长文字省略用...显示

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.spec.tsx
- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.module.css
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
Closes BRICK_STORE-2049
请勾选以下两组选项其中之一：
或者：
>
>
> feat(sub-menu-filter): 样式修改&新增属性inlineIndent

- bricks/basic-bricks/src/sub-menu-filter/index.module.css
Closes BRICK_STORE-2049
请勾选以下两组选项其中之一：
或者：
>
>
> chore(sub-menu-filter): fix style

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.spec.tsx
- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
Closes BRICK_STORE-2134
请勾选以下两组选项其中之一：
或者：
>
>
> feat(sub-menu-filter): add event subMenu.click

- .size-limit.js
- bricks/basic-bricks/src/editor-bricks/general-custom-buttons/general-custom-buttons.editor.module.css
- bricks/basic-bricks/src/editor-bricks/general-custom-buttons/general-custom-buttons.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/general-custom-buttons/general-custom-buttons.editor.tsx
- bricks/basic-bricks/src/editor-bricks/index.ts
- bricks/basic-bricks/src/editor-bricks/shared/intefaces.ts
Refs NEXT_BUILDER-822
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add custom button editor

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.spec.tsx
- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.module.css
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
Closes BRICK_STORE-2135
请勾选以下两组选项其中之一：
或者：
>
>
https://lanhuapp.com/web/#/item/project/detailDetach?pid=49f05f72-6e7b-489c-b95f-4450e7de4736&project_id=49f05f72-6e7b-489c-b95f-4450e7de4736&image_id=db3a40ca-4e95-4b1c-9a23-f16918cec3bf&fromEditor=true
> feat(sub-menu-filter): 增加transparentBackground样式

- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
> fix(brick-tree): 修复搜索时节点不展开

- bricks/basic-bricks/src/sub-menu-filter/index.module.css
Closes BRICK_STORE-2135
请勾选以下两组选项其中之一：
或者：
>
>
> chore(sub-menu-filter): transparentBackground样式更改

- bricks/presentational-bricks/src/brick-table/index.tsx
Closes MONITOR-1798
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-table): change scrollConfigs default value to { x: true }

- bricks/forms/src/general-modal/GeneralModal.tsx
refs INSTANCE-1773
请勾选以下两组选项其中之一：
- [ 1] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。
或者：
>
>
- [ 1] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
> feat(forms): add i18n

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.spec.tsx
- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
Reverts easyops-cn/next-basics#377
> Revert "feat(sub-menu-filter): add event subMenu.click"

- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.spec.tsx
- bricks/basic-bricks/src/sub-menu-filter/SubMenuFilter.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.module.css
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
Closes BRICK_STORE-2135
请勾选以下两组选项其中之一：
或者：
>
>
> feat(sub-menu-filter): 增加属性accordion

- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/AdvancedBrickLibrary.spec.tsx
- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/AdvancedBrickLibrary.tsx
- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/filterBrick.spec.ts
- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/filterBrick.ts
Refs NEXT_BUILDER-818
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 在模板视图中添加构件时去除掉自身

- package.json
- yarn.lock
Reverts easyops-cn/next-basics#387
> Revert "chore(deps): Update dependency @next-core/dev-dependencies to ^1.8.17"

- bricks/basic-bricks/src/menu-bar/AppSubMenu/AppSubMenu.tsx
- bricks/basic-bricks/src/menu-bar/MenuBar/MenuBar.tsx
> chore(menu-bar): add testid

- bricks/basic-bricks/src/general-drawer/GeneralDrawer.spec.tsx
- bricks/basic-bricks/src/general-drawer/GeneralDrawer.tsx
- bricks/basic-bricks/src/general-drawer/index.shadow.less
- bricks/basic-bricks/src/general-drawer/index.tsx
Closes BRICK_STORE-2120
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): general-drawer add loading props

- bricks/presentational-bricks/src/editor-bricks/brick-link/brick-link.editor.module.css
- bricks/presentational-bricks/src/editor-bricks/brick-link/brick-link.editor.spec.tsx
- bricks/presentational-bricks/src/editor-bricks/brick-link/brick-link.editor.tsx
- bricks/presentational-bricks/src/editor-bricks/index.ts
- bricks/shared-editors/src/editor-bricks/general-chart/general-chart.editor.module.css
- bricks/shared-editors/src/editor-bricks/general-chart/general-chart.editor.spec.tsx
- bricks/shared-editors/src/editor-bricks/general-chart/general-chart.editor.tsx
- bricks/shared-editors/src/editor-bricks/general-code/general-code.editor.module.css
- bricks/shared-editors/src/editor-bricks/general-code/general-code.editor.spec.tsx
- bricks/shared-editors/src/editor-bricks/general-code/general-code.editor.tsx
- bricks/shared-editors/src/editor-bricks/index.ts
Refs NEXT_BUILDER-740
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add brick ui editor

- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/card-item/CardItem.tsx
- bricks/presentational-bricks/src/card-item/index.shadow.less
- bricks/presentational-bricks/src/card-item/index.tsx
- yarn.lock
Closes BRICK_STORE-2136
请勾选以下两组选项其中之一：
或者：
>
>
> feat(card-item): 透传shape属性

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvasTabs.module.css
- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvasTabs.spec.tsx
- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvasTabs.tsx
> fix(): highlight in canvas tabs

- bricks/basic-bricks/src/menu-bar/index.tsx
- bricks/basic-bricks/src/sub-menu-filter/index.tsx
- bricks/basic-bricks/src/sub-menu/index.tsx
- bricks/shared-editors/src/editor-bricks/general-menu/general-menu.editor.module.css
- bricks/shared-editors/src/editor-bricks/general-menu/general-menu.editor.spec.tsx
- bricks/shared-editors/src/editor-bricks/general-menu/general-menu.editor.tsx
- bricks/shared-editors/src/editor-bricks/index.ts
Refs NEXT_BUILDER-740
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add brick edtior

- bricks/basic-bricks/src/general-timer/index.tsx
Closes FLOW-400
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-timer): timer suppert stop and reStart

- bricks/basic-bricks/src/general-timer/index.tsx
> chore(): update doc

- bricks/developers/src/stories/docs/cmdb-instances/instance-list.md
> docs(): doc Closed BRICK_STORE-2143

- bricks/general-auth/src/shared/resetLegacyIframe.ts
- bricks/presentational-bricks/src/general-pagination/GeneralPagination.spec.tsx
- bricks/presentational-bricks/src/general-pagination/GeneralPagination.tsx
- bricks/presentational-bricks/src/general-pagination/__snapshots__/GeneralPagination.spec.tsx.snap
- bricks/presentational-bricks/src/general-pagination/index.spec.ts
- bricks/presentational-bricks/src/general-pagination/index.tsx
Closes BRICK_STORE-2145
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-pagination): 修复改变pagesize后两个事件同时触发

- .size-limit.js
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.spec.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.tsx
Closes BRICK_STORE-2137
请勾选以下两组选项其中之一：
或者：
>
>
> feat(builder-container): 支持搜索路由的path

- bricks/forms/src/editor-bricks/index.ts
- bricks/forms/src/editor-bricks/input-with-unit/input-with-unit.editor.module.css
- bricks/forms/src/editor-bricks/input-with-unit/input-with-unit.editor.spec.tsx
- bricks/forms/src/editor-bricks/input-with-unit/input-with-unit.editor.tsx
- bricks/forms/src/editor-bricks/time-range-picker/time-range-picker.editor.module.css
- bricks/forms/src/editor-bricks/time-range-picker/time-range-picker.editor.spec.tsx
- bricks/forms/src/editor-bricks/time-range-picker/time-range-picker.editor.tsx
- bricks/forms/src/form-modal/index.tsx
- bricks/forms/src/user-or-user-group-select/index.tsx
- bricks/presentational-bricks/src/brick-general-search/index.tsx
- bricks/presentational-bricks/src/log-display/index.tsx
- bricks/presentational-bricks/src/markdown-display/index.tsx
- bricks/presentational-bricks/src/markdown-editor/index.tsx
- bricks/shared-editors/src/editor-bricks/general-search/general-search.editor.module.css
- bricks/shared-editors/src/editor-bricks/general-search/general-search.editor.spec.tsx
- bricks/shared-editors/src/editor-bricks/general-search/general-search.editor.tsx
- bricks/shared-editors/src/editor-bricks/index.ts
Refs NEXT_BUILDER-837
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add brick editor

- bricks/shared-editors/src/editor-bricks/general-card/general-card.editor.module.css
- bricks/shared-editors/src/editor-bricks/general-card/general-card.editor.spec.tsx
- bricks/shared-editors/src/editor-bricks/general-card/general-card.editor.tsx
- bricks/shared-editors/src/editor-bricks/general-chart/general-chart.editor.tsx
- bricks/shared-editors/src/editor-bricks/general-code/general-code.editor.tsx
- bricks/shared-editors/src/editor-bricks/general-menu/general-menu.editor.tsx
- bricks/shared-editors/src/editor-bricks/index.ts
Refs NEXT_BUILDER-837
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add general card editor

- bricks/shared-editors/src/editor-bricks/general-card/general-card.editor.tsx
> chore(): remove unused code

- bricks/basic-bricks/src/editor-bricks/easy-view/easy-view.editor.module.css
- bricks/basic-bricks/src/editor-bricks/easy-view/easy-view.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/easy-view/easy-view.editor.tsx
> fix(easy-view--editor): set min-height to 100%

- bricks/shared-editors/src/editor-bricks/general-chart/general-chart.editor.tsx
Refs NEXT_BUILDER-740
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): remove unused code

- bricks/basic-bricks/src/editor-bricks/easy-view/easy-view.editor.module.css
- bricks/basic-bricks/src/editor-bricks/easy-view/easy-view.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/easy-view/easy-view.editor.tsx
> fix(easy-view--editor): show area id in background

- .gitignore
- bricks/basic-bricks/package.json
- bricks/basic-bricks/rollup.snippets.js
- bricks/basic-bricks/snippets/easy-view.ts
- bricks/basic-bricks/snippets/general-button.ts
- bricks/basic-bricks/snippets/index.ts
- bricks/basic-bricks/snippets/thumbnails/easy-view.1x2.svg
- bricks/basic-bricks/snippets/thumbnails/easy-view.2x3.svg
- bricks/basic-bricks/snippets/thumbnails/easy-view.classic.svg
- bricks/basic-bricks/snippets/thumbnails/general-button.default.svg
- bricks/basic-bricks/snippets/thumbnails/general-button.primary.svg
- bricks/basic-bricks/src/easy-view/EasyView.shadow.css
- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.module.css
- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.spec.tsx
- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.tsx
> feat(): add snippets of easy-view and general-button

- bricks/basic-bricks/src/editor-bricks/general-custom-buttons/general-custom-buttons.editor.module.css
- bricks/basic-bricks/src/editor-bricks/general-custom-buttons/general-custom-buttons.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/general-custom-buttons/general-custom-buttons.editor.tsx
Refs NEXT_BUILDER-822
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): custom button editor style

- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
> feat(): fetch snippets by flags

- bricks/forms/src/editor-bricks/general-form-item/general-form-item.editor.module.css
- bricks/forms/src/editor-bricks/general-form-item/general-form-item.editor.spec.tsx
- bricks/forms/src/editor-bricks/general-form-item/general-form-item.editor.tsx
- bricks/forms/src/editor-bricks/general-form/general-form.editor.tsx
- bricks/forms/src/editor-bricks/index.ts
- bricks/presentational-bricks/src/brick-input/index.tsx
- bricks/presentational-bricks/src/brick-tag/index.tsx
- bricks/presentational-bricks/src/brick-value-mapping/index.tsx
- bricks/presentational-bricks/src/editor-bricks/brick-alert/brick-alert.editor.module.css
- bricks/presentational-bricks/src/editor-bricks/brick-alert/brick-alert.editor.spec.tsx
- bricks/presentational-bricks/src/editor-bricks/brick-alert/brick-alert.editor.tsx
- bricks/presentational-bricks/src/editor-bricks/brick-descriptions/brick-descriptions.editor.module.css
- bricks/presentational-bricks/src/editor-bricks/brick-descriptions/brick-descriptions.editor.spec.tsx
- bricks/presentational-bricks/src/editor-bricks/brick-descriptions/brick-descriptions.editor.tsx
- bricks/presentational-bricks/src/editor-bricks/brick-result/brick-result.editor.module.css
- bricks/presentational-bricks/src/editor-bricks/brick-result/brick-result.editor.spec.tsx
- bricks/presentational-bricks/src/editor-bricks/brick-result/brick-result.editor.tsx
- bricks/presentational-bricks/src/editor-bricks/index.ts
- bricks/shared-editors/src/editor-bricks/general-tag/general-tag.editor.module.css
- bricks/shared-editors/src/editor-bricks/general-tag/general-tag.editor.spec.tsx
- bricks/shared-editors/src/editor-bricks/general-tag/general-tag.editor.tsx
- bricks/shared-editors/src/editor-bricks/index.ts
Refs  NEXT_BUILDER-740
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add tag editor

- bricks/flow-builder/src/custom-processors/getFlowConfigDagre.ts
refs FLOW_BUILDER-11
请勾选以下两组选项其中之一：
或者：
>
>
> fix(flow-builder): 修复getFlowConfigDagre会修改入参值的问题

- bricks/forms/src/upload-files-v2/UploadFilesV2.spec.tsx
- bricks/forms/src/upload-files-v2/UploadFilesV2.tsx
- bricks/forms/src/upload-files-v2/index.tsx
- bricks/forms/src/upload-files/UploadFiles.spec.tsx
- bricks/forms/src/upload-files/UploadFiles.tsx
- bricks/forms/src/upload-files/index.spec.ts
- bricks/forms/src/upload-files/index.tsx
- bricks/forms/src/upload-img/UploadImg.spec.tsx
- bricks/forms/src/upload-img/UploadImg.tsx
- bricks/forms/src/upload-img/index.tsx
- bricks/forms/src/utils.spec.ts
- bricks/forms/src/utils.ts
请勾选以下两组选项其中之一：
或者：
>
>
- 文件上传功能添加 limitSize 入参, 作为限制文件上传大小的字段.
- 在utils文件中新增 FileUtils 类, 并对外暴露 sizeCompare 方法用以比较文件大小
- 对新增FileUtils方法进行单元用例测试编写
- 修改文件上传构建, 涉及到 UploadFiles, UploadFilesV2, UploadImg三个构建, 并对UploadFilesV2构建的单元测试进行了补充
> feat(): upload add file size limit

- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.module.css
Refs CD-1999
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-tree): fix suffixBrick style

- bricks/forms/src/time-range-picker/TimeRangePicker.spec.tsx
- bricks/forms/src/time-range-picker/TimeRangePicker.tsx
Fixes BRICK_STORE-2159
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): when time-range-picker value is null, component get invalid date

- bricks/basic-bricks/src/general-button/GeneralButton.tsx
- bricks/basic-bricks/src/general-button/index.tsx
- bricks/forms/src/general-buttons/GeneralButtons.tsx
- bricks/forms/src/general-buttons/index.tsx
Fixes BRICK_STORE-2161
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): button add loading state

- bricks/forms/src/upload-files-v2/UploadFilesV2.spec.tsx
- bricks/forms/src/upload-files-v2/UploadFilesV2.tsx
- bricks/forms/src/upload-files/UploadFiles.spec.tsx
- bricks/forms/src/upload-files/UploadFiles.tsx
Refs: BRICK_STORE-2079
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix autoUpload fail in upload component

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/index.spec.tsx
- bricks/next-builder/src/data-providers/AddStoryboardNodeAndReorder.spec.ts
- bricks/next-builder/src/data-providers/AddStoryboardNodeAndReorder.ts
- bricks/next-builder/src/data-providers/ApplyStoryboardSnippet.spec.ts
- bricks/next-builder/src/data-providers/ApplyStoryboardSnippet.ts
> fix(builder): no longer need to pass nodeAlias

- bricks/basic-bricks/snippets/easy-view.ts
- bricks/basic-bricks/snippets/thumbnails/easy-view.basic.svg
- bricks/basic-bricks/snippets/thumbnails/easy-view.right-aligned-menu.svg
> feat(snippet): add several snippets of page layout

- bricks/time/src/task-calendar/TaskCalendar.module.css
- bricks/time/src/task-calendar/TaskCalendar.spec.tsx
- bricks/time/src/task-calendar/TaskCalendar.tsx
- bricks/time/src/task-calendar/index.tsx
Closes BRICK_STORE-2160
请勾选以下两组选项其中之一：
或者：
>
>
> feat(task-calendar): support modify footer & cell style

- bricks/time/package.json
- bricks/time/src/task-calendar/index.tsx
Refs BRICK_STORE-2160
请勾选以下两组选项其中之一：
或者：
>
>
> chore(time): version bump

- bricks/forms/src/interfaces/index.ts
- bricks/forms/src/interfaces/upload-files-v2.ts
- bricks/forms/src/upload-files-v2/UploadFilesV2.spec.tsx
- bricks/forms/src/upload-files-v2/UploadFilesV2.tsx
- bricks/forms/src/upload-files-v2/index.tsx
Refs BRICK_STORE-2163
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms): 支持设置上传按钮属性 

- bricks/forms/src/upload-files-v2/index.tsx
- bricks/forms/src/upload-files/index.tsx
- bricks/forms/src/upload-img/index.tsx
Refs: BRICK_STORE-2079
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): upload component doc update

- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/AdvancedBrickLibrary.module.css
- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/AdvancedBrickLibrary.tsx
- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.module.css
- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.tsx
- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdown.tsx
- bricks/next-builder/src/builder-container/LibraryDropdown/LibraryDropdownMenu.tsx
> fix(): refine

- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.spec.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/DataView/utils.spec.ts
- bricks/next-builder/src/builder-container/DataView/utils.ts
> fix(): support to set onReject for context

- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemFormModal.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemFormModal.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.spec.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/index.tsx
> feat(builder): use independent providers

- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/AdvancedBrickLibrary.spec.tsx
- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/filterBrick.spec.ts
- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/filterBrick.ts
- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.module.css
- bricks/next-builder/src/builder-container/BrickLibrary/BrickItem.tsx
- bricks/next-builder/src/builder-container/constants.ts
- bricks/next-builder/src/builder-container/interfaces.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
Refs NEXT_BUILDER-851
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine brick library

- bricks/time/src/task-calendar/TaskCalendar.module.css
- bricks/time/src/task-calendar/TaskCalendar.spec.tsx
- bricks/time/src/task-calendar/TaskCalendar.tsx
- bricks/time/stories/chapters/task-calendar.ts
Refs BRICK_STORE-2168
请勾选以下两组选项其中之一：
或者：
>
>
> feat(time): 任务详情支持点击跳转

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/BuilderContainer.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.spec.tsx
- bricks/next-builder/src/builder-container/RoutesView/RoutesView.tsx
- bricks/next-builder/src/builder-container/SnippetList/SnippetList.spec.tsx
- bricks/next-builder/src/builder-container/SnippetList/SnippetList.tsx
- bricks/next-builder/src/builder-container/TemplateList/TemplateList.spec.tsx
- bricks/next-builder/src/builder-container/TemplateList/TemplateList.tsx
- bricks/next-builder/src/builder-container/index.tsx
- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
> feat(): load editors from installed bricks

- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/AdvancedBrickLibrary.spec.tsx
- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/AdvancedBrickLibrary.tsx
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
> fix(get-brick-library): support http options

- bricks/presentational-bricks/src/brick-rate/BrickRate.spec.tsx
- bricks/presentational-bricks/src/brick-rate/BrickRate.tsx
- bricks/presentational-bricks/src/brick-rate/index.tsx
- bricks/presentational-bricks/stories/chapters/brick-rate.ts
refs BRICK_STORE-2173
请勾选以下两组选项其中之一：
或者：
>
>
> fix(presentational-bricks): brick-rate add value property

- bricks/presentational-bricks/src/brick-tag/BrickTag.spec.tsx
- bricks/presentational-bricks/src/brick-tag/BrickTag.tsx
- bricks/presentational-bricks/src/brick-tag/index.tsx
Closes BRICK_STORE-2176
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-tag): add support for tooltip

- bricks/flow-builder/src/schema-editor/SchemaEditor.tsx
- bricks/flow-builder/src/schema-editor/processor.spec.ts
- bricks/flow-builder/src/schema-editor/processor.ts
Refs NEXT_BUILDER-853
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix edit root value don't work

- bricks/presentational-bricks/src/brick-tree/BrickTree.spec.tsx
- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.tsx
Closes CD-2093
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-tree): add deselectable property

- bricks/presentational-bricks/src/brick-tag/BrickTag.tsx
- bricks/presentational-bricks/src/brick-tag/index.tsx
Refs CD-2003
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-tag): add tooltipProps property

- bricks/forms/src/general-input-number/GeneralInputNumber.tsx
- bricks/forms/src/general-input-number/index.tsx
Refs CD-2004
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-input-number): add readOnly and disabled properties

- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.module.css
- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.spec.tsx
- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.tsx
- bricks/presentational-bricks/src/entry-card-item/index.tsx
Closes OS-39
请勾选以下两组选项其中之一：
或者：
>
>
> feat(entry-card-item): add some style property

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrJson.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrJson.tsx
> feat(): 实例列表、详情、关系展示等页面兼容json格式 closed INSTANCE-1789

- bricks/forms/src/general-cascader/GeneralCascader.spec.tsx
- bricks/forms/src/general-cascader/index.tsx
Closes BRICK_STORE-2174
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 修复notRender失效

- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.module.css
- bricks/presentational-bricks/src/entry-card-item/EntryCardItem.tsx
- bricks/presentational-bricks/src/entry-card-item/index.tsx
Closes OS-39
请勾选以下两组选项其中之一：
或者：
>
>
> feat(entry-card-item): iconColor支持白色

- bricks/forms/src/general-radio/GeneralRadio.spec.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.module.css
- bricks/forms/src/general-radio/index.tsx
Closes UISIX-116
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms.general-radio): 新增type 类型为icon 的单选框样式

- bricks/presentational-bricks/src/brick-rate/index.tsx
- bricks/presentational-bricks/stories/chapters/brick-rate.ts
refs BRICK_STORE-2173
请勾选以下两组选项其中之一：
或者：
>
>
> feat(presentational-bricks): brick-rate add tooltips property

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvasTabs.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeMountPoint/StoryboardTreeMountPoint.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeNode/StoryboardTreeNode.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.tsx
- bricks/next-builder/src/builder-container/index.tsx
> feat(builder): support to expand templates

- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.spec.tsx
- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.tsx
> fix(): 切换表单项是否必填

- bricks/flow-builder/src/custom-processors/getNameSpaceTree.spec.ts
- bricks/flow-builder/src/custom-processors/getNameSpaceTree.ts
- bricks/flow-builder/src/index.ts
refs FLOW_BUILDER-11
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): add processor

- bricks/forms/src/general-checkbox/GeneralCheckbox.module.css
- bricks/forms/src/general-checkbox/GeneralCheckbox.spec.tsx
- bricks/forms/src/general-checkbox/GeneralCheckbox.tsx
- bricks/forms/src/general-checkbox/index.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.module.css
> feat(fgeneral-checkbox): 新增type 类型为icon 的复选框样式

- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.tsx
> fix(): refine form item

- bricks/presentational-bricks/stories/chapters/brick-quick-entries.ts
Closes BRICK_STORE-1910
请勾选以下两组选项其中之一：
或者：
>
>
> docs(brick-quick-entries): 增加 data 给子构件传递数据的demo

- bricks/presentational-bricks/src/crontab-display/CrontabDisplay.spec.tsx
- bricks/presentational-bricks/src/crontab-display/CrontabDisplay.tsx
refs CRONTAB-216
请勾选以下两组选项其中之一：
或者：
>
>
> fix(crontab-display):add schedluer

- bricks/next-builder/src/builder-container/StoryboardTreeMountPoint/StoryboardTreeMountPoint.tsx
> fix(): fix dragging mount point over inner mount points

- bricks/forms/src/general-checkbox/GeneralCheckbox.tsx
- bricks/forms/src/general-checkbox/index.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.tsx
- bricks/forms/stories/chapters/general-checkbox.ts
- bricks/forms/stories/chapters/general-radio.ts
Closes NEXT_BUILDER-866
请勾选以下两组选项其中之一：
或者：
>
>
> docs(radio / checkbox): 增加 type为icon类型的样式demo

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
Closes EASY_HUB-248
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 修复CmdbInstanceSelect后台搜索后数据异常问题

- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.tsx
- bricks/next-builder/src/builder-container/BuilderContextMenu/useCanPaste.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContextMenu/useCanPaste.ts
> feat(): support context-menu of root node

- bricks/presentational-bricks/src/brick-tree/index.tsx
Refs#BRICK_STORE-2182
请勾选以下两组选项其中之一：
或者：
>
>
> docs(brick-tree): change the type of the tree.selectV2's detail

- bricks/forms/src/general-date-picker/GeneralDatePicker.spec.tsx
- bricks/forms/src/general-date-picker/GeneralDatePicker.tsx
- bricks/forms/src/general-date-picker/index.tsx
- bricks/forms/src/interfaces/general-date-picker.ts
- bricks/forms/src/interfaces/index.ts
- bricks/forms/stories/chapters/general-date-picker.ts
Closes BRICK_STORE-2177
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms): 时间选择器可设置禁选日期

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
Closes EASY_HUB-253
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 修复CmdbInstanceSelect value数量大于默认30条时数据拉取不全问题

- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.tsx
- bricks/flow-builder/src/schema-editor/components/ref-item/RefItem.tsx
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.spec.ts
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.ts
refs NEXT_BUILDER-860
请勾选以下两组选项其中之一：
或者：
>
>
> refine import data

- bricks/basic-bricks/package.json
- bricks/basic-bricks/snippets/easy-view.ts
请勾选以下两组选项其中之一：
或者：
>
>
Followed by https://github.com/easyops-cn/next-core/pull/737, cc @Wuqimenga
> fix(): support building snippets in dev mode

- bricks/flow-builder/src/schema-editor/constants.ts
- bricks/flow-builder/src/schema-editor/processor/typeItem.spec.ts
Refs NEXT_BUILDER-853
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): miss value type

- bricks/presentational-bricks/src/brick-calendar/index.spec.ts
- bricks/presentational-bricks/src/brick-calendar/index.tsx
Closes EASY_WORK-438
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-calendar):  支持输入data

- bricks/presentational-bricks/stories/chapters/calendar.ts
Closes EASY_WORK-438
请勾选以下两组选项其中之一：
或者：
>
>
> docs(brick-calendar):  add demo

- bricks/basic-bricks/src/editor-bricks/index.ts
- bricks/basic-bricks/src/editor-bricks/page-title/page-title.editor.module.css
- bricks/basic-bricks/src/editor-bricks/page-title/page-title.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/page-title/page-title.editor.tsx
> fix(): add an editor brick of page-title

- bricks/presentational-bricks/src/brick-calendar/index.spec.ts
- bricks/presentational-bricks/src/brick-calendar/index.tsx
- bricks/presentational-bricks/stories/chapters/calendar.ts
Closes EASY_WORK-438
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-calendar):  字段修改

- bricks/flow-builder/src/schema-editor/SchemaEditor.tsx
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.spec.ts
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.ts
> fix(): extrct model ref

- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/filterBrick.spec.ts
- bricks/next-builder/src/builder-container/AdvancedBrickLibrary/filterBrick.ts
- bricks/next-builder/src/builder-container/interfaces.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
> fix(brick-library): support searching multiple fields

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
> fix(build-storyboard): parse template proxy as json instead of yaml

- bricks/presentational-bricks/src/editor-bricks/brick-result/brick-result.editor.module.css
- bricks/presentational-bricks/src/editor-bricks/brick-result/brick-result.editor.tsx
Refs NEXT_BUILDER-740
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): brick-result editor add content slot

- bricks/presentational-bricks/src/log-display/LogDisplay.tsx
- bricks/presentational-bricks/src/log-display/index.tsx
Refs BRICK_STORE-713
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support custom style

- bricks/basic-bricks/package.json
- yarn.lock
refs BRICK_STORE-2188
请勾选以下两组选项其中之一：
- [] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。
或者：
>
>
> fix(basic-components): 折叠时，刷新页面菜单悬浮

- bricks/presentational-bricks/src/brick-general-search/BrickGeneralSearch.spec.tsx
- bricks/presentational-bricks/src/brick-general-search/BrickGeneralSearch.tsx
- bricks/presentational-bricks/src/brick-general-search/index.module.css
- bricks/presentational-bricks/src/brick-general-search/index.spec.ts
- bricks/presentational-bricks/src/brick-general-search/index.tsx
- bricks/presentational-bricks/src/i18n/constants.ts
- bricks/presentational-bricks/src/i18n/locales/en.ts
- bricks/presentational-bricks/src/i18n/locales/zh.ts
> fix(): 搜索框支持ip搜索 closed FULLSEARCH-82

- bricks/presentational-bricks/src/brick-tag/index.tsx
> feat(brick-tag): checked update events support event.preventDefault

- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
> fix(get-brick-library): support ignore snippets

- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.spec.tsx
- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.tsx
> fix(): normalize data

- bricks/basic-bricks/snippets/layout/classic-layout.ts
- bricks/basic-bricks/snippets/thumbnails/classic-layout/grid-classic-titlebar-toolbar-content.svg
> feat(easy-view): add a snippet to easy-view

- bricks/presentational-bricks/src/brick-tag/BrickTag.spec.tsx
- bricks/presentational-bricks/src/brick-tag/BrickTag.tsx
> fix(brick-tag): fix CheckableTag string icon

- bricks/forms/src/tree-select/TreeSelect.tsx
- bricks/forms/src/tree-select/index.tsx
> feat(tree-select): add treeCheckStrictly property

- bricks/forms/src/dynamic-user-select-item/index.tsx
refs MONITOR-1846
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): clearAll不生效

- bricks/next-builder/src/builder-container/constants.ts
Refs NEXT_BUILDER-851
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): frequently layout snippets

- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.spec.ts
- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
> fix(): fix when installed bricks has no text

- bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> fix(build-storboard): add menu group injecting related fields

- bricks/forms/src/dynamic-form-item/DynamicFormItem.tsx
- bricks/forms/src/dynamic-form-item/index.tsx
Refs BRICK_STORE-1346
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support maxTagCount

- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/DataView.tsx
- bricks/next-builder/src/builder-container/DataView/utils.spec.ts
- bricks/next-builder/src/builder-container/DataView/utils.ts
> feat(DataView): resolve type context add value field

- bricks/flow-builder/src/schema-editor/SchemaEditor.tsx
- bricks/flow-builder/src/schema-editor/components/schema-item/SchemaItem.tsx
- bricks/flow-builder/src/schema-editor/index.tsx
Refs NEXT_BUILDER-853
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support readonly

- bricks/flow-builder/src/schema-editor/SchemaEditor.tsx
- bricks/flow-builder/src/schema-editor/components/schema-item/SchemaItem.tsx
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.spec.ts
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.ts
> fix(): refine processor

- bricks/presentational-bricks/src/markdown-display/MarkdownDisplay.module.css
> fix(markdown-display): fix style of paragraphs inside a list

- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.spec.ts
- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.ts
> fix(): slient errors when scanning contexts

- bricks/presentational-bricks/src/brick-table/brickTableHelper.spec.ts
- bricks/presentational-bricks/src/brick-table/brickTableHelper.ts
- bricks/presentational-bricks/src/brick-table/index.tsx
refs BRICK_STORE-2238
请勾选以下两组选项其中之一：
或者：
>
>
> feat(table): brick-table 的rowDisabledConfig支持更多的operator

- bricks/next-builder/src/search-tree/utils.spec.tsx
- bricks/next-builder/src/search-tree/utils.tsx
Refs: NEXT_BUILDER-879
请勾选以下两组选项其中之一：
或者：
>
>
修复多级路由情况下, 子路由realParentId始终指向一级路由的问题
> fix(search-tree): fix while deep route and the parentId is errr

- bricks/forms/src/dynamic-common-item/DynamicCommonItem.tsx
- bricks/forms/src/i18n/constants.ts
- bricks/forms/src/i18n/locales/en.ts
- bricks/forms/src/i18n/locales/zh.ts
- bricks/forms/src/upload-files-v2/UploadFilesV2.spec.tsx
- bricks/forms/src/upload-files-v2/UploadFilesV2.tsx
> feat(): add i18n refs FLOW-443

- bricks/presentational-bricks/src/brick-link/BrickLink.spec.tsx
- bricks/presentational-bricks/src/brick-link/BrickLink.tsx
Closes BRICK_STORE-2249
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-link): 禁用时icon也要置灰

- bricks/presentational-bricks/src/general-transfer/GeneralTransfer.spec.tsx
- bricks/presentational-bricks/src/general-transfer/GeneralTransfer.tsx
refs MONITOR-1890
请勾选以下两组选项其中之一：
或者：
>
>
> fix(presentational-bricks): "maxSelected" has some problems

- .size-limit.js
- bricks/forms/package.json
- bricks/forms/src/crontab-input/CrontabInput.spec.tsx
- bricks/forms/src/crontab-input/CrontabInput.tsx
- bricks/forms/src/i18n/constants.ts
- bricks/forms/src/i18n/locales/en.ts
- bricks/forms/src/i18n/locales/zh.ts
- bricks/presentational-bricks/package.json
- yarn.lock
> chore(): add i18n

- bricks/presentational-bricks/src/brick-divider/BrickDivider.module.css
- bricks/presentational-bricks/src/brick-divider/BrickDivider.spec.tsx
- bricks/presentational-bricks/src/brick-divider/BrickDivider.tsx
- bricks/presentational-bricks/src/brick-divider/__snapshots__/BrickDivider.spec.tsx.snap
- bricks/presentational-bricks/src/brick-divider/index.tsx
- bricks/presentational-bricks/stories/chapters/brick-divider.ts
refs MONITOR-1878
请勾选以下两组选项其中之一：
或者：
>
>
> feat(presentational-bricks): add radiation and plain properties

- bricks/forms/package.json
- bricks/forms/src/crontab-input/CrontabInput.spec.tsx
- bricks/forms/src/crontab-input/useCrontab.spec.tsx
- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/crontab-display/CrontabDisplay.spec.tsx
- yarn.lock
请勾选以下两组选项其中之一：
- [] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。
或者：
>
>
> chore(): update dependencies

- bricks/developers/src/stories/chapters/business-bricks/cmdb-instances/delete-confirm.ts
> chore(): refie doc

- bricks/basic-bricks/src/general-anchor/GeneralAnchor.spec.tsx
- bricks/basic-bricks/src/general-anchor/GeneralAnchor.tsx
- bricks/basic-bricks/src/general-anchor/index.shadow.less
- bricks/basic-bricks/src/general-anchor/index.spec.ts
- bricks/basic-bricks/src/general-anchor/index.tsx
- bricks/basic-bricks/src/index.ts
refs MONITOR-1890
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): add anchor brick

- bricks/time/src/task-calendar/TaskCalendar.spec.tsx
- bricks/time/src/task-calendar/TaskCalendar.tsx
- bricks/time/src/task-calendar/index.tsx
Closes BRICK_STORE-2259
请勾选以下两组选项其中之一：
或者：
>
>
> feat(task-calendar): 任务日历是否显示农历文字

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
BRICK_STORE-1482
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support debounce search

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
- bricks/presentational-bricks/src/brick-table/BrickTable.spec.tsx
- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
> fix(): 支持隐藏/显示省略信息 closed INSTANCE-1838

- .size-limit.js
- bricks/flow-builder/package.json
- bricks/flow-builder/src/fields-mapping-editor/FieldsMappingEditor.spec.tsx
- bricks/flow-builder/src/fields-mapping-editor/FieldsMappingEditor.tsx
- bricks/flow-builder/src/fields-mapping-editor/components/CodeEditor/CodeEditorFormItem.spec.tsx
- bricks/flow-builder/src/fields-mapping-editor/components/CodeEditor/CodeEditorFormItem.tsx
- bricks/flow-builder/src/fields-mapping-editor/components/editable-cell/EditableCell.module.css
- bricks/flow-builder/src/fields-mapping-editor/components/editable-cell/EditableCell.spec.tsx
- bricks/flow-builder/src/fields-mapping-editor/components/editable-cell/EditableCell.tsx
- bricks/flow-builder/src/fields-mapping-editor/constants.ts
- bricks/flow-builder/src/fields-mapping-editor/interfaces.ts
- bricks/flow-builder/src/fields-mapping-editor/processor.spec.ts
- bricks/flow-builder/src/fields-mapping-editor/processor.ts
- yarn.lock
> fix(): process onchange data

- bricks/flow-builder/src/fields-mapping-editor/FieldsMappingEditor.tsx
- bricks/flow-builder/src/fields-mapping-editor/index.tsx
- bricks/flow-builder/src/fields-mapping-editor/processor.spec.ts
- bricks/flow-builder/src/fields-mapping-editor/processor.ts
> fix(): remove extra fields

- bricks/flow-builder/src/fields-mapping-editor/FieldsMappingEditor.spec.tsx
- bricks/flow-builder/src/fields-mapping-editor/FieldsMappingEditor.tsx
- bricks/flow-builder/src/fields-mapping-editor/components/editable-cell/EditableCell.tsx
- bricks/flow-builder/src/i18n/constants.ts
- bricks/flow-builder/src/i18n/locales/en.ts
- bricks/flow-builder/src/i18n/locales/zh.ts
> fix(): refine fieldsMapping table

- bricks/flow-builder/src/fields-mapping-editor/FieldsMappingEditor.tsx
- bricks/flow-builder/src/fields-mapping-editor/components/CodeEditor/CodeEditorFormItem.tsx
- bricks/flow-builder/src/fields-mapping-editor/components/editable-cell/EditableCell.tsx
> fix(): fix yaml covert logic

- bricks/presentational-bricks/src/general-slider/GeneralSlider.module.css
- bricks/presentational-bricks/src/general-slider/GeneralSlider.spec.tsx
- bricks/presentational-bricks/src/general-slider/GeneralSlider.tsx
- bricks/presentational-bricks/src/general-slider/index.tsx
- bricks/presentational-bricks/stories/chapters/general-slider.ts
- bricks/presentational-bricks/stories/chapters/index.ts
Closes MONITOR-1923
请勾选以下两组选项其中之一：
或者：
>
>
> feat(fgeneral-slider): 新增dashboard 样式

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
> refactor(): normalize menu

- bricks/forms/src/general-radio/GeneralRadio.spec.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.module.css
- bricks/forms/src/general-radio/index.tsx
- bricks/forms/src/general-slide/GeneralSlide.tsx
- bricks/forms/src/general-slide/index.tsx
- bricks/forms/src/interfaces/general-form.ts
Closes MONITOR-1924
请勾选以下两组选项其中之一：
或者：
>
>
> feat(fgeneral-radio): 新增dashboard 样式

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrFloat.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrFloat.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStr.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStr.tsx
- bricks/forms/src/cmdb-object-attr-value/index.spec.ts
- bricks/forms/src/cmdb-object-attr-value/index.tsx
Closes INSTANCE-1894
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 修复cmdb添加属性构件无默认值default为null时也会触发正则校验

- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-slide/GeneralSlide.tsx
Refs MONITOR-1923
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复 dashboard 影响有些radio/slide 不能触发的问题

- bricks/basic-bricks/src/general-title/GeneralTitle.module.css
- bricks/basic-bricks/src/general-title/GeneralTitle.spec.tsx
- bricks/basic-bricks/src/general-title/GeneralTitle.tsx
- bricks/basic-bricks/src/general-title/index.spec.ts
- bricks/basic-bricks/src/general-title/index.tsx
- bricks/basic-bricks/src/index.ts
refs 1949
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): add general-title brick

- bricks/flow-builder/src/data-providers/CreateFunctionContract.spec.ts
- bricks/flow-builder/src/data-providers/CreateFunctionContract.ts
- bricks/flow-builder/src/index.ts
> feat(): provider-create-function-contract

- bricks/flow-builder/src/custom-processors/getFunctionStep.spec.ts
- bricks/flow-builder/src/custom-processors/getFunctionStep.ts
- bricks/flow-builder/src/index.ts
Refs FLOW_BUILDER-110
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add graph processor

- bricks/flow-builder/src/custom-processors/getFunctionStep.spec.ts
- bricks/flow-builder/src/custom-processors/getFunctionStep.ts
Refs FLOW_BUILDER-110
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine graph

- bricks/flow-builder/src/custom-processors/getFunctionStep.ts
Refs FLOW_BUILDER-110
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): typo

- bricks/presentational-bricks/src/index.ts
- bricks/presentational-bricks/src/rank-table/RankTable.module.css
- bricks/presentational-bricks/src/rank-table/RankTable.spec.tsx
- bricks/presentational-bricks/src/rank-table/RankTable.tsx
- bricks/presentational-bricks/src/rank-table/RankTableHelper.tsx
- bricks/presentational-bricks/src/rank-table/index.spec.ts
- bricks/presentational-bricks/src/rank-table/index.tsx
- bricks/presentational-bricks/stories/chapters/index.ts
- bricks/presentational-bricks/stories/chapters/rank-table.ts
- yarn.lock
Closes MONITOR-1944
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 新增排名表格

- bricks/time/src/i18n/constants.ts
- bricks/time/src/i18n/locales/en.ts
- bricks/time/src/i18n/locales/zh.ts
- bricks/time/src/task-calendar/Calendar.module.css
- bricks/time/src/task-calendar/Calendar.spec.tsx
- bricks/time/src/task-calendar/Calendar.tsx
- bricks/time/src/task-calendar/TaskCalendar.module.css
- bricks/time/src/task-calendar/TaskCalendar.tsx
- bricks/time/src/task-calendar/index.spec.ts
- bricks/time/src/task-calendar/index.tsx
- bricks/time/src/task-calendar/utils.spec.tsx
- bricks/time/src/task-calendar/utils.tsx
Closes BRICK_STORE-2268
请勾选以下两组选项其中之一：
或者：
>
>
日历需要显示周视图，但antd的calendar只支持月视图和年视图，需要自己写一个calendar了。
> feat(time): 任务日历增加周视图

- bricks/presentational-bricks/src/basic-progress/BasicProgress.spec.tsx
- bricks/presentational-bricks/src/basic-progress/BasicProgress.tsx
- bricks/presentational-bricks/src/basic-progress/index.tsx
Refs#NEXT_BUILDER-936
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add the textColor property to basic-progress

- bricks/forms/src/general-slide/GeneralSlide.tsx
- bricks/forms/src/general-slide/index.tsx
Refs MONITOR-1923
请勾选以下两组选项其中之一：
或者：
>
>
> feat(fgeneral-slide): 新增tip格式化

- bricks/basic-bricks/src/general-title/GeneralTitle.module.css
- bricks/basic-bricks/src/general-title/GeneralTitle.spec.tsx
- bricks/basic-bricks/src/general-title/GeneralTitle.tsx
- bricks/basic-bricks/src/general-title/index.tsx
- bricks/basic-bricks/stories/chapters/general-title.ts
- bricks/basic-bricks/stories/chapters/index.ts
refs MONITOR-1916
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): add subTitle properties and doc

- bricks/forms/src/general-radio/GeneralRadio.spec.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
Closes NEXT_BUILDER-935
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-radio): 修复type:icon时在表单中会失效

- bricks/basic-bricks/src/general-title/GeneralTitle.module.css
Refes MONITOR-1918
请勾选以下两组选项其中之一：
或者：
>
>
> style() : marginbottom

- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.tsx
Refs NEXT_BUILDER-935
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): radio support tooltip

- bricks/presentational-bricks/src/brick-table/index.tsx
Refs CD-2235
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-table): rowDisabledConfig property support array

- bricks/forms/src/general-form/index.spec.ts
- bricks/forms/src/general-form/index.tsx
Refs CD-2240
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-form): add validateTouchedField method

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/cmdb-instance-select/index.tsx
> feat(): CmdbInstanceSelect支持permission

- bricks/presentational-bricks/src/dynamic-grid-container/DynamicGridContainer.tsx
- bricks/presentational-bricks/src/dynamic-grid-container/index.tsx
refs MONITOR-1898
请勾选以下两组选项其中之一：
或者：
>
>
> fix(presentational-bricks): unique key

- bricks/flow-builder/src/custom-processors/formatFeildsMap.spec.ts
- bricks/flow-builder/src/custom-processors/formatFeildsMap.ts
- bricks/flow-builder/src/fields-mapping-editor/FieldsMappingEditor.module.css
- bricks/flow-builder/src/fields-mapping-editor/FieldsMappingEditor.spec.tsx
- bricks/flow-builder/src/fields-mapping-editor/FieldsMappingEditor.tsx
- bricks/flow-builder/src/fields-mapping-editor/index.spec.ts
- bricks/flow-builder/src/fields-mapping-editor/index.tsx
- bricks/flow-builder/src/fields-mapping-editor/interfaces.ts
- bricks/flow-builder/src/fields-mapping-editor/processor.spec.ts
- bricks/flow-builder/src/fields-mapping-editor/processor.ts
- bricks/flow-builder/src/i18n/constants.ts
- bricks/flow-builder/src/i18n/locales/en.ts
- bricks/flow-builder/src/i18n/locales/zh.ts
> fix(): refactor field mapping table

- bricks/presentational-bricks/src/copyable-text/CopyableText.spec.tsx
- bricks/presentational-bricks/src/copyable-text/CopyableText.tsx
- bricks/presentational-bricks/src/copyable-text/index.tsx
- bricks/presentational-bricks/stories/chapters/copyable-text.ts
> feat(copy): 可复制文本构件增加input样式

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboard.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
> feat(): build functions

- bricks/next-builder/src/data-providers/ScanFunctionsInStoryboard.spec.ts
- bricks/next-builder/src/data-providers/ScanFunctionsInStoryboard.ts
- bricks/next-builder/src/index.ts
> feat(): ScanFunctionsInStoryboard

- bricks/forms/src/general-input-number/index.tsx
- bricks/forms/src/general-input/index.tsx
- bricks/forms/src/general-textarea/index.tsx
> fix(): fix property type of readOnly

- bricks/basic-bricks/src/micro-app/MicroApp.spec.tsx
- bricks/basic-bricks/src/micro-app/MicroApp.tsx
- bricks/basic-bricks/src/micro-app/index.spec.ts
Closes NEXT_BUILDER-949
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): dashboardMode支持更换logo

- bricks/forms/src/general-form/GeneralForm.spec.tsx
- bricks/forms/src/general-form/GeneralForm.tsx
- bricks/forms/src/general-form/index.tsx
> fix(): support formStyle

- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
Closes BRICK_STORE-2274
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-auth): 修复登录页logo获取字段错误

- bricks/next-builder/src/shared/storyboard/buildStoryboard.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
> fix(): support building functions which use typescript

- bricks/next-builder/src/data-providers/ScanFunctionsInStoryboard.spec.ts
- bricks/next-builder/src/data-providers/ScanFunctionsInStoryboard.ts
> fix(): scan functions which use typescript

- bricks/presentational-bricks/src/brick-table/index.tsx
Closes BRICK_STORE-2269
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-table): prefer page and page size in dataSource

- bricks/presentational-bricks/src/basic-progress/BasicProgress.tsx
- bricks/presentational-bricks/src/basic-progress/index.tsx
Refs#NEXT_BUILDER-957
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): add some colors

- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
- bricks/next-builder/src/data-providers/utils/getBrickPackageIndexJs.ts
- bricks/next-builder/src/data-providers/utils/simpleHash.ts
- bricks/next-builder/src/index.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> feat(): build project of templates

- bricks/presentational-bricks/src/brick-descriptions/BrickDescriptions.spec.tsx
- bricks/presentational-bricks/src/brick-descriptions/BrickDescriptions.tsx
- bricks/presentational-bricks/src/brick-descriptions/index.tsx
- bricks/presentational-bricks/stories/chapters/brick-descriptions.ts
Closes AOPS-218
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-descriptions):  描述列表支持设置隐藏项

- bricks/presentational-bricks/src/brick-timeline/index.module.css
Refs CD-2005
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): description text allow line breaks

- bricks/general-auth/deploy-default/package.conf.yaml
- bricks/general-auth/package.json
- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- yarn.lock
Refs EASY_CONF-27
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-auth): 登陆认证信息增加 accessRule 字段

- bricks/presentational-bricks/src/copyable-text/CopyableText.spec.tsx
- bricks/presentational-bricks/src/copyable-text/CopyableText.tsx
- bricks/presentational-bricks/src/copyable-text/index.module.css
- bricks/presentational-bricks/src/copyable-text/index.spec.ts
- bricks/presentational-bricks/src/copyable-text/index.tsx
Refs SERVICE_OBSERVE-499
请勾选以下两组选项其中之一：
或者：
>
>
> feat(copyable-text): add text.click

- bricks/basic-bricks/src/general-drawer/GeneralDrawer.tsx
- bricks/basic-bricks/src/general-drawer/index.tsx
refs MONITOR-1898
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): drawer add mask、headerStyle、configProps properties

- bricks/presentational-bricks/src/rank-table/RankTable.spec.tsx
- bricks/presentational-bricks/src/rank-table/RankTable.tsx
- bricks/presentational-bricks/src/rank-table/RankTableHelper.tsx
- bricks/presentational-bricks/src/rank-table/index.tsx
> fix(): 添加属性支持rank-table在小容器时样式调整 Closed SERVICE_OBSERVE-381

- .size-limit.js
- bricks/presentational-bricks/src/dropdown-button/DropdownButton.module.css
- bricks/presentational-bricks/src/dropdown-button/DropdownButton.spec.tsx
- bricks/presentational-bricks/src/dropdown-button/DropdownButton.tsx
- bricks/presentational-bricks/src/dropdown-button/index.spec.ts
- bricks/presentational-bricks/src/dropdown-button/index.tsx
- bricks/presentational-bricks/src/index.ts
- bricks/presentational-bricks/stories/chapters/dropdown-button.ts
- bricks/presentational-bricks/stories/chapters/index.ts
refs MONITOR-2047
请勾选以下两组选项其中之一：
或者：
>
>
> feat(presentational-bricks): add dropdown-button brick

- .size-limit.js
- bricks/presentational-bricks/package.json
- bricks/presentational-bricks/src/basic-icon/BasicIcon.module.css
- bricks/presentational-bricks/src/basic-icon/BasicIcon.spec.tsx
- bricks/presentational-bricks/src/basic-icon/BasicIcon.tsx
- bricks/presentational-bricks/src/basic-icon/index.spec.ts
- bricks/presentational-bricks/src/basic-icon/index.tsx
- bricks/presentational-bricks/src/general-tooltip/GeneralTooltip.spec.tsx
- bricks/presentational-bricks/src/index.ts
- bricks/presentational-bricks/stories/chapters/basic-icon.ts
- bricks/presentational-bricks/stories/chapters/index.ts
- yarn.lock
presentational-bricks
Refs#NEXT_BUILDER-945
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-icon): add a new brick named basic-icon to

- bricks/presentational-bricks/src/basic-icon/BasicIcon.tsx
Refs#NEXT_BUILDER-945
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix typeerror of basic-icon

- bricks/presentational-bricks/src/basic-icon/BasicIcon.spec.tsx
- bricks/presentational-bricks/src/basic-icon/BasicIcon.tsx
- bricks/presentational-bricks/src/basic-icon/index.spec.ts
Refs#NEXT_BUILDER-945
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix bug of basic-icon

- bricks/basic-bricks/src/general-title/GeneralTitle.module.css
- bricks/basic-bricks/src/general-title/GeneralTitle.spec.tsx
- bricks/basic-bricks/src/general-title/GeneralTitle.tsx
- bricks/basic-bricks/src/general-title/index.tsx
refs MONITOR-2047
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): add descSuffixBrick property

- bricks/next-builder/src/event-config-form/EventConfigForm.spec.tsx
- bricks/next-builder/src/event-config-form/EventConfigForm.tsx
- bricks/next-builder/src/event-config-form/index.tsx
- bricks/next-builder/src/events-editor/EventsEditor.module.css
- bricks/next-builder/src/events-editor/EventsEditor.tsx
- bricks/next-builder/src/events-editor/components/add-event-btn/AddEventBtn.module.css
- bricks/next-builder/src/events-editor/components/add-event-btn/AddEventBtn.spec.tsx
- bricks/next-builder/src/events-editor/components/add-event-btn/AddEventBtn.tsx
- bricks/next-builder/src/events-editor/components/handler-item/HandlerItem.module.css
- bricks/next-builder/src/events-editor/components/handler-item/HandlerItem.tsx
- bricks/next-builder/src/events-editor/index.tsx
- bricks/next-builder/src/shared/visual-events/interfaces.ts
Refs NEXT_BUILDER-938
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine lifecycle event

- bricks/forms/src/custom-templates/tpl-cmdb-object-attr-add.ts
Closes INSTANCE-1928
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 模型属性id编辑时取消对长度的验证

- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
- bricks/presentational-bricks/src/brick-table/BrickTable.tsx
- bricks/presentational-bricks/src/brick-table/index.tsx
close BRICK_STORE-2287
请勾选以下两组选项其中之一：
或者：
>
>
> feat(table): brick-table support thTransparent

- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
Refs: NEXT_BUILDER-973
请勾选以下两组选项其中之一：
或者：
>
>
支持custom-template文档生成
> feat(): custom template support doc

- bricks/presentational-bricks/src/general-carousel/GeneralCarousel.tsx
- bricks/presentational-bricks/src/general-carousel/index.tsx
Close BRICK_STORE-2285
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-carousel): general-carousel support  autoplaySpeed

- bricks/presentational-bricks/src/brick-quick-entries/BrickQuickEntries.spec.tsx
- bricks/presentational-bricks/src/brick-quick-entries/BrickQuickEntries.tsx
- bricks/presentational-bricks/src/brick-quick-entries/index.tsx
> fix(): 快捷入口构件支持每项的标题设置 Closed SERVICE_OBSERVE-407

- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
Refs: NEXT_BUILDER-973
请勾选以下两组选项其中之一：
或者：
>
>
增加了layerType: widget类型用以区分构件类型
> feat(): add layerType for widget doc file

- bricks/basic-bricks/package.json
- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.spec.tsx
- bricks/basic-bricks/src/general-custom-buttons/GeneralCustomButtons.tsx
- yarn.lock
Refs BRICK_STORE-2293
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-custom-buttons): add data-icon attribute

- bricks/basic-bricks/package.json
- bricks/brick-visualization/package.json
- bricks/developers/package.json
- bricks/forms/package.json
- bricks/next-builder/package.json
- bricks/presentational-bricks/package.json
- yarn.lock
Refs: MONITOR-2140
请勾选以下两组选项其中之一：
或者：
>
>
依赖更新
> feat(): update dependencies with @next-libs/basic-compomnents

- bricks/forms/src/general-radio/GeneralRadio.tsx
> fix(): 普通单选框支持label和icon Closed SERVICE_OBSERVE-538

- bricks/presentational-bricks/src/brick-quick-entries/BrickQuickEntries.spec.tsx
- bricks/presentational-bricks/src/brick-quick-entries/BrickQuickEntries.tsx
- bricks/presentational-bricks/src/brick-quick-entries/index.tsx
> fix(): 统计入口卡片标题支持icon,支持隐藏线 Closed SERVICE_OBSERVE-538

- bricks/presentational-bricks/src/brick-quick-entries/BrickQuickEntries.tsx
> fix(): 隐藏线问题修复 Closed SERVICE_OBSERVE-538

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
Refs SERVICE_OBSERVE-466
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-select): add showCheckedValueSuffix

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.module.css
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
> chore(basic-bricks): 语言切换按钮样式修改

- bricks/presentational-bricks/src/brick-quick-entries/BrickQuickEntries.tsx
- bricks/presentational-bricks/src/brick-quick-entries/index.tsx
> fix(): 统分割线bug Closed SERVICE_OBSERVE-538

- bricks/basic-bricks/src/general-modal/GeneralModal.tsx
- bricks/basic-bricks/src/general-modal/index.spec.tsx
- bricks/basic-bricks/src/general-modal/index.tsx
Refs NEXT_BUILDER-1000
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): general modal support after close event

- bricks/presentational-bricks/src/dropdown-select/DropdownSelect.spec.tsx
- bricks/presentational-bricks/src/dropdown-select/DropdownSelect.tsx
- bricks/presentational-bricks/src/dropdown-select/index.tsx
> fix(): 下拉菜单添加禁用属性,内容高度控制属性 Closed SERVICE_OBSERVE-407

- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.spec.tsx
- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.tsx
- bricks/presentational-bricks/src/modal-confirm/index.tsx
Closes SERVICE_OBSERVE-598
请勾选以下两组选项其中之一：
或者：
>
>
> feat(modal-confirm): add contentBrick

- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.spec.tsx
- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.tsx
- bricks/presentational-bricks/src/modal-confirm/index.tsx
Refs SERVICE_OBSERVE-598
请勾选以下两组选项其中之一：
或者：
>
>
> fix(modal-confirm): fix contentBrick bug

- bricks/presentational-bricks/src/brick-utils/index.tsx
> fix(brick-utils): 复制成功/失败文案可配置

- bricks/basic-bricks/src/general-custom-buttons/index.module.css
- bricks/basic-bricks/stories/chapters/general-custom-buttons.ts
le
Refs CD-2215
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-custom-buttons): icon buttonType support danger sty

- bricks/basic-bricks/src/general-drawer/index.shadow.less
Refs SERVICE_OBSERVE-619
请勾选以下两组选项其中之一：
或者：
>
>
> fix(drawer): fix浮层抽屉关闭后漏出一点儿

- bricks/basic-bricks/src/app-bar/SearchBar/SearchBar.tsx
- bricks/basic-bricks/src/i18n/constants.ts
- bricks/basic-bricks/src/i18n/locales/en.ts
- bricks/basic-bricks/src/i18n/locales/zh.ts
- bricks/presentational-bricks/src/agent-status/AgentStatus.tsx
- bricks/presentational-bricks/src/agent-status/index.tsx
> feat(): 国际化 refs LAUNCHPAD-75

- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
Refs BRICK_STORE-2307
请勾选以下两组选项其中之一：
或者：
>
>
> fix(login): 记住上次登陆方式

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
- bricks/next-builder/src/data-providers/ScanFunctionsInStoryboard.ts
- bricks/next-builder/src/data-providers/utils/getBrickPackageIndexJs.ts
- bricks/next-builder/src/data-providers/utils/replaceWidgetFunctions.spec.ts
- bricks/next-builder/src/data-providers/utils/replaceWidgetFunctions.ts
> feat(): support building widget functions

- bricks/forms/src/upload-img/UploadImg.module.css
- bricks/forms/src/upload-img/UploadImg.spec.tsx
- bricks/forms/src/upload-img/UploadImg.tsx
- bricks/forms/src/upload-img/index.tsx
refs MONITOR-2348
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms): add showMentions property

- bricks/basic-bricks/src/menu-bar/LogoBar/LogoBar.spec.tsx
- bricks/basic-bricks/src/menu-bar/LogoBar/LogoBar.tsx
refs BRICK_STORE-2313
请勾选以下两组选项其中之一：
或者：
>
>
> feat(LogoBar): logo支持不设置link

- bricks/basic-bricks/src/popover-container/PopoverContainer.module.css
- bricks/basic-bricks/src/popover-container/PopoverContainer.spec.tsx
- bricks/basic-bricks/src/popover-container/PopoverContainer.tsx
- bricks/basic-bricks/src/popover-container/index.tsx
refs SERVICE_OBSERVE-650
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): popover-container support highlight

- bricks/general-auth/src/general-login/GeneralLogin.module.css
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- bricks/general-auth/src/general-signup/GeneralSignup.spec.tsx
- bricks/general-auth/src/general-signup/GeneralSignup.tsx
- bricks/general-auth/src/general-signup/Terms.module.css
- bricks/general-auth/src/general-signup/Terms.tsx
- bricks/general-auth/src/general-signup/index.tsx
Refs#EASYOPSAIR-12
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix the bugs of terms and api

- bricks/basic-bricks/src/general-drawer/GeneralDrawer.tsx
- bricks/basic-bricks/src/general-drawer/index.shadow.less
- bricks/basic-bricks/src/general-drawer/index.tsx
- bricks/basic-bricks/src/general-drawer/left-arrow.svg
- bricks/basic-bricks/src/general-drawer/right-arrow.svg
> fix(drawer): drawer 外侧开关按钮

- bricks/utils/src/broadcast-channel/BroadcastChannel.spec.tsx
- bricks/utils/src/broadcast-channel/BroadcastChannel.tsx
- bricks/utils/src/broadcast-channel/index.tsx
- bricks/utils/src/general-clipboard/index.tsx
- bricks/utils/stories/chapters/broadcast-channel.ts
- bricks/utils/stories/chapters/general-clipboard.ts
- bricks/utils/stories/index.ts
> chore(): refine docs for utils.*

- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
- bricks/general-auth/src/general-signup/GeneralSignup.tsx
- bricks/general-auth/src/i18n/locales/en.ts
- bricks/general-auth/src/i18n/locales/zh.ts
Refs#USER_ADMIN-198
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix the bug of validation

- bricks/forms/src/general-select/GeneralSelect.module.css
> chore(forms): general-select style chroe

- bricks/presentational-bricks/src/brick-timeline/BrickTimeline.tsx
- bricks/presentational-bricks/src/brick-timeline/index.tsx
- bricks/presentational-bricks/src/brick-timeline/processor.spec.ts
- bricks/presentational-bricks/src/brick-timeline/processor.ts
- bricks/presentational-bricks/stories/chapters/brick-timeline.ts
Refs BRICK_STORE-1636
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix timeline show wrong mouth

- bricks/general-auth/src/general-signup/validateProvider.spec.ts
- bricks/general-auth/src/general-signup/validateProvider.ts
Closes EASYOPSAIR-20
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-signup): catch validation error

- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.module.css
- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.tsx
Refs PRD_OPS-692
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): add vendor prefixes

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/cmdb-instance-select/index.tsx
> fix(forms): add tooltip to cmdb-instance-select

- bricks/forms/package.json
- yarn.lock
> fix(): 告警事件中心CMDB通用实例列表模态框v2弹窗的取消按钮应使用文字按钮样式 EVENT-275

- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
请勾选以下两组选项其中之一：
或者：
>
>
将storiesJSON中的图片地址做统一转化
> feat(BuilderProjectOfTemplate): replace StroiesJSON URL

- bricks/forms/src/custom-templates/tpl-cmdb-object-attr-add.ts
Refs INSTANCE-2020
请勾选以下两组选项其中之一：
或者：
>
>
> chore(forms): 流水号、自增id属性修改逻辑优化

- bricks/forms/src/general-cascader/GeneralCascader.spec.tsx
- bricks/forms/src/general-cascader/GeneralCascader.tsx
- bricks/forms/src/general-cascader/index.tsx
- bricks/forms/src/general-cascader/processor.spec.ts
- bricks/forms/src/general-cascader/processor.ts
- bricks/forms/src/interfaces/general-cascader.ts
- bricks/forms/src/interfaces/index.ts
- bricks/forms/stories/chapters/general-cascader.ts
Refs NEXT_BUILDER-1088
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): cascder support dynamic loading data

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
> fix(): fix favicon selector

- bricks/developers/deploy-default/package.conf.yaml
- bricks/developers/src/components/BrickPreview/BrickPreview.spec.tsx
- bricks/developers/src/components/BrickPreview/BrickPreview.tsx
> feat(BrickPreview): support checkoutTplContext

- bricks/presentational-bricks/src/brick-link/BrickLink.spec.tsx
- bricks/presentational-bricks/src/brick-link/BrickLink.tsx
- bricks/presentational-bricks/src/brick-link/__snapshots__/BrickLink.spec.tsx.snap
- bricks/presentational-bricks/src/brick-link/index.tsx
- bricks/presentational-bricks/src/brick-link/style.module.css
> fix(): brick-link支持label颜色设置和下划线 closed MONITOR-2419

- bricks/basic-bricks/src/general-drawer/GeneralDrawer.tsx
> fix(drawer): 抽屉未打开时预渲染

- bricks/basic-bricks/src/general-drawer/GeneralDrawer.tsx
- bricks/basic-bricks/src/general-drawer/index.shadow.less
- bricks/basic-bricks/src/general-drawer/index.tsx
- bricks/basic-bricks/src/general-drawer/left-arrow.svg
- bricks/basic-bricks/src/general-drawer/right-arrow.svg
> fix(drawer): 抽屉外侧按钮样式

- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
- bricks/next-builder/src/data-providers/utils/replaceWidgetFunctions.spec.ts
- bricks/next-builder/src/data-providers/utils/replaceWidgetFunctions.ts
- declarations/global.d.ts
> feat(): support getting images by static files

- bricks/general-auth/src/general-login/GeneralLogin.tsx
> fix(): next新站点验证码登陆样式调整 refs DESKTOP-238

- bricks/forms/src/general-structs-form-item/GeneralStructsFormItem.spec.tsx
- bricks/forms/src/general-structs-form-item/GeneralStructsFormItem.tsx
- bricks/forms/src/general-structs-form-item/index.tsx
close PIPELINE-1438
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms): general struce support structInnerTableColumnsOrder

- bricks/presentational-bricks/src/rank-table/RankTable.module.css
refs MONITOR-2548
请勾选以下两组选项其中之一：
或者：
>
>
> fix(presentational-bricks): modify rank-table `small` style

- bricks/presentational-bricks/src/general-iframe/index.spec.ts
- bricks/presentational-bricks/src/general-iframe/index.ts
Refs SERVICE_OBSERVE-928
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): should not render if no src property

- bricks/presentational-bricks/src/rank-table/RankTable.module.css
Closes EVENTS-2232
请勾选以下两组选项其中之一：
或者：
>
>
> fix(rank-table): set min-with of ranking box

- bricks/forms/src/general-date-picker/GeneralDatePicker.module.css
- bricks/forms/src/general-date-picker/GeneralDatePicker.spec.tsx
- bricks/forms/src/general-date-picker/GeneralDatePicker.tsx
> fix(forms): 日期选择器禁选日期确定按钮禁用

- bricks/developers/deploy-default/package.conf.yaml
- bricks/developers/package.json
- bricks/developers/src/data-providers/GetProvidersList.spec.ts
- bricks/developers/src/data-providers/GetProvidersList.ts
- bricks/developers/src/provider-providers-sub-menu/processors.spec.ts
- bricks/developers/src/provider-providers-sub-menu/processors.ts
- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/package.json
- bricks/next-builder/src/data-providers/GetAllProviders.spec.ts
- bricks/next-builder/src/data-providers/GetAllProviders.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
- bricks/next-builder/src/data-providers/GetBrickLibrary.ts
- yarn.lock
Refs QUALITY-204
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): replace the api to get the all brick pacakge

- bricks/presentational-bricks/src/rank-table/RankTable.tsx
- bricks/presentational-bricks/src/rank-table/RankTableHelper.tsx
Refs EVENTS-2232
请勾选以下两组选项其中之一：
或者：
>
>
> style(rank-table): refine style

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
- bricks/next-builder/src/data-providers/utils/getBrickPackageIndexJs.ts
- bricks/next-builder/src/data-providers/utils/replaceWidgetFunctions.spec.ts
- bricks/next-builder/src/data-providers/utils/replaceWidgetFunctions.ts
> feat(): support i18n in widgets

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
BRICK_STORE-2333
请勾选以下两组选项其中之一：
或者：
>
>
> feat(select): add easyopsEmptyProps props  Refs

- bricks/next-builder/src/data-providers/ScanBricksAndTemplates.spec.ts
- bricks/next-builder/src/data-providers/ScanBricksAndTemplates.ts
> feat(): support build contract data

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
BRICK_STORE-2333
请勾选以下两组选项其中之一：
或者：
>
>
> fix(select): delete isNil emptyProps  Refs

- bricks/presentational-bricks/src/brick-table/index.spec.ts
- bricks/presentational-bricks/src/brick-table/index.tsx
BRICK_STORE-2334
请勾选以下两组选项其中之一：
或者：
>
>
> feat(brick-table): add exactSearch props 实现前端精确搜索  Refs

- bricks/forms/src/general-radio/index.module.css
> fix(forms): modify general-radio dashboard type style

- bricks/next-builder/src/data-providers/LintStoryboard.spec.ts
- bricks/next-builder/src/data-providers/LintStoryboard.ts
- bricks/next-builder/src/index.ts
> feat(): support linting storyboard

- bricks/forms/src/general-select/GeneralSelect.tsx
Closes EVENT-478
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): select搜索自动剔除前后空格

- bricks/next-builder/src/data-providers/CreateThemeLayout.spec.ts
- bricks/next-builder/src/data-providers/CreateThemeLayout.ts
- bricks/next-builder/src/index.ts
> feat(): new provider: create theme layout

- bricks/forms/src/general-radio/index.module.css
> fix(forms): fix dashboard radio style

- bricks/next-builder/src/data-providers/CreateThemeLayout.spec.ts
- bricks/next-builder/src/data-providers/DeleteThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/DeleteThemeTemplate.ts
- bricks/next-builder/src/index.ts
> feat(): new provider: delete theme template

- bricks/presentational-bricks/src/general-image/GeneralImage.spec.tsx
- bricks/presentational-bricks/src/general-image/GeneralImage.tsx
- bricks/presentational-bricks/src/general-image/index.tsx
- bricks/presentational-bricks/stories/chapters/general-image.ts
Closes BRICK_STORE-2339
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-image): add open and close method

- bricks/presentational-bricks/src/general-image/index.tsx
Refs OS-122
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-image): add visible-change event

- bricks/forms/src/input-with-unit/InputWithUnit.tsx
Refs#MONITOR-2702
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix the bug of that forms cannot update value of this brick

- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.spec.tsx
- bricks/presentational-bricks/src/modal-confirm/ModalConfirm.tsx
Closes MONITOR-2654
请勾选以下两组选项其中之一：
或者：
>
>
> fix(presentational-bricks): 修复modal国际化失效

- bricks/next-builder/src/data-providers/ApplyThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/ApplyThemeTemplate.ts
> fix(): mark `isFromTheme` for templates from theme

- bricks/next-builder/src/data-providers/ApplyThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/ApplyThemeTemplate.ts
- bricks/next-builder/src/data-providers/BuildProjectOfThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfThemeTemplate.ts
- bricks/next-builder/src/data-providers/CreateThemePage.spec.ts
- bricks/next-builder/src/data-providers/CreateThemePage.ts
> fix(): refactor theme locales

- bricks/next-builder/src/data-providers/ApplyThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/ApplyThemeTemplate.ts
- bricks/next-builder/src/data-providers/BuildProjectOfThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfThemeTemplate.ts
- bricks/next-builder/src/data-providers/CreateThemePage.spec.ts
- bricks/next-builder/src/data-providers/CreateThemePage.ts
> feat(): support theme thumbnails

- bricks/developers/src/provider-group-list/ProviderGroupList.tsx
> fix(): add description

- bricks/developers/src/provider-group-list/ProviderGroupList.module.css
- bricks/developers/src/provider-group-list/ProviderGroupList.tsx
> fix(): ui modify

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
- bricks/next-builder/src/shared/storyboard/minimalStoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/minimalStoryboardAssembly.ts
> fix(): appId is not required any more for building storyboard

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/buildPreviewRoutesForTheme.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
> feat(): support theme preview routes for micro-apps too

- bricks/forms/src/general-form/index.spec.ts
- bricks/forms/src/general-form/index.tsx
Refs: NEXT_BUILDER-1161
请勾选以下两组选项其中之一：
或者：
>
>
> feat(GeneralForm): setInitValue support runInMacrotask

- bricks/next-builder/src/data-providers/ApplyThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/ApplyThemeTemplate.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
- bricks/next-builder/src/data-providers/BuildProjectOfThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfThemeTemplate.ts
- bricks/next-builder/src/data-providers/ExperimentalExportThemeTemplate.ts
- bricks/next-builder/src/data-providers/utils/arrayPick.ts
- bricks/next-builder/src/data-providers/utils/getBrickPackageIndexJs.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
> feat(): support i18n, images and functions in theme

- bricks/developers/src/provider-doc/ProviderDoc.tsx
- bricks/developers/src/provider-doc/index.tsx
> fix(): developer doc refactor

- bricks/developers/src/i18n/constants.ts
- bricks/developers/src/i18n/locales/en.ts
- bricks/developers/src/i18n/locales/zh.ts
- bricks/developers/src/provider-doc/ProviderDoc.tsx
- bricks/developers/src/provider-doc/ProviderSample/ProviderSample.module.css
- bricks/developers/src/provider-doc/ProviderSample/ProviderSample.spec.tsx
- bricks/developers/src/provider-doc/ProviderSample/ProviderSample.tsx
- bricks/developers/src/provider-group-menu/ProviderGroupMenu.module.css
- bricks/developers/src/provider-group-menu/ProviderGroupMenu.tsx
- bricks/developers/src/provider-provider-doc/interfaces.ts
> fix(): doc refactor

- bricks/basic-bricks/src/general-drawer/GeneralDrawer.spec.tsx
- bricks/basic-bricks/src/general-drawer/GeneralDrawer.tsx
- bricks/basic-bricks/src/general-drawer/index.shadow.less
- bricks/basic-bricks/src/general-drawer/index.tsx
Closes MONITOR-2788
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks): customSwitchConfig支持文字

- bricks/developers/src/provider-group-menu/ProviderGroupMenu.module.css
> fix(): ui style

- bricks/forms/src/custom-templates/tpl-cmdb-object-attr-add.ts
> fix(cmdb): 结构体属性支持readonly配置

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/builder-container/DataView/scanContextsInStoryboard.ts
- bricks/next-builder/src/data-providers/ScanFunctionsInStoryboard.ts
> refactor(): refine scanning storyboard

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
Refs: NEXT_BUILDER-1198
请勾选以下两组选项其中之一：
或者：
>
>
> feat(StoryboardAssembly): build&push  mocks 结构更新

- bricks/presentational-bricks/src/brick-tree/BrickTree.spec.tsx
- bricks/presentational-bricks/src/brick-tree/BrickTree.tsx
- bricks/presentational-bricks/src/brick-tree/index.module.css
- bricks/presentational-bricks/src/brick-tree/index.tsx
refs NEXT_BUILDER-1233
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 支持按key搜索

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.module.css
- bricks/basic-bricks/src/images/launchpad.svg
- bricks/basic-bricks/src/menu-bar/AppMenu/AppMenu.module.css
- bricks/basic-bricks/src/menu-bar/AppSubMenu/AppSubMenu.module.css
- bricks/basic-bricks/src/menu-bar/CollapseBar/CollapseBar.module.css
- bricks/basic-bricks/src/menu-bar/MenuBar/MenuBar.module.css
Refs BRICK_STORE-2342
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): replace with css varibales

- bricks/basic-bricks/src/general-button/GeneralButton.tsx
- bricks/basic-bricks/src/general-button/index.tsx
refs SERVICE_OBSERVE-1038
请勾选以下两组选项其中之一：
或者：
>
>
> feat(basic-bricks):  add buttonStyle property

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrArr.tsx
Refs#DATA_QUALITY-204
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms):when variable is null, add defalut values

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/menu-bar/AppMenu/AppMenu.module.css
Refs BRICK_STORE-2343
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): menu style

- bricks/next-builder/package.json
- bricks/next-builder/src/data-providers/GetTypeDeclarations.ts
- bricks/next-builder/src/data-providers/GetTypeDeclarationsOfFn.spec.ts
- bricks/next-builder/src/data-providers/GetTypeDeclarationsOfFn.ts
- bricks/next-builder/src/index.ts
- bricks/next-builder/webpack.config.js
- yarn.lock
> feat(): get type declarations for storyboard functions

- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/DataView/utils.spec.ts
- bricks/next-builder/src/builder-container/DataView/utils.ts
Refs: NEXT_BUILDER-1161
请勾选以下两组选项其中之一：
或者：
>
>
> fix(ContextItemForm): fix submit while data error

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
Refs: NEXT_BUILDER-1200
请勾选以下两组选项其中之一：
或者：
>
>
> feat(preStoryboardAssembly): mocks add provider

- bricks/flow-builder/src/custom-processors/getFunctionStep.spec.ts
- bricks/flow-builder/src/custom-processors/getFunctionStep.ts
fixes FLOW_BUILDER-285
请勾选以下两组选项其中之一：
或者：
>
>
> fix(flow-builder): 未设置步骤时,参数设计报错

- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
Refs: NEXT_BUILDER-1308
请勾选以下两组选项其中之一：
或者：
>
>
> fix(ContextItemForm): fix value field error

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/general-button/GeneralButton.module.css
- bricks/presentational-bricks/deploy-default/package.conf.yaml
- bricks/presentational-bricks/src/brick-divider/BrickDivider.module.css
Refs NEXT_BUILDER-1244
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): divider style

- bricks/basic-bricks/src/editor-bricks/fold-brick-v2/fold-brick-v2.editor.module.css
- bricks/basic-bricks/src/editor-bricks/fold-brick-v2/fold-brick-v2.editor.spec.tsx
- bricks/basic-bricks/src/editor-bricks/fold-brick-v2/fold-brick-v2.editor.tsx
- bricks/basic-bricks/src/editor-bricks/index.ts
Refs: NEXT_BUILDER-1309
请勾选以下两组选项其中之一：
或者：
>
>
> feat(fold-brick-v2): add editor

- bricks/basic-bricks/src/fold-brick-v2/FoldBrickV2.tsx
- bricks/basic-bricks/src/fold-brick-v2/index.tsx
Closes EVENT-658
请勾选以下两组选项其中之一：
或者：
>
>
> fix(basic-bricks): 修复fold-brick-v2折叠触发异常

- bricks/presentational-bricks/deploy-default/package.conf.yaml
- bricks/presentational-bricks/src/brick-table/BrickTable.module.css
- bricks/presentational-bricks/src/general-pagination/index.module.css
Refs NEXT_BUILDER-1255
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): pagination style refine

- bricks/basic-bricks/src/general-anchor/GeneralAnchor.spec.tsx
- bricks/basic-bricks/src/general-anchor/GeneralAnchor.tsx
- bricks/basic-bricks/src/general-anchor/index.tsx
Refs: BRICK_STORE-2387
请勾选以下两组选项其中之一：
或者：
>
>
> feat(Anchor): add props: disabledJump, event: anchor.click/anchor.change

- bricks/forms/deploy-default/package.conf.yaml
- bricks/forms/src/general-radio/index.module.css
Refs NEXT_BUILDER-1322
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): radio style refine

- bricks/basic-bricks/src/micro-app/MicroApp.spec.tsx
- bricks/basic-bricks/src/micro-app/MicroApp.tsx
- bricks/basic-bricks/src/micro-app/index.tsx
- bricks/basic-bricks/src/page-title/PageTitle.spec.tsx
- bricks/basic-bricks/src/page-title/PageTitle.tsx
> feat(): add property of `page-title-scale` for micro-view/micro-app

- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvasTabs.module.css
- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvasTabs.tsx
> fix(): handle canvas tabs overflow

- bricks/presentational-bricks/src/brick-general-search/index.module.css
Refs NEXT_BUILDER-1261
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): replace css variables

- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvasTabs.module.css
- bricks/next-builder/src/builder-container/BuilderCanvas/BuilderCanvasTabs.tsx
> fix(): fix scrollbar of canvas tabs

- bricks/basic-bricks/src/general-anchor/index.tsx
Refs: NEXT_BUILDER-2387
请勾选以下两组选项其中之一：
或者：
>
>
> fix(general-anchor): 修复点击事件多次触发

- bricks/forms/src/time-range-picker/TimeRangePicker.spec.tsx
- bricks/forms/src/time-range-picker/TimeRangePicker.tsx
- bricks/forms/src/time-range-picker/index.tsx
refs EVENT-663
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): `time-range-picker`首次onChange，某些场景会有问题

- bricks/forms/stories/chapters/general-checkbox.ts
> docs(): 修改checkbox案例的配置描述

- bricks/basic-bricks/src/general-drawer/index.tsx
> chore(basic-bricks): drawer scrollToTopWhenOpen默认值为true

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/general-modal/index.shadow.less
- bricks/forms/deploy-default/package.conf.yaml
- bricks/forms/src/general-checkbox/GeneralCheckbox.module.css
- bricks/forms/src/general-modal/index.shadow.less
Refs BRICK_STORE-239,BRICK_STORE-2389
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): modal style

- bricks/presentational-bricks/deploy-default/package.conf.yaml
- bricks/presentational-bricks/src/rank-table/RankTable.module.css
- bricks/presentational-bricks/src/rank-table/RankTable.tsx
> fix(): support dark theme

- bricks/presentational-bricks/src/rank-table/RankTable.module.css
> fix(): fix header color of rank-table

- bricks/forms/src/time-range-picker/TimeRangePicker.tsx
Refs BRICK_STORE-2391
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): time range style

- bricks/presentational-bricks/src/dropdown-select/DropdownSelect.module.css
Refs BRICK_STORE-2422
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): use css variables

- bricks/presentational-bricks/src/brick-quick-entries/BrickQuickEntries.tsx
- bricks/presentational-bricks/src/brick-quick-entries/brick-quick-entries.module.css
> fix(): support dark theme in brick-quick-entries

- bricks/general-auth/src/general-login/GeneralLogin.tsx
Refs NEXT_BUILDER-995
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix admin role

- bricks/forms/package.json
- bricks/next-builder/package.json
- yarn.lock
> chore(): update lib version

- bricks/frame-bricks/src/index.ts
- bricks/frame-bricks/src/nav-bar/NavBar.module.css
- bricks/frame-bricks/src/nav-bar/NavBar.shadow.css
- bricks/frame-bricks/src/nav-bar/NavBar.spec.tsx
- bricks/frame-bricks/src/nav-bar/NavBar.tsx
- bricks/frame-bricks/src/nav-bar/__snapshots__/NavBar.spec.tsx.snap
- bricks/frame-bricks/src/nav-bar/index.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/frame-bricks/src/nav-menu/NavMenu.spec.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/nav-menu/index.spec.ts
- bricks/frame-bricks/src/nav-menu/index.tsx
NEXT_BUILDER-1330
请勾选以下两组选项其中之一：
或者：
>
>
> feat(navBrick): support nav brick

- bricks/presentational-bricks/deploy-default/package.conf.yaml
> chore(): update version

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- declarations/global.d.ts
> feat(): support customized log-out when auth guard is ignored

- bricks/forms/src/general-checkbox/GeneralCheckbox.module.css
> fix(): refine styles

- bricks/forms/src/time-range-picker/TimeRangePicker.module.css
- bricks/forms/src/time-range-picker/TimeRangePicker.tsx
Refs BRICK_STORE-2391
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine style

- bricks/forms/src/general-form/index.spec.ts
- bricks/forms/src/general-form/index.tsx
Closes SERVICE_OBSERVE-1036
请勾选以下两组选项其中之一：
或者：
>
>
使用方式
``` yaml
- target: '#form'
method: getFieldsValue
callback:
success:
- action: console.log
args:
- '${EVENT.detail}'
error:
- action: console.log
```
> feat(forms): add method getFieldsValue

- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.spec.tsx
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
- bricks/frame-bricks/src/side-bar/index.spec.ts
- bricks/frame-bricks/src/side-bar/index.tsx
Refs: NEXT_BUILDER-1330
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): Nav支持主题样式，sidebar加入移入移出事件

- bricks/forms/stories/chapters/general-form.ts
> chore(forms): 增加getFieldsValue方法demo

- bricks/forms/src/general-slide/GeneralSlide.module.css
Refs  MONITOR-1923
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): slider style

- bricks/basic-bricks/src/app-bar/DesktopSlider/DesktopSlider.spec.tsx
- bricks/basic-bricks/src/app-bar/DesktopSlider/DesktopSlider.tsx
Refs: LAUNCHPAD-83
请勾选以下两组选项其中之一：
或者：
>
>
> fix(launchButton): fix query custom item couldn't found

- bricks/basic-bricks/src/general-drawer/index.shadow.less
> chore(basic-bricks): style fix

- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.module.css
> chore(forms): style fix

- .size-limit.js
- bricks/presentational-bricks/package.json
> chore(): change basic-components version

- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
> feat(): support customized log-out page by app

- bricks/presentational-bricks/src/index.ts
- bricks/presentational-bricks/src/text-collapse/TextCollapse.spec.tsx
- bricks/presentational-bricks/src/text-collapse/TextCollapse.tsx
- bricks/presentational-bricks/src/text-collapse/index.spec.ts
- bricks/presentational-bricks/src/text-collapse/index.tsx
- bricks/presentational-bricks/src/text-collapse/text-collapse.module.css
- bricks/presentational-bricks/stories/chapters/index.ts
- bricks/presentational-bricks/stories/chapters/text-collapse.ts
close BRICK_STORE-2172
请勾选以下两组选项其中之一：
或者：
>
>
> feat(presentational-bricks): add text-collapse brick

- bricks/forms/src/general-input-number/GeneralInputNumber.tsx
- bricks/forms/src/general-input-number/index.tsx
Refs EASY_AGILE-370
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-input-number): add precision property

- bricks/basic-bricks/src/app-bar/DesktopSlider/DesktopSlider.spec.tsx
- bricks/basic-bricks/src/app-bar/DesktopSlider/DesktopSlider.tsx
> chore(appBar): set enable-my-desktop to true

- bricks/forms/src/general-radio/GeneralRadio.spec.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.module.css
- bricks/forms/src/general-radio/index.tsx
- bricks/forms/stories/chapters/general-radio.ts
refs EVENT-746
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms): `general-radio`  `type` 属性新增  `icon-circle` 类型样式

- bricks/forms/src/general-select/GeneralSelect.spec.tsx
- bricks/forms/src/general-select/GeneralSelect.tsx
- bricks/forms/src/general-select/index.tsx
close QUALITY-417
请勾选以下两组选项其中之一：
或者：
>
>
> feat(generalSelect): add SelectOption tooltip

- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
Refs: NEXT_BUILDER-1330
请勾选以下两组选项其中之一：
或者：
>
>
> style(): update sidebar style

- bricks/next-builder/src/data-providers/ApplyThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/ApplyThemeTemplate.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.spec.ts
- bricks/next-builder/src/data-providers/BuildProjectOfTemplates.ts
- bricks/next-builder/src/data-providers/utils/getBrickPackageIndexJs.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboard.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
- declarations/global.d.ts
> feat(): support building template with state

- bricks/basic-bricks/src/sub-menu-filter/index.module.css
- bricks/forms/src/dynamic-common-item/DynamicCommonItem.module.css
- bricks/forms/src/dynamic-form-item/DynamicFormItem.module.css
Refs BRICK_STORE-2473
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): dynamic form item style refine

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/sub-menu-filter/index.module.css
Refs BRICK_STORE-2466
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix hover style

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
> fix(forms): cmdb-instance-select构件换V3接口

- bricks/presentational-bricks/src/general-transfer/GeneralTransfer.spec.tsx
- bricks/presentational-bricks/src/general-transfer/GeneralTransfer.tsx
> fix(transfer): 穿梭框右边超过最大数支持勾选转换到左边 Refs MONITOR-3013

- bricks/presentational-bricks/src/brick-table/index.tsx
BRICK_STORE-2504
请勾选以下两组选项其中之一：
或者：
>
>
> fix(table): 修复filters没值时导致table没数据的问题 Refs

- bricks/basic-bricks/src/general-anchor/GeneralAnchor.spec.tsx
- bricks/basic-bricks/src/general-anchor/GeneralAnchor.tsx
refs BRICK_STORE-2505
请勾选以下两组选项其中之一：
或者：
>
>
> fix(basic-bricks): 初始锚点位置不对

- bricks/basic-bricks/src/general-anchor/GeneralAnchor.spec.tsx
- bricks/basic-bricks/src/general-anchor/GeneralAnchor.tsx
Refs BRICK_STORE-2505
请勾选以下两组选项其中之一：
或者：
>
>
> fix(rank-table): 初始锚点位置不对

- bricks/presentational-bricks/deploy-default/package.conf.yaml
> chore():update brick_next version

- bricks/developers/src/stories/docs/agile/issue-card.md
- bricks/developers/src/stories/docs/agile/kanban-container.md
> docs(): 补充issue-card和kanban-container的文档f

- bricks/forms/src/general-form/index.tsx
> feat(forms): getFieldsValue support options

- bricks/developers/src/stories/chapters/business-bricks/agile/issue-card.ts
> docs(): issue-card示例

- bricks/developers/src/stories/chapters/business-bricks/agile/issue-card.ts
> docs(): 矫正issue-card文档字段

- bricks/forms/deploy-default/package.conf.yaml
- bricks/forms/src/upload-files-v2/UploadFilesV2.module.css
- bricks/forms/src/upload-files-v2/UploadFilesV2.spec.tsx
- bricks/forms/src/upload-files-v2/UploadFilesV2.tsx
- bricks/presentational-bricks/src/brick-quick-entries/brick-quick-entries.module.css
Refs BRICK_STORE-2475
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): replace new icon

- bricks/next-builder/src/data-providers/RunStoryboardFunctionTests.spec.ts
- bricks/next-builder/src/data-providers/RunStoryboardFunctionTests.ts
> fix(): fix funciton test stats

- bricks/basic-bricks/src/menu-bar/AppMenu/AppMenu.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/frame-bricks/src/nav-menu/NavMenu.spec.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.spec.tsx
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
- bricks/frame-bricks/src/side-bar/index.tsx
> style(): update style

- bricks/forms/src/dynamic-form-item/DynamicFormItem.tsx
- bricks/forms/src/dynamic-form-item/index.tsx
refs EVENT-773
请勾选以下两组选项其中之一：
或者：
>
>
> feat(forms):`type`为`select`时候，增加 `popoverPositionType`属性

- bricks/forms/src/general-radio/index.module.css
refs MONITOR-2915
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): add hover style

- bricks/basic-bricks/src/easy-view/index.tsx
> fix(): simplify easy-view: use shadow root as the mount point

- bricks/next-builder/deploy-default/package.conf.yaml
Refs: NEXT_BUILDER-1426
请勾选以下两组选项其中之一：
或者：
>
>
> chroe(): re package

- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
Refs: ITSERVICE_NEXT-3329
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add last login time

- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/frame-bricks/src/nav-menu/NavMenu.spec.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/nav-menu/index.tsx
- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.spec.tsx
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
- bricks/frame-bricks/src/side-bar/index.tsx
Refs: NEXT_BUILDER-1426
请勾选以下两组选项其中之一：
或者：
>
>
> chroe(): update style

- bricks/presentational-bricks/src/markdown-editor/index.tsx
Refs EASY_AGILE-507
请勾选以下两组选项其中之一：
或者：
>
>
> fix(markdown-editor): pass pattern property to MarkdownEditor

- bricks/next-builder/src/builder-container/StoryboardTreeView/StoryboardTreeView.tsx
> fix(): search brick alias as well

- bricks/basic-bricks/src/app-bar-breadcrumb/AppbarBreadcrumb.module.css
- bricks/basic-bricks/src/app-bar-breadcrumb/AppbarBreadcrumb.spec.tsx
- bricks/basic-bricks/src/app-bar-breadcrumb/AppbarBreadcrumb.tsx
- bricks/basic-bricks/src/app-bar/AppBarBreadcrumb/AppBarBreadcrumb.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.module.css
- bricks/frame-bricks/src/nav-menu/NavMenu.spec.tsx
- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/side-bar/SideBar.spec.tsx
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/SidebarMenu.module.css
Refs: NEXT_BUILDER-1427
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update menu fetch and style update

- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/StoryboardTreeNode/handleDropOnNode.ts
- bricks/next-builder/src/builder-container/index.tsx
- bricks/next-builder/src/index.ts
- bricks/next-builder/src/lazy-bricks.yaml
- bricks/next-builder/src/shared/scrollbar.shadow.css
- bricks/next-builder/src/workbench-action/WorkbenchAction.module.css
- bricks/next-builder/src/workbench-action/WorkbenchAction.spec.tsx
- bricks/next-builder/src/workbench-action/WorkbenchAction.tsx
- bricks/next-builder/src/workbench-action/index.spec.ts
- bricks/next-builder/src/workbench-action/index.tsx
- bricks/next-builder/src/workbench-pane/WorkbenchPane.shadow.css
- bricks/next-builder/src/workbench-pane/WorkbenchPane.spec.tsx
- bricks/next-builder/src/workbench-pane/WorkbenchPane.tsx
- bricks/next-builder/src/workbench-pane/index.spec.ts
- bricks/next-builder/src/workbench-pane/index.tsx
- bricks/next-builder/src/workbench-sidebar/WorkbenchSidebar.shadow.css
- bricks/next-builder/src/workbench-sidebar/WorkbenchSidebar.spec.tsx
- bricks/next-builder/src/workbench-sidebar/WorkbenchSidebar.tsx
- bricks/next-builder/src/workbench-sidebar/index.spec.ts
- bricks/next-builder/src/workbench-sidebar/index.tsx
- bricks/next-builder/src/workbench-tree/WorkbenchTree.module.css
- bricks/next-builder/src/workbench-tree/WorkbenchTree.tsx
- bricks/next-builder/src/workbench-tree/index.spec.ts
- bricks/next-builder/src/workbench-tree/index.tsx
> feat(): add new bricks of workbench

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/general-anchor/GeneralAnchor.module.css
Refs NEXT_BUILDER-1250
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): anchor style

- bricks/next-builder/src/custom-processors/getWorkbenchRouteTree.ts
- bricks/next-builder/src/index.ts
- bricks/next-builder/src/lazy-bricks.yaml
- bricks/next-builder/src/shared/workbench/WorkbenchActionsContext.ts
- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.module.css
- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.module.css
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeContext.ts
- bricks/next-builder/src/shared/workbench/interfaces.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-brick-tree/index.tsx
- bricks/next-builder/src/workbench-mini-action-bar/index.spec.ts
- bricks/next-builder/src/workbench-mini-action-bar/index.tsx
- bricks/next-builder/src/workbench-pane/WorkbenchPane.shadow.css
- bricks/next-builder/src/workbench-pane/WorkbenchPane.tsx
- bricks/next-builder/src/workbench-pane/index.tsx
- bricks/next-builder/src/workbench-store/index.tsx
> feat(): workbench mini action bar

- bricks/basic-bricks/src/app-bar-setting/AppBarSetting.spec.tsx
- bricks/basic-bricks/src/app-bar-setting/AppBarSetting.tsx
- bricks/basic-bricks/src/app-bar-setting/index.spec.ts
- bricks/basic-bricks/src/app-bar-setting/index.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.module.css
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBar/AppBar.tsx
- bricks/basic-bricks/src/app-bar/AppSetting/AppSetting.module.css
- bricks/basic-bricks/src/app-bar/AppSetting/AppSetting.spec.tsx
- bricks/basic-bricks/src/app-bar/AppSetting/AppSetting.tsx
- bricks/basic-bricks/src/index.ts
> feat(): add app-bar-setting brick

- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.tsx
- bricks/next-builder/src/workbench-pane/WorkbenchPane.shadow.css
- bricks/next-builder/src/workbench-sidebar/WorkbenchSidebar.shadow.css
- bricks/next-builder/src/workbench-sidebar/WorkbenchSidebar.tsx
- bricks/next-builder/src/workbench-sidebar/index.tsx
> feat(): resize sidebar

- bricks/next-builder/src/data-providers/ApplyThemeTemplate.ts
- bricks/next-builder/src/data-providers/ReplaceSingleThemePage.spec.ts
- bricks/next-builder/src/data-providers/ReplaceSingleThemePage.ts
- bricks/next-builder/src/data-providers/utils/mergeVersion.spec.ts
- bricks/next-builder/src/data-providers/utils/mergeVersion.ts
- bricks/next-builder/src/index.ts
> feat(): support merge version and replace theme

- bricks/next-builder/src/data-providers/utils/mergeVersion.spec.ts
- bricks/next-builder/src/data-providers/utils/mergeVersion.ts
> fix(): fix bug when arguments is undefined

- bricks/next-builder/src/custom-processors/getWorkbenchRouteTree.ts
- bricks/next-builder/src/shared/scrollbar.shadow.css
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/workbench-context-menu/WorkbenchContextMenu.module.css
> fix(): refine workbench

- bricks/forms/stories/chapters/dynamic-form-item.ts
> chore(forms): deprecate dynamic-form-item

- bricks/frame-bricks/src/nav-menu/NavMenu.tsx
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/next-builder/src/data-providers/utils/fetchFullData.spec.ts
> fix(): bug fix

- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-brick-tree/index.tsx
> fix(): refine workbench tree

- bricks/basic-bricks/src/event-agent/index.spec.ts
- bricks/basic-bricks/src/event-agent/index.ts
- bricks/basic-bricks/src/index.ts
> feat(): support event-agent

- bricks/next-builder/src/workbench-store/WorkbenchStore.tsx
- bricks/next-builder/src/workbench-store/index.tsx
> feat(): support deleting node

- bricks/brick-visualization/package.json
- bricks/flow-builder/package.json
- bricks/forms/package.json
- bricks/presentational-bricks/package.json
- yarn.lock
> chore(): update lib

- bricks/next-builder/src/preview-container/PreviewContainer.module.css
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
> fix(): simplyfy preview-container

- bricks/basic-bricks/src/general-button/GeneralButton.module.css
- bricks/basic-bricks/src/general-custom-buttons/index.module.css
Refs NEXT_BUILDER-1258
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): button style

- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.tsx
- bricks/forms/src/interfaces/dynamic-form-item-v2.ts
> feat(forms): support defaultValue

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrFloat.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
- bricks/forms/src/cmdb-object-attr-value/index.tsx
refs INSTANCE-2258
refs VIEW-387
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): 新建结构体从已有模型中引入，回填regex&浮点型去除限制位数

- bricks/forms/src/upload-files-v2/index.tsx
> fix(forms): support labelTooltip

- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.tsx
- bricks/forms/src/dynamic-form-item-v2/DynamicFormItemV2.tsx
- bricks/forms/src/interfaces/dynamic-form-item-v2.ts
> feat(forms): support uniq rule

- bricks/basic-bricks/src/app-bar/AppSetting/AppSetting.tsx
Refs BRICK_STORE-2625
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): replace icon

- bricks/next-builder/src/custom-processors/getWorkbenchRouteTree.ts
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeContext.ts
- bricks/next-builder/src/shared/workbench/interfaces.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-brick-tree/index.tsx
- bricks/next-builder/src/workbench-tree/index.tsx
> feat(workbench-tree): support click on tree node

- bricks/basic-bricks/src/resizable-box/ResizableBox.shadow.css
- bricks/basic-bricks/src/resizable-box/ResizableBox.tsx
- bricks/basic-bricks/src/resizable-box/index.tsx
> fix(resizable-box): allow setting style when not resizing

- bricks/basic-bricks/src/page-error/PageError.tsx
> feat(): basic-bricks.page-error支持展示错误详情 refs DEVOPS_MANAGEMENT-347

- bricks/forms/src/general-radio/GeneralRadio.spec.tsx
- bricks/forms/src/general-radio/GeneralRadio.tsx
- bricks/forms/src/general-radio/index.module.css
- bricks/forms/src/general-radio/index.tsx
> feat(): raido add type

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.module.css
- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.tsx
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-brick-tree/index.tsx
- bricks/next-builder/src/workbench-mini-action-bar/index.tsx
- bricks/next-builder/src/workbench-store/WorkbenchStore.tsx
- bricks/next-builder/src/workbench-store/index.tsx
> feat(): support move node up or down

- bricks/forms/src/upload-img/UploadImg.spec.tsx
- bricks/forms/src/upload-img/UploadImg.tsx
> fix(forms): 修复maxNumber为1时图片无法删除

- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.spec.tsx
- bricks/forms/src/dynamic-form-item-v2/ColumnComponent.tsx
- bricks/forms/src/interfaces/dynamic-form-item-v2.ts
> feat(forms): rules.validator可获取更多数据进行校验

- bricks/general-auth/src/general-login/GeneralLogin.spec.tsx
- bricks/general-auth/src/general-login/GeneralLogin.tsx
> fix(login): 用最后一次登录方式前判断下在不在配置内

- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.spec.tsx
- bricks/next-builder/src/builder-container/BuilderToolbox/BuilderToolbox.tsx
- bricks/next-builder/src/builder-container/index.tsx
- bricks/next-builder/src/data-providers/ApplyThemePage.spec.ts
- bricks/next-builder/src/data-providers/ApplyThemePage.ts
- bricks/next-builder/src/data-providers/ApplyThemeTemplate.spec.ts
- bricks/next-builder/src/data-providers/ApplyThemeTemplate.ts
> feat(): support context for theme snippet

- bricks/basic-bricks/src/images/launchpad.svg
Refs BRICK_STORE-2636
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix icon color

- bricks/forms/src/advance-setting/style.shadow.less
> fix(): 修改forms.advanced.setting样式   Closes BRICK_STORE-2657

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
> fix(cmdb): 结构项类型不可以修改

- bricks/next-builder/package.json
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.module.css
- bricks/next-builder/src/workbench-store/useHoverOnBrick.ts
- bricks/next-builder/src/workbench-store/useListenOnPreviewMessage.spec.tsx
- bricks/next-builder/src/workbench-store/useListenOnPreviewMessage.ts
- bricks/next-previewer/package.json
- bricks/next-previewer/src/preview-helper/inspector.ts
- bricks/next-previewer/src/preview-helper/overlay.spec.ts
- bricks/next-previewer/src/preview-helper/overlay.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- lerna.json
- package.json
- types/preview/index.d.ts
- types/preview/package.json
> feat(): support context menu on preview

- bricks/forms/package.json
> chore(): 重新打包

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
when container is oversized
请勾选以下两组选项其中之一：
或者：
>
>
> fix(preview): fix context menu position

- bricks/presentational-bricks/src/brick-tree/index.module.css
Refs#BRICK_STORE-2651
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): adapt to the dark theme

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.spec.tsx
- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
> fix(cmdb): 未保存的结构项可以修改类型

- bricks/forms/src/general-select/GeneralSelect.tsx
> feat(forms): support select-option disabled

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-previewer/deploy-default/package.conf.yaml
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> feat(): support updating storyboard on the fly

- bricks/presentational-bricks/src/brick-illustration/BrickIllustration.tsx
- bricks/presentational-bricks/src/brick-illustration/index.module.css
Closese DESIGNER_ROUTINE-546
请勾选以下两组选项其中之一：
或者：
>
>
> fix(brick-illustration ): 修改空状态占比优化

- bricks/basic-bricks/src/app-bar-breadcrumb/AppbarBreadcrumb.spec.tsx
- bricks/basic-bricks/src/app-bar-breadcrumb/AppbarBreadcrumb.tsx
- bricks/basic-bricks/src/app-bar/AppBarBreadcrumb/AppBarBreadcrumb.spec.tsx
- bricks/basic-bricks/src/app-bar/AppBarBreadcrumb/AppBarBreadcrumb.tsx
- bricks/basic-bricks/src/app-document-link/AppDocumentLink.spec.tsx
- bricks/basic-bricks/src/app-document-link/AppDocumentLink.tsx
- bricks/basic-bricks/src/app-document-link/index.spec.ts
- bricks/basic-bricks/src/app-document-link/index.tsx
- bricks/basic-bricks/src/general-text/GeneralText.spec.tsx
- bricks/basic-bricks/src/general-text/GeneralText.tsx
- bricks/basic-bricks/src/general-text/index.spec.ts
- bricks/basic-bricks/src/general-text/index.tsx
- bricks/basic-bricks/src/index.ts
Refs: THEME_BUILDER-4
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): theme-brick support

- bricks/next-builder/src/shared/workbench/interfaces.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
> fix(workbench): show root node

- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeContext.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-tree/index.tsx
> fix(workbench): support setting initial padding

- bricks/presentational-bricks/src/general-carousel/index.tsx
> fix: support general-carousel

- bricks/next-builder/src/shared/workbench/interfaces.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-brick-tree/index.tsx
> fix(): refine workbench runtime node

- bricks/next-builder/src/shared/storyboard/buildPreviewRoutesForTheme.ts
Refs: THEME_BUILDER-4
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): theme build & push support context

- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
Refs: THEME_BUILDER-4
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix theme build add sort rule

- bricks/next-builder/src/preview-container/PreviewContainer.module.css
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/workbench-store/WorkbenchStore.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.ts
- bricks/next-builder/src/workbench-store/useListenOnPreviewMessage.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> feat(): refine highlight brick

- bricks/next-builder/src/preview-container/PreviewContainer.module.css
> fix(): refine brick outline style

- bricks/forms/src/cmdb-object-attr-value/components/ObjectAttrStruct.tsx
> fix(forms): fix新建的结构项编辑一次后类型就不能更改bug

- bricks/frame-bricks/src/side-bar/SideBar.module.css
- bricks/frame-bricks/src/side-bar/SideBar.spec.tsx
- bricks/frame-bricks/src/side-bar/SideBar.tsx
- bricks/frame-bricks/src/side-bar/index.spec.ts
- bricks/frame-bricks/src/side-bar/index.tsx
Refs: THEME_BUILDER-4
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): sidebar style position use sticky

- bricks/next-builder/src/workbench-sidebar/WorkbenchSidebar.shadow.css
- bricks/next-builder/src/workbench-tree/index.tsx
> feat(workbench): support click on tree

- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.spec.tsx
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
- bricks/brick-visualization/src/visual-property-form/components/MenuEditor/MenuEditorItem.spec.tsx
- bricks/brick-visualization/src/visual-property-form/components/MenuEditor/MenuEditorItem.tsx
- bricks/brick-visualization/src/visual-property-form/constant.ts
- bricks/brick-visualization/src/visual-property-form/index.tsx
- bricks/brick-visualization/src/visual-property-form/processor.spec.ts
- bricks/brick-visualization/src/visual-property-form/processor.ts
Refs: THEME_BUILDER-7
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): visualPropertyForm support MenuType

- bricks/next-builder/src/data-providers/CreateThemePage.spec.ts
- bricks/next-builder/src/data-providers/CreateThemePage.ts
Refs: THEME_BUILDER-27
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support create theme with page template

- bricks/next-builder/src/preview-container/PreviewContainer.module.css
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-store/WorkbenchStore.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.spec.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.ts
- bricks/next-builder/src/workbench-store/useListenOnPreviewMessage.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> fix(): support highlight custom-template

- bricks/presentational-bricks/src/general-pagination/index.spec.ts
- bricks/presentational-bricks/src/general-pagination/index.tsx
> feat():general-pagination构件分页和设置页数时不刷新页面  refs ORCHESTRATION-73

- bricks/utils/package.json
- bricks/utils/src/broadcast-channel/BroadcastChannel.spec.tsx
- bricks/utils/src/broadcast-channel/BroadcastChannel.tsx
- bricks/utils/src/broadcast-channel/polyfill.ts
- yarn.lock
> fix(): fix compatibility of broadcast-channel in safari

- bricks/next-builder/src/data-providers/ScanBricksAndTemplates.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
Refs FLOW_BUILDER-314
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): add contract field

- bricks/presentational-bricks/stories/chapters/brick-rate.ts
> refactor(): 修改brick-rate默认浅色系颜色 refs BRICK_STORE-2660

- bricks/next-builder/src/shared/workbench/WorkbenchTree.module.css
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeContext.ts
- bricks/next-builder/src/shared/workbench/interfaces.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-brick-tree/index.tsx
- bricks/next-builder/src/workbench-tree/index.tsx
> feat(): support search in workbench tree

- bricks/forms/src/general-select/GeneralSelect.tsx
Refs: BRICK_STORE-2669
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 去除下拉框打开时第一个选项的默认hover态

- bricks/next-builder/src/shared/workbench/WorkbenchTree.module.css
> fix(): refine workbench tree style

- bricks/presentational-bricks/stories/chapters/brick-rate.ts
> refactor(): 更换rate颜色写法 refs BRICK_STORE-2660

- bricks/next-builder/src/preview-container/PreviewContainer.module.css
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
> feat(workbench): support setting viewport size

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
> feat(preview): support reporting viewport scale

- bricks/basic-bricks/src/app-bar/DesktopSlider/DesktopSlider.module.css
> fix(): wrap desktop selector

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/workbench-store/useListenOnPreviewMessage.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> fix(): trigger re-computing active/hover node outlines

- bricks/next-previewer/src/preview-helper/previewStart.ts
> fix(): observe mutations and re-sending hover/active brick outlines

- bricks/forms/src/general-switch/GeneralSwitch.spec.tsx
- bricks/forms/src/general-switch/GeneralSwitch.tsx
- bricks/forms/src/general-switch/index.tsx
heckedIcon properties
Refs EASY_AGILE-624
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-switch): add checkedText unCheckedText checkedIcon and unC

- bricks/flow-builder/src/schema-editor/components/schema-item/SchemaItem.tsx
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.spec.ts
- bricks/flow-builder/src/schema-editor/processor/schemaEditor.ts
Refs NEXT_BUILDER-853
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix field type

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> feat(): do not inspect when route is not matching

- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.spec.tsx
- bricks/next-builder/src/workbench-store/useHighlightBrick.ts
> fix(): show active context menu node as hover node

- bricks/flow-builder/src/schema-editor/components/add-property-modal/AddPropertyModal.tsx
Refs C_CENTER-6
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): reset fields refine

- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
> test(): add some tests for workbench components

- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.spec.tsx
- bricks/next-builder/src/builder-container/BuilderContextMenu/BuilderContextMenu.tsx
- bricks/next-builder/src/builder-container/interfaces.ts
- bricks/next-builder/src/data-providers/CreateThemePage.spec.ts
- bricks/next-builder/src/data-providers/CreateThemePage.ts
- bricks/next-builder/src/data-providers/PasteBricks.spec.ts
- bricks/next-builder/src/data-providers/PasteBricks.ts
- bricks/next-builder/src/index.ts
- bricks/next-builder/src/shared/storyboard/getBaseGraphParams.ts
> feat(): support cut and copy bricks with link tpl

- bricks/next-builder/src/preview-container/PreviewContainer.module.css
> fix(): fix preview iframe style

- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.module.css
- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
> fix(workbench-tree): auto disable move actions

- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-previewer/src/preview-helper/previewStart.spec.ts
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> fix(): re-update tempalate preview after login

- bricks/forms/src/general-radio/index.module.css
SERVICE_OBSERVE-1280
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): change radio styles

- bricks/next-builder/src/index.ts
- bricks/next-builder/src/lazy-bricks.yaml
- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.module.css
- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.tsx
- bricks/next-builder/src/workbench-tabs/index.spec.ts
- bricks/next-builder/src/workbench-tabs/index.tsx
> feat(): new brick: workbench-tabs

- bricks/basic-bricks/src/general-drawer/index.tsx
> fix(drawer): 抽屉增加scroll方法

- bricks/next-builder/src/shared/workbench/WorkbenchTree.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeContext.ts
- bricks/next-builder/src/workbench-tree/index.tsx
> feat(workBenchTree): support calc node name

- bricks/basic-bricks/src/general-card/GeneralCard.tsx
- bricks/basic-bricks/src/general-card/index.shadow.less
- bricks/basic-bricks/src/general-card/index.tsx
> fix(general-card): 修复没有footer也显示分割线的问题

- bricks/next-builder/src/shared/workbench/WorkbenchTextIcon.module.css
- bricks/next-builder/src/shared/workbench/WorkbenchTextIcon.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/interfaces.ts
- bricks/next-builder/src/workbench-tabs/WorkbenchTabs.tsx
> feat(workbench): show text icon

- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.spec.tsx
- bricks/brick-visualization/src/visual-property-form/VisualPropertyForm.tsx
- bricks/next-builder/src/event-config-form/EventConfigForm.tsx
- bricks/next-builder/src/events-editor/EventsEditor.module.css
- bricks/next-builder/src/events-editor/components/add-event-btn/AddEventBtn.module.css
- bricks/next-builder/src/events-editor/components/handler-item/HandlerItem.module.css
Refs NEXT_BUILDER-1505
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): dark mode

- bricks/next-builder/src/shared/workbench/WorkbenchTree.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/workbench-tree/index.tsx
> fix(): support workbench-tree with no search

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/cmdb-instance-select/index.tsx
> feat(forms): support ignoreMissingFieldError

- bricks/basic-bricks/deploy-default/package.conf.yaml
- bricks/basic-bricks/src/general-card/GeneralCard.tsx
- bricks/basic-bricks/src/general-card/index.shadow.less
- bricks/basic-bricks/src/general-card/index.tsx
Refs NEXT_BUILDER-1249
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复 hasFooter 属性不生效问题

- bricks/forms/package.json
- yarn.lock
> chore(deps): Update dependency @next-libs/cmdb-instances to ^6.21.18

- bricks/basic-bricks/src/i18n/locales/zh.ts
> refactor(): 修改NOT_FOUND提示语

- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
Refs: NEXT_BUILDER-1520
请勾选以下两组选项其中之一：
或者：
>
>
> feat(workbenchBrickTree): support display snippet

- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
> fix(): fix snippet icon

- bricks/next-builder/src/custom-processors/getWorkbenchRouteTree.spec.ts
- bricks/next-builder/src/custom-processors/getWorkbenchRouteTree.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.spec.tsx
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-brick-tree/index.tsx
- bricks/next-builder/src/workbench-context-menu/WorkbenchContextMenu.spec.tsx
- bricks/next-builder/src/workbench-context-menu/WorkbenchContextMenu.tsx
> test(): add tests for workbench components

- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
> fix(): mark mount point type

- bricks/general-auth/deploy-default/package.conf.yaml
Refs INFRA-1182
请勾选以下两组选项其中之一：
或者：
>
>
> chore(): Update api_gateway dependency to ^1.52.1

- bricks/next-builder/src/shared/workbench/WorkbenchTree.module.css
- bricks/next-builder/src/shared/workbench/WorkbenchTree.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeContext.ts
- bricks/next-builder/src/workbench-tree/index.tsx
> fix(workbench-tree): support fixed actions

- bricks/next-builder/package.json
- bricks/next-builder/src/function-debugger-store/FunctionDebuggerStore.spec.tsx
- bricks/next-builder/src/shared/functions/FunctionDebuggerFactory.ts
- yarn.lock
> fix(): support mock date in storyboard functions

- bricks/next-builder/src/shared/workbench/WorkbenchActionsContext.ts
- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchMiniActionBar.tsx
- bricks/next-builder/src/workbench-tree/index.tsx
> feat(workbench-actions): support hidden actions

- .gitignore
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
> fix(preview-container): support route.match event

- bricks/next-builder/src/workbench-sidebar/index.tsx
> fix(workbench-sidebar): support setting active flex for children

- bricks/next-builder/deploy-default/package.conf.yaml
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
- bricks/next-builder/src/preview-container/index.tsx
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
- bricks/next-previewer/deploy-default/package.conf.yaml
- bricks/next-previewer/src/preview-helper/previewStart.ts
- types/preview/index.d.ts
> feat(): support snippet preview

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.spec.ts
- bricks/next-builder/src/shared/storyboard/buildStoryboardV2.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
Refs NEXT_BUILDER-1554
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 基于当前编辑后的 storyboard 的数据搜集 contract 信息

- bricks/forms/src/user-or-user-group-select/UserOrUserGroupSelect.module.css
refs EVENT-867
请勾选以下两组选项其中之一：
或者：
>
>
> fix(forms): user-or-user-group-select选项过长，样式溢出

- bricks/next-builder/src/builder-container/BuilderContainer.tsx
- bricks/next-builder/src/builder-container/BuilderUIContext.ts
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
- bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
- bricks/next-builder/src/builder-container/index.tsx
Refs NEXT_BUILDER-1560
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support flow api

- bricks/next-builder/src/shared/components/contract-auto-complete/useContract.spec.ts
- bricks/next-builder/src/shared/components/contract-auto-complete/useContract.ts
Refs NEXT_BUILDER-1564
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): Optimize error display

- bricks/forms/package.json
- yarn.lock
close TRANSFER-97
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): change depencies

- bricks/forms/src/general-form/GeneralForm.spec.tsx
- bricks/forms/src/general-form/GeneralForm.tsx
> fix(forms): 修复表单项中下拉框文本太长导致超出容器的问题 Refs EVENT-867

- bricks/basic-bricks/stories/chapters/flex-layout.ts
> docs(flex-layout): 修改构件文档示例

- bricks/basic-bricks/src/general-popup/GeneralPopup.spec.tsx
- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
- bricks/basic-bricks/src/general-popup/index.spec.ts
- bricks/basic-bricks/src/general-popup/index.tsx
- bricks/basic-bricks/src/general-popup/style.shadow.css
- bricks/basic-bricks/src/index.ts
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
Refs: NEXT_BUILDER-1557
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add general-popup brick

- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.spec.tsx
- bricks/forms/src/cmdb-instance-select/CmdbInstanceSelect.tsx
- bricks/forms/src/cmdb-instance-select/index.tsx
Refs#INSTANCE-2333
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 添加showKey入参情况下的实例默认展示

- bricks/forms/src/general-form/GeneralForm.tsx
> fix(forms): 修复layout: inline情况下，forms容器宽度由items项撑开 Refs EVENT-867

- bricks/next-builder/src/shared/components/contract-auto-complete/index.spec.ts
- bricks/next-builder/src/shared/components/contract-auto-complete/index.tsx
Refs NEXT_BUILDER-1572
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复编辑契约时光标偏移问题

- bricks/basic-bricks/src/general-button/GeneralButton.spec.tsx
- bricks/basic-bricks/src/general-button/GeneralButton.tsx
> fix(): fix preview of disabled button

- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.spec.ts
- bricks/next-builder/src/shared/storyboard/StoryboardAssembly.ts
- bricks/next-builder/src/shared/storyboard/interfaces.ts
- bricks/next-builder/src/shared/storyboard/preStoryboardAssembly.ts
Refs: NEXT_BUILDER-1571
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): mock use method

- bricks/next-builder/src/shared/workbench/WorkbenchTree.spec.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTree.tsx
- bricks/next-builder/src/shared/workbench/WorkbenchTreeContext.ts
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.spec.tsx
- bricks/next-builder/src/workbench-brick-tree/WorkbenchBrickTree.tsx
- bricks/next-builder/src/workbench-brick-tree/index.tsx
> feat(): support emitting event of node toggle

- CONTRIBUTING.md
> docs(): update contributing guide about development with instance preview

- bricks/basic-bricks/src/general-popup/GeneralPopup.spec.tsx
- bricks/basic-bricks/src/general-popup/GeneralPopup.tsx
- bricks/basic-bricks/src/general-popup/index.tsx
- bricks/basic-bricks/src/general-popup/style.shadow.css
Refs: NEXT_BUILDER-1575
请勾选以下两组选项其中之一：
或者：
>
>
> feat(general-popup):  support storage and limit

- bricks/next-builder/src/preview-container/PreviewContainer.module.css
- bricks/next-builder/src/preview-container/PreviewContainer.tsx
> fix(): hide brick outline when not inspecting
